- .travis.yml
I'll need to also connect the repo to Travis after this PR is merged before it starts being run.
> Add a configuration file so we can use Travis CI

- truffle/com.oracle.truffle.api.object/src/com/oracle/truffle/api/object/Layout.java
- truffle/com.oracle.truffle.api.object/src/com/oracle/truffle/api/object/Location.java
- truffle/com.oracle.truffle.api.object/src/com/oracle/truffle/api/object/Property.java
- truffle/com.oracle.truffle.object.basic/src/com/oracle/truffle/object/basic/BasicLayout.java
- truffle/com.oracle.truffle.object.basic/src/com/oracle/truffle/object/basic/ShapeBasic.java
- truffle/com.oracle.truffle.object/src/com/oracle/truffle/object/LayoutImpl.java
This PR adds some comments to `Layout.createShape(..)`, `Location`, and `Property`.
Not sure whether the term 'language-specific' is ideal, but I wanted to document which elements are free for implementers to use.
Ping @jtulach and @woess.
> Improved documentation of some object model classes

- README.md
Update of https://github.com/graalvm/truffle/pull/7
> README: github.com/OracleLabs/GraalVM is deprecated.

- README.md
This test case fails to access the global object of SL.
It raises `IllegalStateException("Accessor.findLanguage access to vm")`, while it probably shouldn't.
> Test case for a potential bug in the polyglot engine.

- truffle/com.oracle.truffle.api.object/src/com/oracle/truffle/api/object/Layout.java
- truffle/com.oracle.truffle.api.object/src/com/oracle/truffle/api/object/Property.java
These issues cause `mx javadoc --unified` to report errors.
> Fixed JavaDoc issues in object model docs

- mx.truffle/mx_truffle.py
- truffle/com.oracle.truffle.api.object/src/com/oracle/truffle/api/object/Layout.java
- truffle/com.oracle.truffle.api.object/src/com/oracle/truffle/api/object/Property.java
Calling mx.javadoc(...) from the gate.
> Making 'mx javadoc --unified' part of the gate

- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/source/Source.java
- truffle/com.oracle.truffle.object.basic/src/com/oracle/truffle/object/basic/BasicAllocator.java
- truffle/com.oracle.truffle.object.basic/src/com/oracle/truffle/object/basic/DefaultStrategy.java
- truffle/com.oracle.truffle.object.basic/src/com/oracle/truffle/object/basic/DynamicObjectBasic.java
- truffle/com.oracle.truffle.object.basic/src/com/oracle/truffle/object/basic/ShapeBasic.java
- truffle/com.oracle.truffle.object/src/com/oracle/truffle/object/DynamicObjectImpl.java
- truffle/com.oracle.truffle.object/src/com/oracle/truffle/object/ObjectStorageOptions.java
just some javadoc cleanup and object model access modifier fixes in the implementation package.
> minor javadoc cleanup and access modifier fixes

- truffle/com.oracle.truffle.api.test/src/com/oracle/truffle/api/vm/EngineTest.java
- truffle/com.oracle.truffle.api.test/src/com/oracle/truffle/api/vm/ImplicitExplicitExportTest.java
- truffle/com.oracle.truffle.api.vm/src/com/oracle/truffle/api/vm/PolyglotEngine.java
- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/TruffleLanguage.java
- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/impl/Accessor.java
This change allows to pass an array of strings to the polyglot engine and retrieve it in the environment object.
The goal is to provide a straight-forward way to pass implementation-level arguments, as the typically come from the command line to the `PolyglotEngine` and the languages.
At the moment, we need to jump through many many hoops.
To realize the same effect, in a language-specific way, it seems we need to do roughly the following:
1. we need some wrapper class to be able to get to the value later on in the language:
```Java
public static class CmdArgWrapper<T> implements TruffleObject {
private final T obj;
public CmdArgWrapper(final T obj) {
this.obj = obj;
}
public T getObject() {
return obj;
}
@Override
public ForeignAccess getForeignAccess() {
throw new …
```
> Enable passing of arguments to the polyglot engine

- truffle/com.oracle.truffle.api.dsl/src/com/oracle/truffle/api/dsl/UnsupportedSpecializationException.java
the actual data types that weren't successfully specialized on are not always visible from the "toString()" of the values - this change adds a list of type names.
> better message for UnsupportedSpecializationException: include data types

- truffle/com.oracle.truffle.api.test/src/com/oracle/truffle/api/vm/IsMimeTypeSupportedTest.java
- truffle/com.oracle.truffle.api.test/src/com/oracle/truffle/api/vm/IsMimeTypeSupportedTestLanguage.java
- truffle/com.oracle.truffle.api.vm/src/com/oracle/truffle/api/vm/PolyglotEngine.java
- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/TruffleLanguage.java
- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/impl/Accessor.java
I want to know what languages are supported in a `PolyglotEngine`. The pressing use-case is in JRuby+Truffle where I want to know if I have a JS interpreter available. I'm currently doing this by just trying to eval with `application/javascript` and catching any error as an indication that it isn't available. This patch instead checks what languages are available first.
https://github.com/jruby/jruby/compare/truffle-execjs...truffle-execjs-list-languages#diff-0c9caf96978e9602deec3f1fca2d97a8L68
The workaround before this patch is slow, even if I end up not using the JavaScript interpreter after finding that it is available. This is 3rd party code for the most part so I can't redesign much.
This is a new API, so a 'large' review. @jtulach @chumer @woess
> Add Env#getSupportedMimeTypes()

- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/frame/FrameSlot.java
Accidentally invoking toString might lead to huge graphs potentially causing the compiler to run OOM. This assertion should help catching such errors upfront.
> assert neverPartOfCompilation in FrameSlot.toString

- CONTRIBUTING.md
- truffle/com.oracle.truffle.api.dsl.test/src/com/oracle/truffle/api/dsl/test/SourceSectionTest.java
- truffle/com.oracle.truffle.api.dsl.test/src/com/oracle/truffle/api/dsl/test/TypeSystemTest.java
- truffle/com.oracle.truffle.api.dsl/src/com/oracle/truffle/api/dsl/internal/DSLShare.java
- truffle/com.oracle.truffle.api.test/src/com/oracle/truffle/api/ArgumentsTest.java
- truffle/com.oracle.truffle.api.test/src/com/oracle/truffle/api/ChildNodeTest.java
- truffle/com.oracle.truffle.api.test/src/com/oracle/truffle/api/ChildrenNodesTest.java
- truffle/com.oracle.truffle.api.test/src/com/oracle/truffle/api/FinalFieldTest.java
- truffle/com.oracle.truffle.api.test/src/com/oracle/truffle/api/FrameSlotTypeSpecializationTest.java
- truffle/com.oracle.truffle.api.test/src/com/oracle/truffle/api/FrameTest.java
- truffle/com.oracle.truffle.api.test/src/com/oracle/truffle/api/InterfaceChildFieldTest.java
- truffle/com.oracle.truffle.api.test/src/com/oracle/truffle/api/ReplaceTest.java
- truffle/com.oracle.truffle.api.test/src/com/oracle/truffle/api/ReturnTypeSpecializationTest.java
- truffle/com.oracle.truffle.api.test/src/com/oracle/truffle/api/ThreadSafetyTest.java
- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/impl/Accessor.java
- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/nodes/Node.java
- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/nodes/RootNode.java
- truffle/com.oracle.truffle.sl.test/src/com/oracle/truffle/sl/test/SLDebugTest.java
- truffle/com.oracle.truffle.sl/src/com/oracle/truffle/sl/nodes/SLStatementNode.java
- truffle/com.oracle.truffle.sl/src/com/oracle/truffle/sl/nodes/controlflow/SLRepeatingNode.java
- truffle/com.oracle.truffle.tools.test/src/com/oracle/truffle/tools/test/ToolTestUtil.java
According to discussion in #25 it seems that there is a general consensus that SourceSections should be handled by individual languages and the interface in Truffle API simplified to:
- Node.getSourceSection() that can be implemented by subclasses
- RootNode(SourceSection, ...) constructor accepting SourceSection as majority of RootNode instances have source section
The other methods are deprecated while the functionality is kept. Once the deprecated methods are removed, the Node#sourceSection field will be removed as well. RootNode will then get such field to hold the value provided in constructor.
> Source section less node

- truffle/com.oracle.truffle.api.interop/snapshot.sigtest
- truffle/com.oracle.truffle.api.interop/src/com/oracle/truffle/api/interop/GetSize.java
- truffle/com.oracle.truffle.api.interop/src/com/oracle/truffle/api/interop/HasSize.java
- truffle/com.oracle.truffle.api.interop/src/com/oracle/truffle/api/interop/IsBoxed.java
- truffle/com.oracle.truffle.api.interop/src/com/oracle/truffle/api/interop/IsExecutable.java
- truffle/com.oracle.truffle.api.interop/src/com/oracle/truffle/api/interop/IsNull.java
- truffle/com.oracle.truffle.api.interop/src/com/oracle/truffle/api/interop/Message.java
- truffle/com.oracle.truffle.api.interop/src/com/oracle/truffle/api/interop/Read.java
- truffle/com.oracle.truffle.api.interop/src/com/oracle/truffle/api/interop/Unbox.java
- truffle/com.oracle.truffle.api.interop/src/com/oracle/truffle/api/interop/Write.java
- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/impl/DefaultCompilerOptions.java
- truffle/com.oracle.truffle.dsl.processor/src/com/oracle/truffle/dsl/processor/java/model/CodeNames.java
- truffle/com.oracle.truffle.object/src/com/oracle/truffle/object/ObjectStorageOptions.java
All `Message` statics are `final` except `WRITE`.
* The various `INSTANCE` fields are also not final, but accessed only here, should we make them `final` as well?
> Make Message.WRITE final

- truffle/com.oracle.truffle.api.vm/src/com/oracle/truffle/api/vm/PolyglotEngine.java
- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/impl/Accessor.java
- truffle/com.oracle.truffle.tck/src/com/oracle/truffle/tck/BoxedValue.java
Use the preferable self-documenting `Objects.requireNonNull` method instead of `obj.getClass()` to null-check arguments.
> use Objects.requireNonNull instead of obj.getClass for null checks

- truffle/com.oracle.truffle.api.dsl.test/src/com/oracle/truffle/api/dsl/test/examples/FunctionCall.java
- truffle/com.oracle.truffle.api.dsl/src/com/oracle/truffle/api/dsl/internal/DSLShare.java
- truffle/com.oracle.truffle.api.interop/src/com/oracle/truffle/api/interop/ForeignAccess.java
- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/frame/FrameDescriptor.java
- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/frame/FrameSlot.java
- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/impl/Accessor.java
- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/nodes/Node.java
- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/nodes/NodeUtil.java
- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/nodes/RootNode.java
- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/source/Source.java
- truffle/com.oracle.truffle.object/src/com/oracle/truffle/object/ShapeImpl.java
While debugging a failed compilation, I missed those bailout messages. They would have sped up my debugging process. (I was not able to use e.g. TruffleCompilationExceptionsArePrinted from the binary I used).
IMHO we should even deprecate the option NOT to provide a message, but that's a different story.
> provide bailout messages for usages of CompilerAsserts.neverPartOfCompilation()

- truffle/com.oracle.truffle.api.instrumentation.test/src/com/oracle/truffle/api/instrumentation/SourceSectionFilterTest.java
Trying to solve this problem:
https://travis-ci.org/graalvm/graal-core/jobs/109844273
I could not solve it with:
@RunWith(SeparateClassloaderTestRunner.Theories.class)
Its the reason I cannot integrate:
https://github.com/graalvm/graal-core/pull/39
> Temporary fix for SourceSectionFilterTest execution for running inside graal classloaders

- mx.truffle/suite.py
- truffle/com.oracle.truffle.api.dsl.test/src/com/oracle/truffle/api/dsl/test/CodeFormatTest.java
- truffle/com.oracle.truffle.api.dsl.test/src/com/oracle/truffle/api/dsl/test/ExecuteGroupingTest.java
- truffle/com.oracle.truffle.api.dsl.test/src/com/oracle/truffle/api/dsl/test/MergeSpecializationsTest.java
- truffle/com.oracle.truffle.api.dsl.test/src/com/oracle/truffle/api/dsl/test/SourceSectionTest.java
- truffle/com.oracle.truffle.api.dsl.test/src/com/oracle/truffle/api/dsl/test/SpecializationFallthroughTest.java
- truffle/com.oracle.truffle.api.dsl.test/src/com/oracle/truffle/api/dsl/test/examples/ExampleNode.java
- truffle/com.oracle.truffle.api.dsl.test/src/com/oracle/truffle/api/dsl/test/processor/Compile.java
- truffle/com.oracle.truffle.api.instrumentation.test/src/com/oracle/truffle/api/instrumentation/examples/DebuggerExample.java
- truffle/com.oracle.truffle.api.interop.java.test/src/com/oracle/truffle/api/interop/java/test/JavaInteropTest.java
- truffle/com.oracle.truffle.api.interop/src/com/oracle/truffle/api/interop/ForeignAccess.java
- truffle/com.oracle.truffle.api.interop/src/com/oracle/truffle/api/interop/GenericObjectAccessNode.java
- truffle/com.oracle.truffle.api.interop/src/com/oracle/truffle/api/interop/impl/ReadOnlyArrayList.java
- truffle/com.oracle.truffle.object.basic/src/com/oracle/truffle/object/basic/BasicAllocator.java
- truffle/com.oracle.truffle.tck/src/com/oracle/truffle/tck/ComplexNumberAEntry.java
- truffle/com.oracle.truffle.tck/src/com/oracle/truffle/tck/ComplexNumberBEntry.java
- truffle/com.oracle.truffle.tck/src/com/oracle/truffle/tck/ConstantFunction.java
- truffle/com.oracle.truffle.tck/src/com/oracle/truffle/tck/EagerStackTraceDecorator.java
- truffle/com.oracle.truffle.tck/src/com/oracle/truffle/tck/GCAfterTestDecorator.java
- truffle/com.oracle.truffle.tck/src/com/oracle/truffle/tck/MaxMinObject.java
- truffle/com.oracle.truffle.tck/src/com/oracle/truffle/tck/Schema.java
- truffle/com.oracle.truffle.tck/src/com/oracle/truffle/tck/TimingDecorator.java
- truffle/com.oracle.truffle.tck/src/com/oracle/truffle/tck/TruffleJUnitRunListenerDecorator.java
- truffle/com.oracle.truffle.tck/src/com/oracle/truffle/tck/TruffleTextListener.java
- truffle/com.oracle.truffle.tck/src/com/oracle/truffle/tck/TruffleVerboseTextListener.java
- truffle/com.oracle.truffle.tck/src/com/oracle/truffle/tck/impl/TckLanguage.java
- truffle/com.oracle.truffle.tools.debug.shell/src/com/oracle/truffle/tools/debug/shell/client/REPLCommand.java
- truffle/com.oracle.truffle.tools.debug.shell/src/com/oracle/truffle/tools/debug/shell/client/SimpleREPLClient.java
- truffle/com.oracle.truffle.tools.test/src/com/oracle/truffle/tools/test/ToolTestUtil.java
- truffle/com.oracle.truffle.tools/src/com/oracle/truffle/tools/NodeExecCounter.java
This fixes the superfluous keyword issues reported by the latest checkstyle version and updates mx to make sure these rules are enforced in the future.
> Update mx to 5.8.0 and fix checkstyle issues

- .travis.sigtest.sh
- .travis.yml
I'd like the travis to download the most recent API snapshot and compare the signatures in the pull request with it. This way we can find out whether there are (signature) API changes in the PR or not.
> Check API signatures against most recent API snapshot

- truffle/com.oracle.truffle.api.test/src/com/oracle/truffle/api/impl/AccessorTest.java
- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/impl/Accessor.java
Follow up to #65, this time for the Graal Truffle Runtime.
> CallTarget initialization should not throw NPE when not using PolyglotEngine

- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/impl/DefaultCallTarget.java
The class is not part of the API and should also not be extensible.
> Make DefaultCallTarget final. 

- truffle/com.oracle.truffle.api.profiles/src/com/oracle/truffle/api/profiles/ConditionProfile.java
Makes sure the sum of the counters of the true and false branch of a condition profile cannot overflow.
> Fix a possible overflow in the counting condition profile.

- truffle/com.oracle.truffle.api.test/src/com/oracle/truffle/api/StackTraceTest.java
- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/impl/DefaultCallTarget.java
- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/impl/DefaultDirectCallNode.java
- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/impl/DefaultIndirectCallNode.java
- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/impl/DefaultTruffleRuntime.java
- truffle/com.oracle.truffle.sl/src/com/oracle/truffle/sl/builtins/SLStackTraceBuiltin.java
Fix TruffleRuntime#iterateStackTrace was not iterating the topmost frame;
Fixed missing stackframe if CallTarget#call was called without a call node with the default runtime;
Added stack frame tests.
> Fixed missing stackframe if CallTarget#call was called without a call node with the default runtime;

- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/TruffleLanguage.java
Even if you aren't using the old `.instrument` API anymore you can't avoid it because of these three abstract methods in `TruffleLanguage`. This PR makes them concrete and just throws `UnsupportedOperationException` if they're used, which they won't be if you aren't using the API.
> Make old instrument API abstract methods in RubyLanguage concrete

- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/TruffleRuntime.java
- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/nodes/LoopNode.java
- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/nodes/RepeatingNode.java
Long overdue documentation for loop nodes. They were also still marked as experimental, but they are used by most Truffle languages now.
> Add loop node documentation. Make loop nodes a non-experimental feature.

- mx.truffle/mx_truffle.py
- mx.truffle/suite.py
Turning on the `@since` tag check introduced in https://github.com/graalvm/mx/pull/62
By default generating the *unified* javadoc as that is what we want other contributors to check and it is hard to teach all of them that the most important version of Truffle javadoc requires some argument.
> mx javadoc to verify @since tags

- truffle/com.oracle.truffle.api.test/src/com/oracle/truffle/api/StackTraceTest.java
- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/frame/FrameInstance.java
- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/impl/DefaultCallTarget.java
- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/impl/DefaultTruffleRuntime.java
@chrisseaton  please verify that the behavior is now fixed in ruby.
> Restore old behavior in FrameInstance#getCallNode()

- truffle/com.oracle.truffle.api.test/src/com/oracle/truffle/api/LoopNodeTest.java
- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/LoopCountReceiver.java
- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/impl/Accessor.java
- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/nodes/LoopNode.java
- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/nodes/Node.java
- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/nodes/RootNode.java
Two improvements:
* Deprecated LoopCountReceiver that was never intended to be visible to guest languages and use the accessor pattern to call into the runtime instead. Tried to implement it in a compatible way, please verify.
* Move reportLoopCount from RootNode to Node to make the context(Node) of the reported loop count visible  to the Truffle runtime implementation. This is important to do a better OSR decision in the Graal runtime. Should be a compatible change.
> Make loop counts reportable on Nodes instead of RootNodes; 

- .travis.yml
- mx.truffle/mx_truffle.py
This adds a new command `mx testdownstream` and runs that on Travis as an allowed-failure (it doesn't fail the overall commit if it fails, but you still see the result). Only JRuby so far, and runs 64k of JRuby's fastest tests so it only takes a couple of minutes.
This allows you to see if your changes are immediately compatible with JRuby. For example it would have caught the problems with the `iterateFrames` changes.
Potential problems are if the JRuby build is broken anyway (it very rarely is, but sometimes), or if people ignore it because it's allowed-failure.
@mickjordan am I using mx correctly here?
> Test downstream users (JRuby to start with) of Truffle

- truffle/com.oracle.truffle.api.instrumentation/src/com/oracle/truffle/api/instrumentation/InstrumentationHandler.java
- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/impl/DefaultCallTarget.java
* Only publish the DefaultCallTarget as initialized when it is.
* Only publish the InstrumentationHandler as initialized when it is.
* `intialized` needs to be volatile or the store to it might move above the actual initialization (compiler or CPU reordering).
> Fix double-checked locking patterns

- truffle/com.oracle.truffle.api.debug/src/com/oracle/truffle/api/debug/Debugger.java
- truffle/com.oracle.truffle.sl.tools/src/com/oracle/truffle/sl/tools/debug/SLREPL.java
- truffle/com.oracle.truffle.tools.debug.shell/src/com/oracle/truffle/tools/debug/shell/server/InstrumentationUtils.java
Remove an ad hoc mechanism for hiding selected frames in stack tracing that also contained an NPE vulnerability (which @mickjordan reported hitting in FastR).
> Debugger NPE patch

- truffle/com.oracle.truffle.api.instrumentation.test/src/com/oracle/truffle/api/instrumentation/SourceSectionFilterTest.java
- truffle/com.oracle.truffle.api.instrumentation/src/com/oracle/truffle/api/instrumentation/InstrumentationHandler.java
- truffle/com.oracle.truffle.api.instrumentation/src/com/oracle/truffle/api/instrumentation/SourceSectionFilter.java
This should address https://github.com/graalvm/truffle/issues/80 with rootSourceSectionEquals.
Additionally I've added indexIn, indexNotIn, lineIn and lineNotIn with a set of ranges to allow arbitrary index and line based checks. 
@mickjordan please comment if this fits your needs.
> Source section filter extension

- truffle/com.oracle.truffle.api.interop.java.test/src/com/oracle/truffle/api/interop/java/test/JavaInteropSpeedTest.java
The test tries to find performance regressions in the java interop implementation by comparing invocation time which is highly system dependent and fails regularly on different machines. Doing this in a unit test is sub-optimal. It should be converted into a microbenchmark.
> Ignore JavaInteropSpeedTest.

- truffle/com.oracle.truffle.api.test/src/com/oracle/truffle/api/instrument/InstrumentationTest.java
I needed to disable the instrumentation tags as they were failing on jdk9 for unknown reasons.
This is the job that failed: https://travis-ci.org/graalvm/graal-core/jobs/115116308
@mlvdv We decided to disable this as a new Truffle version is desperately needed in graal-core. Do you have an idea what could be the cause?
> Temporarily disable instrumentation tests as they seem to fail on JDK9.

- truffle/com.oracle.truffle.api.debug/src/com/oracle/truffle/api/debug/Debugger.java
- truffle/com.oracle.truffle.api.debug/src/com/oracle/truffle/api/debug/ExecutionEvent.java
- truffle/com.oracle.truffle.api.vm/src/com/oracle/truffle/api/vm/PolyglotEngine.java
- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/impl/Accessor.java
- truffle/com.oracle.truffle.sl.test/src/com/oracle/truffle/sl/test/SLDebugTest.java
Returns the situation with respect to `ExecutionEvent` to 0.11 state - e.g. `ExecutionEvent` is always delivered and its `getDebugger` method returns initialized debugger.
Martin @Entlicher, please verify if the change works for your debugger.
> Execution event always

- truffle/com.oracle.truffle.tck/src/com/oracle/truffle/tck/TruffleTCK.java
@lukasstadler pointed out that the byte addition could in fact overflow in some languages. Narrowing the range to prevent that.
@lukasstadler also suggested to remove the failure message and keep just the formula.
> Byte overflow & failure message simplification 

- truffle/com.oracle.truffle.api.object.dsl.test/src/com/oracle/truffle/api/object/dsl/test/ObjectTypePublicTest.java
- truffle/com.oracle.truffle.api.object.dsl.test/src/com/oracle/truffle/api/object/dsl/test/alternate_package/ObjectTypePublicTest.java
- truffle/com.oracle.truffle.object.dsl.processor/src/com/oracle/truffle/object/dsl/processor/LayoutGenerator.java
The `ObjectType` subclass we generate as part of the OM DSL is currently hidden as an implementation detail. But now I've found out that it would be useful to have it for the foreign access DSL, which needs it in the required `receiverType` parameter of the  `AcceptMessage` annotation.
This doesn't change any signatures but I guess it counts as an API change on the as-yet unreleased OM-DSL as the generated code is different, but backwards compatible.
> OM-DSL: make the generated ObjectType public

- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/nodes/RootNode.java
The ExecutionContext does not contain getLanguageShortName() method, therefore it's reference should be removed from Javadoc.
> Update Javadoc of getExecutionContext()

- truffle/com.oracle.truffle.api.dsl.test/src/com/oracle/truffle/api/dsl/test/utilities/InstrumentationTestMode.java
- truffle/com.oracle.truffle.api.interop.java.test/src/com/oracle/truffle/api/interop/java/test/InstrumentationTestMode.java
- truffle/com.oracle.truffle.api.interop.java.test/src/com/oracle/truffle/api/interop/java/test/JavaFunctionTest.java
- truffle/com.oracle.truffle.api.test/src/com/oracle/truffle/api/impl/AccessorTest.java
- truffle/com.oracle.truffle.api.test/src/com/oracle/truffle/api/instrument/InstrumentationTest.java
- truffle/com.oracle.truffle.api.test/src/com/oracle/truffle/api/utilities/InstrumentationTestMode.java
- truffle/com.oracle.truffle.api.test/src/com/oracle/truffle/api/vm/EngineSingleThreadedTest.java
- truffle/com.oracle.truffle.api.test/src/com/oracle/truffle/api/vm/EngineTest.java
- truffle/com.oracle.truffle.api.test/src/com/oracle/truffle/api/vm/GlobalSymbolTest.java
- truffle/com.oracle.truffle.api.test/src/com/oracle/truffle/api/vm/ImplicitExplicitExportTest.java
- truffle/com.oracle.truffle.api.test/src/com/oracle/truffle/api/vm/InitializationTest.java
- truffle/com.oracle.truffle.api.test/src/com/oracle/truffle/api/vm/IsMimeTypeSupportedTest.java
- truffle/com.oracle.truffle.api.test/src/com/oracle/truffle/api/vm/ToStringTest.java
- truffle/com.oracle.truffle.api.test/src/com/oracle/truffle/api/vm/ValueTest.java
- truffle/com.oracle.truffle.sl.test/src/com/oracle/truffle/sl/test/ParsingCachedTest.java
- truffle/com.oracle.truffle.sl.test/src/com/oracle/truffle/sl/test/SLDebugTest.java
- truffle/com.oracle.truffle.sl.test/src/com/oracle/truffle/sl/test/SLJavaInteropTest.java
- truffle/com.oracle.truffle.sl.test/src/com/oracle/truffle/sl/test/SLPolyglotTest.java
- truffle/com.oracle.truffle.sl.test/src/com/oracle/truffle/sl/test/SLTckTest.java
- truffle/com.oracle.truffle.sl.test/src/com/oracle/truffle/sl/test/SLTestRunner.java
- truffle/com.oracle.truffle.sl.test/src/com/oracle/truffle/sl/test/ToStringOfEvalTest.java
- truffle/com.oracle.truffle.sl.test/src/com/oracle/truffle/sl/test/instrument/InstrumentationTestMode.java
- truffle/com.oracle.truffle.sl.test/src/com/oracle/truffle/sl/test/instrument/SLInstrumentTestRunner.java
- truffle/com.oracle.truffle.sl/src/com/oracle/truffle/sl/SLLanguage.java
- truffle/com.oracle.truffle.tck/src/com/oracle/truffle/tck/TruffleTCK.java
Consistently dispose PolyglotEngine after being used in tests. Give TruffleTCK and its implementor a chance to co-operate on construction of new PolyglotEngine.
Yesterday Andreas @Woess noted that the change proposed in #85 is huge. I took a look and yes, it seems huge as it contains a lot of fixes in tests. These fixes are however independent of the #85 change - they just consistently dispose `PolyglotEngine` after it has been used. I believe this kind of robustness improving changes can go in without any delay. Thus I am starting this pull request.
In addition to that there is one change in `TruffleTCK` to allow the TCK and the tested language to co-operate on creation of a `PolyglotEngine` - such factory is needed not only for #85, but also to test import of symbols - the TCK needs to …
> Consistently dispose PolyglotEngine after being used in tests

- truffle/com.oracle.truffle.api.debug/src/com/oracle/truffle/api/debug/BreakpointFactory.java
- truffle/com.oracle.truffle.api.instrumentation.test/src/com/oracle/truffle/api/instrumentation/SourceSectionFilterTest.java
- truffle/com.oracle.truffle.api.instrumentation/src/com/oracle/truffle/api/instrumentation/SourceSectionFilter.java
This makes sense for when there are ambiguous source section definitions like a breakpoint in an if condition.
Also changed the debugger to use the new lineStartsIn.
> Add lineStartsIn and lineEndsIn to source section filters.

- README.md
`mx` repository is on github + the Maven coordinates are different now - the groupId is `com.oracle.truffle`.
> Using more recent references in the README file

- truffle/com.oracle.truffle.api.vm/src/com/oracle/truffle/api/vm/PolyglotEngine.java
- truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/TruffleLanguage.java
A TruffleLanguage should provide a language-agnostic interface to be able to be usable in multi-language environments. Language-specific front-ends or launchers, for instance, emulating existing implementations, should be realized externally to the PolyglotEngine.
This change fixes also minor issues in existing comments.
The tests on Travis still fail, because it seems to use the Eclipse 4.5 formatter.
Locally, it passes with using Eclipse 4.4 and making sure `ECLIPSE_EXE` is set.
Recreated the PR. Seems like force-push to a branch after the original PR is closed is problematic.
> Document guideline to design TruffleLanguage with language-agnostic initialization.

- .travis.yml
This also updates from 4.5.1 to 4.5.2
> Fix ecj and eclipse jdk URL for travis

- truffle/com.oracle.truffle.dsl.processor/src/com/oracle/truffle/dsl/processor/InteropProcessor.java
- truffle/com.oracle.truffle.dsl.processor/src/com/oracle/truffle/dsl/processor/interop/ExecuteGenerator.java
- truffle/com.oracle.truffle.dsl.processor/src/com/oracle/truffle/dsl/processor/interop/ForeignAccessFactoryGenerator.java
- truffle/com.oracle.truffle.dsl.processor/src/com/oracle/truffle/dsl/processor/interop/GenericGenerator.java
- truffle/com.oracle.truffle.dsl.processor/src/com/oracle/truffle/dsl/processor/interop/LanguageCheckGenerator.java
- truffle/com.oracle.truffle.dsl.processor/src/com/oracle/truffle/dsl/processor/interop/ReadGenerator.java
- truffle/com.oracle.truffle.dsl.processor/src/com/oracle/truffle/dsl/processor/interop/UnaryGenerator.java
- truffle/com.oracle.truffle.dsl.processor/src/com/oracle/truffle/dsl/processor/interop/WriteGenerator.java
Changes the generated code to use “static final” as it is the recommended order by JLS.
Also fix two minor whitespace issues.
> Fix checkstyle issues in generated code

- .travis.yml
The downstream tests do not seem to be maintained, and are likely not very helpful.
To avoid extra maintenance overhead, we might want to remove it from the Travis tests.
/cc @eregon @chrisseaton
> Remove JRuby downstream test from Travis checks

- compiler/src/org.graalvm.compiler.phases.common/src/org/graalvm/compiler/phases/common/AddressLoweringByUsePhase.java
The issue:
The current AArhc64 address lowering assumes each use of an address employs the same type for the loaded datum. In rare cases this assumption is invalid because an address is shared by two loads with different types. In particular, this manifests when loading an int from a DirectByteBuffer at an odd address. The problem can be seen when running netbeans, where reads of mapped file data occasionally fail when an integer datum is located at an odd offset.
Diagnosis:
The generated code for Unsafe.getIntUnaligned
```
public final int getIntUnaligned(Object o, long offset) {
if ((offset & 3) == 0) {
return getInt(o, offset);
} else if ((offset & 1) == 0) {
return makeInt(getShort(o, offset),
getShort(o, offset + 2)); // base + const offset 2
} else {
return makeInt(getByte(o, …
```
> create different lowerings for different use types

- compiler/src/org.graalvm.compiler.replacements.aarch64/src/org/graalvm/compiler/replacements/aarch64/AArch64IntegerArithmeticSnippets.java
The Problem:
This patch fixes the 12 CountedLoop unit tests that currently fail with an assert during code generation.
Diagnosis:
On AArch64 DIv/Rem nodes are replaced by a snippet which includes AArch64-specific SafeDiv/Rem nodes. The latter are cloned from the original DIv/Rem nodes with a null beforeState. Unfortunately, they inherit their generate method from the generic Div/Rem nodes. The inherited methods call gen.state(this) to retrieve the beforeState and construct a FrameState passed in the call to the generators emitDiv/Rem method. This blows up because the beforeState is null.
Fix:
The AArch64 generator's emitDiv/Rem methods ignore the state argument because they will never encounter a div by zero. So, there is no need to compute a frame state. The fix works by overriding the …
> avoid asserts over missing before state when generating safe Div/Rem nodes on AArch64

- compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64Assembler.java
- compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64MacroAssembler.java
- compiler/src/org.graalvm.compiler.truffle.hotspot.aarch64/src/org/graalvm/compiler/truffle/hotspot/aarch64/AArch64OptimizedCallTargetInstumentationFactory.java
- compiler/src/org.graalvm.compiler.truffle/src/org/graalvm/compiler/truffle/TruffleCompiler.java
This patch fixes a problem introduced into AArch64 by a previous truffle compiler fix.
Testing:
The patch fixes all the unit tests which were failing because of a broken tbz implementation.
n.b. 12 CountedLoop tests are still failing but that is due to an unrelated error to do with missing frame state for a SafeSignedDiv node
> Aarch64 tbz patch

- compiler/src/org.graalvm.compiler.core.test/src/org/graalvm/compiler/core/test/ByteBufferTest.java
- compiler/src/org.graalvm.compiler.core.test/src/org/graalvm/compiler/core/test/DirectByteBufferTest.java
As promised here is a unit test to check writes to direct byte buffers, It passes on x86 and AArch64 with the latest head.
n.b. I reverted the AArch64 address lowering code to revert the fix that updated usages one by one and, as expected, the unaligned int writes failed because the second byte of the int was being written at offset 1 rather than offset 2. So, this test would have caught the error in the original commit.
> test writes to direct byte buffers

- .travis.yml
- compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64Assembler.java
- compiler/src/org.graalvm.compiler.hotspot.aarch64/src/org/graalvm/compiler/hotspot/aarch64/AArch64HotSpotLIRGenerator.java
- compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/JVMCIVersionCheck.java
- compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64PrefetchOp.java
- compiler/src/org.graalvm.compiler.phases.common/src/org/graalvm/compiler/phases/common/AddressLoweringByUsePhase.java
This patch implements prefetch for AArch64.
Currently, on AArch64 a PrefetchAllocateNode inserted into generic code results in a redundant load constant followed by a nop. This patch ensures that a prefetch (prfm) instruction is generated with a suitable prefetch mode and displacement mode address.
Note that the AArch64 port does not currently set a suitable value for PrefetchAllocateInstr in it's implementation of class VM_Version. The default value of 0 (PLDL1KEEP) would not be a disaster but is not really the best choice. So, this patch follows the current AArch64 C2 compiler in enforcing use of prefetch mode PSTL1KEEP when lowering a PrefetchAllocateNode, ignoring the config setting derived from PrefetchAllocateInstr.
> Implement prefetch for AArch64

- compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64MacroAssembler.java
What?
This patch changes the address generation plan for AArch64 to use scaled displacement addressing in preference to unscaled displacement addressing. It's only a cosmetic change since neither is better than the other in terms of how the code executes, yet it seems cosmetics do have a point.
Why?
Unscaled addressing generates an instruction ldur xr, [xm,#nnn] where nnn is a 9-bit signed unscaled displacement (offsets from -2^9 inclusive up to 2^9 exclusive). Scaled addressing generates an instruction ldr xr, [xm, #nnn] where nnn is a 12 bit unsigned scaled displacement (i.e. byte offsets up to 2^12, qword aligned offsets up to 2^15). For any positive nnn value fitting into 8 bits there is no difference between the two instructions except for the presence of ldur/ldr. Outside that range …
> use scaled addressing in preference to unscaled where possible

- .travis.yml
- compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/JVMCIVersionCheck.java
- compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64Move.java
- compiler/src/org.graalvm.compiler.lir.jtt/src/org/graalvm/compiler/lir/jtt/StackStoreLoadTest.java
This patch fixes the problem reported here: https://github.com/graalvm/graal/issues/236
The patch includes a unit test which manifest the problem and confirms the fix as described in the issyue mentioned above.
> fix AArch64 stack saves and copies

- .travis.yml
- compiler/src/org.graalvm.compiler.phases.common/src/org/graalvm/compiler/phases/common/UseTrappingNullChecksPhase.java
The Problem:
UseTrappingNullChecksPhase checks to see whether a read from an object field is guarded by an IfNode/IsNullNode and, where possible, converts the read to use an implicit null check and splices the If out of the graph. The check involves identifying whether the oop address tested by the IsNullNode equals the oop base address used by the ReadNode. When using compressed oops this can lead to failures on architectures other than x86.
If the oop value in question is a narrow oop then the IsNullNode is passed a CompressionNode. It dereferences this to store the underlying NarrowOop value as the target value to be tested for null. If this same CompressionNode is used as the base or index for the ReadNode then the comparison will not succeed unless the address lowering can optimize …
> Enable trapping null checks for architectures whcih cannot fold uncompress into address

- .travis.yml
- compiler/mx.compiler/suite.py
- compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64ArithmeticLIRGenerator.java
- compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64NodeMatchRules.java
- compiler/src/org.graalvm.compiler.core.test/src/org/graalvm/compiler/core/test/ZeroSignExtendTest.java
- compiler/src/org.graalvm.compiler.hotspot.aarch64/src/org/graalvm/compiler/hotspot/aarch64/AArch64HotSpotSuitesProvider.java
- compiler/src/org.graalvm.compiler.replacements.aarch64/src/org/graalvm/compiler/replacements/aarch64/AArch64ReadNode.java
- compiler/src/org.graalvm.compiler.replacements.aarch64/src/org/graalvm/compiler/replacements/aarch64/AArch64ReadReplacementPhase.java
This patch fixes the problem reported here: https://github.com/graalvm/graal/issues/238
When running on AArch64 it adds a phase to the LowTier  just before the Scheduling phase. This new phase replaces pairs of Read + Sign/ZeroExtend nodes with an AArch64ReadNode that combines the read and extend operation into one.
The patch includes a unit test (ZeroSignExtendTest) which exercises the node replacement for the newly added phase. Generated code for the test snippets before and after the patch shows that the patched version elides redundant stxw or andw instructions that the previous match rules could not eliminate.
Atached assembler dumps for the before and after code show the improvement.
[extend-before.txt](https://github.com/graalvm/graal/files/1142318/extend-before.txt) …
> AArch64 Zero/SignExtend elision is inadequate

- compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/calc/IntegerDivRemNode.java
(This is broken as-is due to breaking CountedLoopTest)
> Divide can deopt if y is -1

- compiler/src/org.graalvm.compiler.hotspot.aarch64/src/org/graalvm/compiler/hotspot/aarch64/AArch64HotSpotForeignCallsProvider.java
- compiler/src/org.graalvm.compiler.hotspot.amd64/src/org/graalvm/compiler/hotspot/amd64/AMD64HotSpotForeignCallsProvider.java
- compiler/src/org.graalvm.compiler.hotspot.sparc/src/org/graalvm/compiler/hotspot/sparc/SPARCHotSpotForeignCallsProvider.java
- compiler/src/org.graalvm.compiler.hotspot.test/src/org/graalvm/compiler/hotspot/test/CRC32CSubstitutionsTest.java
- compiler/src/org.graalvm.compiler.hotspot.test/src/org/graalvm/compiler/hotspot/test/CheckGraalIntrinsics.java
- compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/GraalHotSpotVMConfig.java
- compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/meta/HotSpotGraphBuilderPlugins.java
- compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/replacements/CRC32CSubstitutions.java
CRC32C is available since Java 9 and there are StubRoutines::updateBytesCRC32C() stubs for x86_64, aarch64 and sparcv9.
GraalHotSpotVMConfig got useCRC32CIntrinsics, it reads the flag for 9 and it is always false for 8.
New CRC32CSubstitutions class provides substitutions to update() methdods using the stub. 3 foreign calls providers were updated to use it and the substitutions are registered in HotSpotGraphBuilderPlugins.
New CRC32CSubstitutionsTest compares checksums for arrays with zero and non-zero offset and for direct and wrapped ByteBuffer. It passes in my environment.
On the whole CRC32C support is similar to CRC32 taking into account that the class is not present in Java 8.
Some x86 performance results on JDK9.
benchmark: …
> Implement CRC32C substitutions

- compiler/src/org.graalvm.compiler.replacements/src/org/graalvm/compiler/replacements/classfile/ClassfileConstant.java
- compiler/src/org.graalvm.compiler.replacements/src/org/graalvm/compiler/replacements/classfile/ClassfileConstantPool.java
Small addition to the patch that bumps supported classfile version to JDK11(55). Skip new CONSTANT_Dynamic tag.
I signed OCA as:
Dmitry Samersov - OpenJDK - dsamersoff
> Skip jdk11 CONSTANT_Dynamic tag

- truffle/src/com.oracle.truffle.nfi.native/Makefile
- truffle/src/com.oracle.truffle.nfi.native/include/native.h
Warning! These changes has an impact to the process.
1. It depends to mx changes (https://github.com/graalvm/mx/pull/142).
2. It's not clear to me how we should handle jdk8 that stay with javah
> Replace javah with javac

- truffle/src/com.oracle.truffle.nfi.native/Makefile
Problem originally reported here: https://github.com/graalvm/sulong/issues/832
> Fix build problem when JAVA_HOME contains spaces.

- compiler/src/org.graalvm.compiler.asm.amd64/src/org/graalvm/compiler/asm/amd64/AMD64Assembler.java
- compiler/src/org.graalvm.compiler.core.amd64/src/org/graalvm/compiler/core/amd64/AMD64LIRGenerator.java
- compiler/src/org.graalvm.compiler.lir.amd64/src/org/graalvm/compiler/lir/amd64/AMD64ArrayCompareToOp.java
- compiler/src/org.graalvm.compiler.lir/src/org/graalvm/compiler/lir/gen/LIRGeneratorTool.java
- compiler/src/org.graalvm.compiler.replacements.amd64/src/org/graalvm/compiler/replacements/amd64/AMD64GraphBuilderPlugins.java
- compiler/src/org.graalvm.compiler.replacements.amd64/src/org/graalvm/compiler/replacements/amd64/AMD64StringLatin1Substitutions.java
- compiler/src/org.graalvm.compiler.replacements.amd64/src/org/graalvm/compiler/replacements/amd64/AMD64StringUTF16Substitutions.java
- compiler/src/org.graalvm.compiler.replacements.test/src/org/graalvm/compiler/replacements/test/StringCompareToTest.java
- compiler/src/org.graalvm.compiler.replacements/src/org/graalvm/compiler/replacements/nodes/ArrayCompareToNode.java
> String.compareTo intrinsic for amd64

- compiler/src/org.graalvm.compiler.hotspot.aarch64/src/org/graalvm/compiler/hotspot/aarch64/AArch64HotSpotBackend.java
- compiler/src/org.graalvm.compiler.hotspot.aarch64/src/org/graalvm/compiler/hotspot/aarch64/AArch64HotSpotDeoptimizeOp.java
- compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64Call.java
This fixes a few overflows discovered when testing with a large (i.e. more than 128Mb) code buffer.
> AArch64: fix branch target overflows and return addresses.

- compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64Assembler.java
Adding a function for determining the support for AArch64 CPUFeatures. This is a small function to prepare the way for implementing certain intrinsics which require atomic instructions only available on AArch64 architectures that have implemented certain 8.X extensions.
This function is modeled after the same function in AMD64.
> Add AArch64 support() function for determining CPUFeature support.

- compiler/src/org.graalvm.compiler.hotspot.aarch64/src/org/graalvm/compiler/hotspot/aarch64/AArch64HotSpotSuitesProvider.java
- compiler/src/org.graalvm.compiler.replacements.aarch64/src/org/graalvm/compiler/replacements/aarch64/AArch64ReadReplacementPhase.java
This change is about to fix the NullPointerException in the compiler when running with the economic configuration. `mx gate -t BootstrapWithSystemAssertionsEconomy`.
I guess  the intention was to put the `AArch64ReadReplacementPhase` right before the `SchedulePhase` by adding it after the secondlast phase. Unfortunately in the economic configuration the secondlast phase (`PropagateDeoptimizeProbabilityPhase`) is not there.
@adinn please review this change and confirm if my assumption was right.
> AArch64: Put AArch64ReadReplacementPhase right before SchedulePhase.

- compiler/src/org.graalvm.compiler.asm.aarch64.test/src/org/graalvm/compiler/asm/aarch64/test/TestProtectedAssembler.java
- compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64Assembler.java
- compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64LIRGenerator.java
- compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64ArrayCompareToOp.java
- compiler/src/org.graalvm.compiler.replacements.aarch64/src/org/graalvm/compiler/replacements/aarch64/AArch64GraphBuilderPlugins.java
- compiler/src/org.graalvm.compiler.replacements.aarch64/src/org/graalvm/compiler/replacements/aarch64/AArch64StringLatin1Substitutions.java
- compiler/src/org.graalvm.compiler.replacements.aarch64/src/org/graalvm/compiler/replacements/aarch64/AArch64StringUTF16Substitutions.java
- compiler/src/org.graalvm.compiler.replacements.test/src/org/graalvm/compiler/replacements/test/StringCompareToTest.java
String compareTo intrinsic for  AArch64
> String.compareTo for AArch64

- compiler/mx.compiler/suite.py
- compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64Assembler.java
- compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64LIRGenerator.java
- compiler/src/org.graalvm.compiler.lir.aarch64.jdk11/src/org/graalvm/compiler/lir/aarch64/AArch64AtomicMove.java
- compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64AtomicMove.java
- compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64Move.java
This adds the basic support for the CAS instruction in AArch64. It supports the various acquire/release variants, though it appears that only the acquire/release variant would currently be used. It also allows the CASAL instruction to be used for the lowering of a CompareAndSwapOp if the corresponding support is there in the hardware. 
This takes the same approach as HotSpot in dealing with the UseLSE flag. That is, if either the flag is thrown OR the hardware support is there, the CAS instruction will be used.
> Add AArch64 support for the CAS instruction

- compiler/src/org.graalvm.compiler.debug/src/org/graalvm/compiler/debug/PathUtilities.java
AUFS is the default file system for Docker container on some Linux
distribution. And the maximum filename length on AUFS is 242.
> Update maximum file name length to support AUFS

- compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64Assembler.java
This fixes a sparse and improper comment for the CAS instruction I added earlier.
> Add proper comment to AArch64 CAS instruction

- compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64LIRGenerator.java
- compiler/src/org.graalvm.compiler.lir.aarch64.jdk11/src/org/graalvm/compiler/lir/aarch64/AArch64AtomicMove.java
- compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64AtomicMove.java
- compiler/src/org.graalvm.compiler.replacements.aarch64/src/org/graalvm/compiler/replacements/aarch64/AArch64GraphBuilderPlugins.java
This is an implementation of the getAndAddInt() and getAndAddLong() intrinsics for AArch64. This should support both AArch64 systems with 8.1 extensions and those without. It uses acquire/release semantics as I don't currently see a way to distinguish if we need them or if that information can be passed in. The registration of the unsafe plugin code was taken from AMD and therefore copies that structure, even though this patch doesn't currently support Objects. In the future, additions to the registration code could, and therefore that part of the code which includes Java Objects in an enumeration was left in, even though the code immediately looks for that and passes over it.
> Add support for getAndAddInt() and getAndAddLong() intrinsics to AArch64

- substratevm/REFLECTION.md
Should be `true` (boolean) not `"true"` string in two places.
I got compile errors with Graal 1.0.0 rc-1 when using `"true"`.
> Fix error in JSON

- compiler/mx.compiler/mx_graal_benchmark.py
- compiler/mx.compiler/suite.py
This PR adds a new benchmark `dacapo-d3s` that uses a modified version of the DaCapo benchmark that can query hardware performance counters (Linux only).
Hardware counters are accessed via [PAPI](http://icl.cs.utk.edu/papi/) through a simple C agent. The agent is compiled automatically when running the suite for the first time.
The [C agent is available](https://github.com/D-iii-S/java-ubench-agent) at GitHub, the JAR with the modified DaCapo is hosted by [Department of Distributed and Dependable Systems at Charles University](http://d3s.mff.cuni.cz/software/benchmarking/).
As an extra feature, the results can be also stored in a CSV file.
Example run to collect total number of instructions and L1 cache misses with results stored in `avrora.csv`:
```shell
mx --primary-suite compiler \ …
```
> Add modified DaCapo benchmark collecting hardware counters

- compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64MacroAssembler.java
- compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64LIRGenerator.java
- compiler/src/org.graalvm.compiler.lir.aarch64.jdk11/src/org/graalvm/compiler/lir/aarch64/AArch64LIRFlagsVersioned.java
- compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64AtomicMove.java
- compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64LIRFlagsVersioned.java
This adds support for using immediate values in the add instruction within the getAndAddInt() intrinsic for AArch64.
> Allow immediates to be used in getAndAddInt for AArch64

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/SunMiscSubstitutions.java
Since JarFile is back, we can now use JarURLConnection again.
> Reinstate JarURLConnection

- substratevm/REFLECTION.md
The JSON snippet in `substratevm/REFLECTION.md` is not valid, let's fix it
> Fix JSON snippet in documentation

- README.md
As part of [[GR-11502] Relicense Truffle and the SDK to UPL](/oracle/graal/commit/0f8c00b5241ec89154a79ac6e7627dbfbaf4dce6).
> Update README with license move from GPL to UPL

- compiler/src/org.graalvm.compiler.hotspot.test/src/org/graalvm/compiler/hotspot/test/BigIntegerIntrinsicsTest.java
- compiler/src/org.graalvm.micro.benchmarks/src/micro/benchmarks/BigIntegerBenchmark.java
Added simplistic test cases and benchmark for BigInteger intrinsics.
Used in order to test JDK change.
> JDK-8191339: [JVMCI] BigInteger compiler intrinsics on Graal.

- compiler/src/org.graalvm.compiler.core.test/src/org/graalvm/compiler/core/test/ea/UnsafeCompareAndSwapVirtualizationTest.java
- compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/java/UnsafeCompareAndSwapNode.java
Compare and swap calls using `Unsafe` are currently always lowered to an atomic operation. That's unnecessary when the CAS mutates a field of an instance that is virtual. It introduces some performance overhead and prevents other optimizations.
Let's take this JMH benchmark class as an example:
```java
public class VirtualCASBench {
public static final long valueOffset = UnsafeUtil.fieldOffset(TestClass.class, "value");
private static class TestClass {
public volatile int value;
public TestClass(int value) {
this.value = value;
}
}
@Benchmark
public boolean testUnsafe() {
TestClass t = new TestClass(0);
return UnsafeUtil.unsafe.compareAndSwapInt(t, valueOffset, 0, 1);
}
@Benchmark
public boolean testIfElse() {
TestClass t = new TestClass(0);
synchronized (t) {
if (t.value != 0)
return …
```
> virtualize unsafe compare and swap calls

- compiler/src/org.graalvm.compiler.asm.amd64/src/org/graalvm/compiler/asm/amd64/AMD64Assembler.java
- compiler/src/org.graalvm.compiler.core.amd64/src/org/graalvm/compiler/core/amd64/AMD64ArithmeticLIRGenerator.java
- compiler/src/org.graalvm.compiler.core.amd64/src/org/graalvm/compiler/core/amd64/AMD64NodeMatchRules.java
- compiler/src/org.graalvm.compiler.core/src/org/graalvm/compiler/core/gen/NodeMatchRules.java
- compiler/src/org.graalvm.compiler.hotspot.amd64.test/src/org/graalvm/compiler/hotspot/amd64/test/BmiAndn.java
- compiler/src/org.graalvm.compiler.hotspot.amd64.test/src/org/graalvm/compiler/hotspot/amd64/test/BmiBlsi.java
- compiler/src/org.graalvm.compiler.hotspot.amd64.test/src/org/graalvm/compiler/hotspot/amd64/test/BmiBlsmsk.java
- compiler/src/org.graalvm.compiler.hotspot.amd64.test/src/org/graalvm/compiler/hotspot/amd64/test/BmiBlsr.java
- compiler/src/org.graalvm.compiler.hotspot.amd64.test/src/org/graalvm/compiler/hotspot/amd64/test/BmiCompilerTest.java
- compiler/src/org.graalvm.compiler.lir.amd64/src/org/graalvm/compiler/lir/amd64/AMD64ArithmeticLIRGeneratorTool.java
This pull request adds support for the andn, blsi, blsr and blsmsk pattern matchings for amd64 architectures.
> [JDK-8198574] Add support for andn, blsi, blsr and blsmsk x86 instructions

- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/ClassInitializationFeature.java
I noticed some misspellings of initialization and reinitialized while debugging.
> Fix typos in class initialization messages

- compiler/mx.compiler/mx_compiler.py
When running ~`mx makegraaljdk build`~ `mx gate` while using JDK 11 in the compiler suite I was seeing an error about the file `/lib/jdwp.dll` not existing. That is indeed the case, because the file is under `/bin` on windows.
This PR adds a function to return the right lib folder based on the platform, and uses that instead of the hardcoded `lib` directory.
> Add function to select the right lib folder

- compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64ArrayCompareToOp.java
- compiler/src/org.graalvm.compiler.replacements.test/src/org/graalvm/compiler/replacements/test/StringCompareToTest.java
- compiler/src/org.graalvm.compiler.replacements.test/src/org/graalvm/compiler/replacements/test/StringSubstitutionTestBase.java
Also fix the StringCompareToTest by adding RemoveNeverExecutedCode
option to test compilation.
And the StringCompareToTest will fail without this patch's modification in CompareTo intrinsics on AArch64.
> Fix AArch64 CompareTo String intrinsic.

- sulong/projects/com.oracle.truffle.llvm.runtime/src/com/oracle/truffle/llvm/runtime/LLVMLanguage.java
- sulong/projects/com.oracle.truffle.llvm.test/src/com/oracle/truffle/llvm/test/ParserTortureSuite.java
- sulong/projects/com.oracle.truffle.llvm.test/src/com/oracle/truffle/llvm/test/debug/LLVMDebugTestBase.java
- sulong/projects/com.oracle.truffle.llvm.test/src/com/oracle/truffle/llvm/test/util/ProcessUtil.java
- sulong/projects/com.oracle.truffle.llvm/src/com/oracle/truffle/llvm/Sulong.java
This PR capitalizes Sulong's language name to make it more consistent with other Truffle languages (see [TruffleRuby](https://github.com/oracle/truffleruby/blob/13bd0c45ec508e43a67e1f176c20ebe360f5a146/src/main/java/org/truffleruby/RubyLanguage.java#L36) or [Graal.Python](https://github.com/graalvm/graalpython/blob/master/graalpython/com.oracle.graal.python/src/com/oracle/graal/python/PythonLanguage.java#L99)).
> Capitalize Sulong's language name

- compiler/src/org.graalvm.compiler.hotspot.test/src/org/graalvm/compiler/hotspot/test/CheckGraalIntrinsics.java
- compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/GraalHotSpotVMConfig.java
- compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/HotSpotBackend.java
- compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/meta/HotSpotGraphBuilderPlugins.java
- compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/meta/HotSpotHostForeignCallsProvider.java
- compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/replacements/ArraysSupportSubstitutions.java
…7161)
From the openjdk bug report:
Currently the vectorizedMismatch intrinsic is in the toBeInvestigated list: 
./share/classes/org.graalvm.compiler.hotspot.test/src/org/graalvm/compiler/hotspot/test/CheckGraalIntrinsics.java 
There is a JMH micro for testing ArraysMismatch: open/test/micro/org/openjdk/bench/java/util/ArraysMismatch.java 
Implementing this in the longest case would be a ~150% speedup.
> jdk.internal.util.ArraysSupport.vectorizedMismatch intrinsic (JDK-8217161)

- substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/JavaNetNetUtil.java
This simple patch fixes problems with hanging socket's operations (oracle#934) in SVM.
> Fix mistypes for RESTARTABLE macros in JavaNetNetUtil

- compiler/src/org.graalvm.compiler.core.aarch64.test/src/org/graalvm/compiler/core/aarch64/test/AArch64MembarOpTest.java
- compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64Move.java
On AArch64 platform, all the memory barriers are implemented as any-to-any barrier which is much heavier than required. 
This patch create a more accurate mapping from barrier defined in Graal compiler to its AArch64 backend implementation.
Change-Id: Id941b019e0894c24403e525889a83f2bd0524211
> Enable different dmb types on aarch64

- substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/darwin/DarwinImageHeapProvider.java
- substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/headers/PosixDirectives.java
- substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/headers/Stat.java
- substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/headers/Unistd.java
- substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/headers/darwin/DarwinVirtualMemory.java
- substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/linux/LinuxImageHeapProvider.java
- substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/linux/ProcFSSupport.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/os/CopyingImageHeapProvider.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/os/OSCommittedMemoryProvider.java
- 1/21/19 - Added Darwin COW support
- 1/21/19 - Dropped commit that changed SpawnIsolates default to false for executables
- 1/23/19 - Updated Linux COW to utilize overlapped anon relocatable section instead of patching, removed UseCOWIsolateHeaps,  removed UseCompressedReferences & spawn isolates usage (will continue discussion around that change separately)
This pull request includes a set of changes to improve the memory usage of native images. I have broken these changes into ~3~ 2 separate commits to make it easier to review, and also make it easier to apply in piecemeal if any are contentious. If preferred, I can break these into separate PRs, just let me know. Also, I am happy to address any other concerns raised. The changes in this PR (justifications further down) are:
1. The …
> Improve memory usage

- compiler/src/org.graalvm.compiler.lir/src/org/graalvm/compiler/lir/hashing/HashFunction.java
@tkrodriguez @dougxc Here's the fix as requested in https://github.com/oracle/graal/pull/895#discussion_r254862466
> Avoid AMD64Kind in HashFunction

- compiler/src/org.graalvm.compiler.core.test/src/org/graalvm/compiler/core/test/IntegerDivRemConstantTest.java
- compiler/src/org.graalvm.compiler.core.test/src/org/graalvm/compiler/core/test/MemoryScheduleTest.java
- compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/calc/IntegerDivRemNode.java
- compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/calc/IntegerMulHighNode.java
- compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/calc/SignedDivNode.java
- compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/calc/SignedRemNode.java
- compiler/src/org.graalvm.compiler.truffle.compiler/src/org/graalvm/compiler/truffle/compiler/substitutions/TruffleGraphBuilderPlugins.java
We want to use some cheaper instructions to implement a division operation, of which
the divisor is a constant but not a power of 2 one, instead of using "div" directly.
The main conversion theory is shown here:
"a/num -> a*(1/num) -> a*(temp_num)/2^n -> a*(temp_num)>>n".
I borrowed the existing algorithm from Hacker's Delight by Henry S. Warren, Jr, and
almost verbatim the codes from it with just translate the C codes to JAVA codes.
Here is two jmh performance results with -wi 10 -i 5:
```
without this patch   with this patch   units
fasta              349.741             347.511       us/op
fastaredux         196.150             188.920       us/op
```
And here is a division unit test:
```
private final int func(int n, int[] arr) {
int ret = 0;
for (int i = 0; i < n; i++) {
int var = …
```
> Canonicalize a/num to a*(temp_num)>>n for non-power-of-2 constant division.

- compiler/src/org.graalvm.compiler.hotspot.test/src/org/graalvm/compiler/hotspot/test/CheckGraalIntrinsics.java
- compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/GraalHotSpotVMConfig.java
- compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/HotSpotBackend.java
- compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/meta/HotSpotGraphBuilderPlugins.java
- compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/meta/HotSpotHostForeignCallsProvider.java
- compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/replacements/DigestBaseSubstitutions.java
- compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/replacements/HotSpotReplacementsUtil.java
This patch implements SHA1/2/5::implCompress Multi-Block from base DigestBase class.
It needs review as it is not-working as is. I am fairly confident the code is close-to-finish, but for some reason I run into a NullPointer exception line 97 of DigestModeSubstitutions.java. I have identified shaObj as being null, but I do not understand why. The object is casted from DigestBase to its derived class line 61 of the same file.
I also had to annotate getType as an @Fold method.
Please let me know your insights.
> SHA1/2/5::implCompressMB stub

- compiler/src/org.graalvm.compiler.replacements/src/org/graalvm/compiler/replacements/IntrinsicGraphBuilder.java
There is a NullPointerException in `IntrinsicGraphBuilder.java`.
Check for null in `.updateLastInstruction()`.
Running the script at https://gist.github.com/cosmicexplorer/b8b4128315dfb4a30f462c5e73e5cd83 on `master` should produce:
```
Caused by: java.lang.NullPointerException
at org.graalvm.compiler.replacements.IntrinsicGraphBuilder.updateLastInstruction(IntrinsicGraphBuilder.java:130)
at org.graalvm.compiler.replacements.IntrinsicGraphBuilder.append(IntrinsicGraphBuilder.java:148)
at org.graalvm.compiler.replacements.StandardGraphBuilderPlugins$UnsafeAccessPlugin.createUnsafeAccess(StandardGraphBuilderPlugins.java:1058)
at org.graalvm.compiler.replacements.StandardGraphBuilderPlugins$UnsafePutPlugin.apply(StandardGraphBuilderPlugins.java:1154)
at …
```
> fix NullPointerException when previous instruction in updateLastInstruction() is null

- substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/PosixJavaNetSubstitutions.java
Fixes ##1087
I'm a Red Hat employee so I believe I won't need to sign an individual contributor agreement.
It's my first contribution. Please let me know if I should do anything else; I'm wondering also if I should add a regression test? I could use a pointer to an example of how you want such tests structured.
Thanks!
> Allow disabling SO_LINGER on java.net.Socket

- compiler/src/org.graalvm.compiler.core.aarch64.test/src/org/graalvm/compiler/core/aarch64/test/AArch64TestBitAndBranchTest.java
- compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64ControlFlow.java
- compiler/src/org.graalvm.compiler.lir/src/org/graalvm/compiler/lir/asm/CompilationResultBuilder.java
Change buildLabelOffsets to also record the LIR instruction offset
besides recording label. It will make labelWithinRange work with
BitTestAndBranchOp on AArch64.
Also correct the isFarBranch flag value in BitTestAndBranchOp emit
and fix the AArch64TestBitAndBranchTest.
Change-Id: Idf3454f7db0895360c63ef6ca434fb51e5db2fcc
> Fix errors in aarch64 TBZ implementation.

- compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/GraalHotSpotVMConfig.java
- compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/HotSpotBackend.java
- compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/meta/HotSpotGraphBuilderPlugins.java
- compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/meta/HotSpotHostForeignCallsProvider.java
- compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/graphbuilderconf/InvocationPlugin.java
Implements Base64::encodeBlock stub enablement as an InvocationPlugin. Currently does not apply.
Base64$Encoder is a subclass of Base64.Encoder. My assumption is that the class name string in the Registration is wrong. I have tried $ and # signs but I was out of luck there too.
Another question I have is whether the BASE64_ENCODE_BLOCK instance should have its last constructor argument as a boolean.class or int.class, since I think we are dealing with bytecode at this point.
Let me know your thoughts.
Jp
> Base64::encodeBlock stub

- compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64Move.java
While HotSpot supported `fldr` to load them from a relatively close-by location,
in a native-image binary, the address space addressable by `fldr` is not sufficient
to locate a complex double placed in the data section.
Replace with an adrp/add + fldr against a scratch register to accomodate both.
> Support non-literal/non-inlinable doubles & floats for native-image

- compiler/src/org.graalvm.compiler.core.aarch64.test/src/org/graalvm/compiler/core/aarch64/test/AArch64TestBitAndBranchTest.java
- compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64NodeMatchRules.java
As  we have "if !(n < 0) <=> tbz n, sizeOfBits(n) - 1, label" in AArch64, this patch add a special match rule to find the case where IfNode has the condition that the greater value of  IntergerLessThanNode is zero and then simplify the generated assembly code from cmp, b.lt to tbz.
Change-Id: I7e72e12a0efea65b4fdc513200d105220590babe
> Use AArch64 instruction tbz #31 to do negative check in Graal

- compiler/mx.compiler/suite.py
- compiler/src/org.graalvm.compiler.hotspot.aarch64.test/src/org/graalvm/compiler/hotspot/aarch64/test/AArch64UncompressPointerTest.java
- compiler/src/org.graalvm.compiler.hotspot.aarch64/src/org/graalvm/compiler/hotspot/aarch64/AArch64HotSpotMove.java
Currently decoding a compressed pointer with zero base will generate
the following code:
`add x0, xzr, x0, lsl #3`
This patch will optimize it to:
`lsl x0, x0, #3`
Here is a jmh benchmark to decode a compressed pointer:
```
public class UncompressPointer {
private static final int field0 = 1000000;
private int field1;
static class A {
B b;
A(B b) {
this.b = b;
}
}
static class B {
int field;
B(int i) {
this.field = i;
}
}
static A[] arr;
static {
arr = new A[field0];
for (int i = 0; i < field0; i++)
arr[i] = new A(new B(i));
}
public static int func() {
int result = 0;
for (int i = 0; i < field0; i++) {
result += arr[i].b.field;
}
return result;
}
@Benchmark
public void jmhUncompressPointer() {
field1 = func();
}
}
```
And the performance results:
```
Score      Error    Units
Without …
```
> AArch64: Compressed pointer decoding optimization when base is zero.

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/NativeLibrarySupport.java
I believe this could be the fix for #438 
The code in :
https://github.com/oracle/graal/blob/cbadcf6f7a1890562984e1c581f7c3b31809b34e/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/NativeLibrarySupport.java#L91-L95
is able to deal with the requirement to list multiple paths for the _java.library.path_ system property, but then the code attempting to load the libraries is expecting to have "false" returned on failure from one path, so to try the next path.
However the failed attempt to load the library from the first path immediately causes an `UnsatisfiedLinkError` to be thrown, so the additional paths are never tested.
see also:
- https://github.com/quarkusio/quarkus/pull/1674
I'd be happy to add an integration test, but I'm not familiar with how you might prefer …
> Need to try all paths listed by 'java.library.path' before throwing UnsatisfiedLinkError

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/aarch64/AArch64FrameAccess.java
Helps to allow for native-image to be native-image'd on aarch64.
> Fold base-pointer-size as a constant.

- compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64Move.java
- substratevm/src/com.oracle.svm.core.graal/src/com/oracle/svm/core/graal/code/aarch64/SubstrateAArch64Backend.java
This avoids an issue where null + offset for CCharPointers
involving Unsafe.copyMemory(...) would end up being offsets
from the heap-base register, incorrectly.
In general, it's a good thing to have in the codebase.
> Add conversion of null to/from zero for aarch64.

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/CPUFeatureAccess.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/aarch64/AArch64CPUFeatureAccess.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/amd64/AMD64CPUFeatureAccess.java
- substratevm/src/com.oracle.svm.graal/src/com/oracle/svm/graal/SubstrateGraalUtils.java
Hide architecture-specific CPU feature manipulation behind
the specific installed CPUFeatureAccess relevant to the
current architecture.
> Refactor additional architecture-specific CPU feature manipulation.

- compiler/src/org.graalvm.compiler.asm.amd64/src/org/graalvm/compiler/asm/amd64/AMD64Assembler.java
- compiler/src/org.graalvm.compiler.core.amd64/src/org/graalvm/compiler/core/amd64/AMD64ArithmeticLIRGenerator.java
- compiler/src/org.graalvm.compiler.graph/src/org/graalvm/compiler/graph/spi/Canonicalizable.java
- compiler/src/org.graalvm.compiler.hotspot.amd64/src/org/graalvm/compiler/hotspot/amd64/AMD64HotSpotBackendFactory.java
- compiler/src/org.graalvm.compiler.hotspot.test/src/org/graalvm/compiler/hotspot/test/CheckGraalIntrinsics.java
- compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/GraalHotSpotVMConfig.java
- compiler/src/org.graalvm.compiler.lir.amd64/src/org/graalvm/compiler/lir/amd64/AMD64Ternary.java
- compiler/src/org.graalvm.compiler.lir/src/org/graalvm/compiler/lir/gen/ArithmeticLIRGeneratorTool.java
- compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/calc/TernaryNode.java
- compiler/src/org.graalvm.compiler.replacements.amd64/src/org/graalvm/compiler/replacements/amd64/AMD64GraphBuilderPlugins.java
- compiler/src/org.graalvm.compiler.replacements/src/org/graalvm/compiler/replacements/nodes/FusedMultiplyAddNode.java
Initial PR for FMA intrinsics support. It implements the design suggested on the graal mailinglist, namely:
1. Add FMA instructions in VexRVMOp in AMD64Assembler
a. It requires to add the VexOpAssertion.FMA and use CPUFeature.FMA flags
2. Add UseFMA flag from HotSpot flags in GraalHotSpotVMConfig.java
3. Add a registerFMA method in AMD64GraphBuilderPlugins::registerMathPlugins
a. This requires to add a specific FusedMultiplyNodeNode, which will emit the corresponding FMA instructions.
--> Need for TernaryNode support and AMD64Ternary support
I have a few questions regarding this PR considering this is the first time I touch a couple of things. I will post comments to make it easier.
> Float, Double Scalar FMA intrinsics

- substratevm/src/com.oracle.svm.native.jvm.posix/src/JvmFuncs.c
This is just a basic implementation that always returns 0.
Most important is that there is an implementation that is not returning -1.
When this PR got accepted, a new issue should be created for writing a proper implementation.
This fixes #1263
> add simple implementation for JVM_GetNanoTimeAdjustment()

- substratevm/src/com.oracle.svm.core.graal/src/com/oracle/svm/core/graal/code/aarch64/SubstrateAArch64Backend.java
- substratevm/src/com.oracle.svm.core.graal/src/com/oracle/svm/core/graal/code/aarch64/SubstrateAArch64RegisterConfig.java
I welcome review of the actual deopt-frame implementation, as it's a naive transliteration of the AMD64 variant
> Add support for calling-convention and deopt on AArch64 SVM.

- substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/PosixJavaIOSubstitutions.java
This fixes #1038, in case the JNI platform is used.
> add inputConsumed and outputConsumed field for JNI access.

- substratevm/src/com.oracle.svm.native.jvm.posix/src/JvmFuncs.c
Those should not be called, but libjava.a relies on their availability
This fixes #1279
> Provide definitions for JVM_Module functions.

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/thread/JavaThreads.java
This sounds plausible for threads that are generated by the OS.
This fixes #1281
> set the contextClassLoader of this thread to be the System Classloader.

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/SystemPropertiesSupport.java
> Allow os.name and os.arch to be set when cross-compiling

- compiler/src/org.graalvm.compiler.core.aarch64.test/src/org/graalvm/compiler/core/aarch64/test/AArch64BitFieldTest.java
- compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64NodeMatchRules.java
- compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64BitFieldOp.java
This patch adds match rules for AArch64 Unsigned Bit Field Extract
(UBFX) and Unsigned Bit Field Insert in Zero (UBFIZ) operations.
After this change, AArch64 instruction sequence like
lsr     w0, w1, #5
and     w0, w0, #0xff
could be replaced by
ubfx    w0, w1, #5, #8
and instruction sequence like
and     w0, w1, #0x3
lsl     w0, w0, #16
could be replaced by
ubfiz   w0, w1, #16, #2
> AArch64: Add MatchRules for bit field operations

- compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64Assembler.java
- compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64MacroAssembler.java
- substratevm/src/com.oracle.svm.core.graal/src/com/oracle/svm/core/graal/code/aarch64/AArch64CGlobalDataLoadAddressOp.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/code/aarch64/SingleInstructionHostedPatcher.java
Renaming methods to better match what they do.
Renaming classes to better express what they do.
> Cleanup on aisle aarch64.

- compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64Move.java
@pli-arm this PR fixes issue #1337. Please doublecheck and confirm so I can merge this change.
> AArch64: Supply scratch register on move reg2stack

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/Target_java_lang_Module.java
The WeakPairMap inside Module$ReflectionData was changing,
sometimes, during heap generation of native-image.
Delete the class and no-op the relevant methods that used it.
Might be a sub-optimal solution, but avoids spurious native-image
failures at this point when using JDK11+.
> No-op module reflection modifications.

- compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/replacements/NewObjectSnippets.java
In the snippet code for allocating new array/object, method fillMemory()
calls ZeroMemoryNode.zero() without checking the value to fill is zero
or not. And, to be more accurate, the value of "size - offset", which is
the actual number of bytes to be zeroed, should be compared against the
value of "MinimalBulkZeroingSize".
> Fix condition for memory bulk zeroing

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/aarch64/AArch64FrameAccess.java
Since the FrameContext uses `stp fp, lr, ...` to store the
`fp` and `lr` as the first two words in the frame,
the layout is actually:
--------- frame start ---------
lr (word)
fp (word)
--------- rest of frame -------
...
Therefore, when walking the stack, to read the return value
of a given frame with an effective frame-start address, the
immediately first word is the `lr`. Reading the second results
in reading the `fp` which ultimately results in a bus error
on AArch64.
> AArch64 - Read return address correctly.

- substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/PosixJavaNetSubstitutions.java
Two instances of incorrect transliteration of the original C code:
1) gethostname() returns zero to indicate success, not an error
2) NET_SockaddrToInetAddress returns null when unsuccessful, non-null when successful.
> Fix for #1338 - UnknownHostException when network down on OSX

- compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/calc/SignedDivNode.java
The conditions that a division can be replaced by one shift
instruction are:
1. The divisor is power-of-2.
2. The dividend is positive, or its low bits are always 0.
Otherwise, the dividend needs to be rounded if we still want to
replace the division by shift when the divisor is power-of-2.
But the conditions to round the dividend in Graal is:
"if (stampX.canBeNegative() || (stampX.upMask() & (abs - 1)) != 0)"
So if stampX is positive, and its low bits are not always 0, it will
also be rounded. This will also generate the rounding instructions,
which is redundant.
This patch modifies the conditions to make sure that any positive
dividend is not rounded.
Change-Id: I3bf4eceb11f50d3aa6e0bc606f7927f20259a477
> Fix rounding conditions for SignedDivNode when canonicalized.

- substratevm/src/com.oracle.svm.core.graal.llvm/src/com/oracle/svm/core/graal/llvm/LLVMNativeImageCodeCache.java
- substratevm/src/com.oracle.svm.core.graal.llvm/src/com/oracle/svm/core/graal/llvm/LLVMOptions.java
This PR allows the compilation of LLVM bitcode to machine code in the LLVM backend of native image to occur on multiple threads, which makes this part of the build faster (local trials show a 4x speedup).
The level of parallelism can be set using the LLVMBatchesPerThread option, which specifies how many batches should be formed for every available thread, the default being 1. A setting of 0 is equivalent to the current method, in which all functions are linked into a single batch before being passed to the LLVM compiler.
Edit: changed the name of the option to LLVMBatchesPerThread
> Parallelized build for the LLVM backend

- compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/graphbuilderconf/GraphBuilderConfiguration.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/phases/SharedGraphBuilderPhase.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/substitute/UnsafeAutomaticSubstitutionProcessor.java
Due to the fact an unresolved type may (previous to this commit)
throw a parse exception when attempting to perform automatic unsafe
substitutions, this can result in a null slot being left in the
universe of types array.
Which then ends up being an unresolve type error of type 'null'
subsequently when attempting to resolve null as a type.
Allow the graph-builder to respect the the default false value of
`unresolvedIsError` by not throwing in such a case.
> Avoid NPE when parsing static initializers.

- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/substitute/UnsafeAutomaticSubstitutionProcessor.java
Since it's a JDK class that we can't fix, and probably
can't convince the JDK team to use a field instead of
a local (since a local is all that is required), might as
well whitelist it from the unsafe automatic substitutions
warnings.
Meanwhile, let's spell "suppress" correctly while we're there.
> Add `InnocuousThread` to the warning whitelist.

- substratevm/src/com.oracle.svm.native.jvm.posix/src/JvmFuncs.c
This PR provides an implementation for `JVM_GetNanoTimeAdjustment` that fixes #1274.
It is based on the adaptation of [SunMiscSubstitutions::getNanoTimeAdjustment](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/SunMiscSubstitutions.java#L448).
> #1274 Implement JVM_GetNanoTimeAdjustment

- substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/JavaUtilZipSubstitutions.java
In this PR I fixed small mistake in `JavaUtilZipSubstitutions.doInflate` method that caused different exceptions related to Inflater on JDK11. In fact, I only synchronized Java and C implementations (see https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/19fb8f93c59dfd791f62d41f332db9e306bc1422/src/java.base/share/native/libzip/Inflater.c#L143 )
Minimal example:
```
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.zip.GZIPInputStream;
import java.net.URL;
import java.net.URLConnection;
public class GzipExample {
public static void main(String[] args) throws Exception {
final URL url = new URL("https://google.com");
final URLConnection urlConnection = url.openConnection();
urlConnection.setRequestProperty("Accept-Encoding", …
```
> [native-image][JDK11] Fix error in JavaUtilZipSubstitutions.doInflate

- substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/JavaNetNetworkInterface.java
- substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/PosixJavaNetSubstitutions.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/NetworkInterfaceTest.java
Fixes #1267 . Transliterate JDK C to Java as appropriate.
- isLoopback0()
- getFlags0()
- openSocketWithFallback()
$ ./com.redhat.network.networktest
name:en5 (en5) ==> false
name:utun1 (utun1) ==> false
name:utun0 (utun0) ==> false
name:awdl0 (awdl0) ==> false
name:en0 (en0) ==> false
name:lo0 (lo0) ==> true
> Fix for #1267 - NetworkInterface#isLoopback()

- substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/PosixJavaNetSubstitutions.java
- substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/headers/NetinetIn.java
- substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/headers/linux/LinuxIn.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/GitHub1398.java
> Introduce implementation for PlainDatagramSocketImpl.mcast_join_leave

- compiler/src/org.graalvm.compiler.asm.aarch64.test/src/org/graalvm/compiler/asm/aarch64/test/AArch64BitCountAssemblerTest.java
- compiler/src/org.graalvm.compiler.hotspot.aarch64/src/org/graalvm/compiler/hotspot/aarch64/AArch64HotSpotBackend.java
This fixes issue #1439
For Graal CodeGenTest cases, assembly code generated by assembler or macro assembler is installed into HotSpot as an nmethod. But AArch64 requires the instruction at nmethod verifed entry to be a jump or nop for method invalidation in sweeper thread. To meet the requirement, we patch the generated test code by inserting a nop at the beginning.
> Fix CodeGenTest issue for AArch64

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JavaLangSubstitutions.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/GetPackageTest.java
> Allow Class.getPackage() to work on Java 11

- compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64Assembler.java
- compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64LIRGenerator.java
- compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64LoweringProviderMixin.java
- compiler/src/org.graalvm.compiler.core.amd64/src/org/graalvm/compiler/core/amd64/AMD64ArithmeticLIRGenerator.java
- compiler/src/org.graalvm.compiler.core.amd64/src/org/graalvm/compiler/core/amd64/AMD64LIRGenerator.java
- compiler/src/org.graalvm.compiler.hotspot.aarch64/src/org/graalvm/compiler/hotspot/aarch64/AArch64HotSpotLIRGenerator.java
- compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/GraalHotSpotVMConfig.java
- compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64ZeroMemoryOp.java
- compiler/src/org.graalvm.compiler.lir/src/org/graalvm/compiler/lir/gen/ArithmeticLIRGeneratorTool.java
- compiler/src/org.graalvm.compiler.lir/src/org/graalvm/compiler/lir/gen/LIRGeneratorTool.java
- compiler/src/org.graalvm.compiler.replacements/src/org/graalvm/compiler/replacements/nodes/ZeroMemoryNode.java
Current AArch64 Graal generates inefficient STR loops to zero memory of
new arrays/objects in TLAB fast path. To improve the performance of new
array/object allocations, this patch implements memory bulk zeroing with
AArch64 store pair (STP) and cache maintenance (DC ZVA) instructions.
In this implementation, we try to read the pre-loaded value of AArch64
system register DCZID_EL0 from HotSpot field via JVMCI at compile-time,
and generate loops with DC ZVA instruction based on the zva length. In
cases that use of DC ZVA is prohibited, bulk zeroing is disabled by VM
options or the HotSpot field is unable to read, we generate bulk zeroing
code with STP instructions as a fallback.
Performance numbers of JMH case ArrayAllocationBenchmark.java:
```
(size)        Before         After  Units …
```
> Memory bulk zeroing for AArch64

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JavaLangReflectSubstitutions.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/ArraySetTest.java
Fixes #1585
Avoid checking assignability of the value to the array
element type if the value is null, and therefore `.getClass()`
is pretty much guaranteed to throw an NPE.
@cstancu I have no idea how to make Checkstyle actually stop uselessly whinging about the import in my test:
`/Users/bob/repos/oracle/graal/substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/ArraySetTest.java:28: Illegal import - java.lang.reflect.Array.`
I've attempted a `// Checkstyle: off` but that doesn't seem sufficient.
I also question the need for such stringent checkstyle/linting/formatting in tests. Seems to just cause more non-functional work to make random compiler tools "happy" about code that doesn't even ship to end-users. Sorta discourages testing, in fact.
> Allow Array.set(objArray, index, null) to not throw NPE.

- substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/PosixJavaIOSubstitutions.java
Relates to, but probably isn't a fix for #1581.
Comparing the code to JDK8, there is missing error-handling which could, I guess, result in a directory stream being left open.
> Add a try/finally to ensure the dir stream gets closed.

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/RecomputedFields.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/ForkJoinTest.java
Fixes #552
Includes test demonstrating that the ForkJoinTask can indeed
handle the thrown exception, repropagating it, instead of ultimately
throwing a not-implemented at runtime, obscuring the underlying
real exception.
> Remove not-implemented throw from ForkJoinTask.

- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageGenerator.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageOptions.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeBootImageViaCC.java
> Allow to stop building after the relocatable object file is written.

- vm/README.md
* Sulong is now part of the graal repo, it should be referenced from the root of the repo.
* Otherwise you get error `Imported suite 'sulong' not found (binary or source).`
> Update sulong dynamic dependency

- compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64ReadNode.java
- compiler/src/org.graalvm.compiler.phases.common/src/org/graalvm/compiler/phases/common/AddressLoweringByUsePhase.java
This patch fixes issue:https://github.com/oracle/graal/issues/1408.
Graal AddressLoweringPhase lowers the general address node to platform
specific address node, like AArch64AddressNode, and together with some
optimizations. It should use the right memory access type to set the
suitable address mode and scaleFactor. But currently it uses the node type.
An AArch64ReadNode is a node merges ZeroExtended/SignedExtended with
ReadNode. If the type of the ReadNode is 32bits. After extending, the
type of the AArch64ReadNode is 64bits, but its access type is still 32bits.
So if the compiler is lowering an AArch64ReadNode and using its node type,
the result address will be wrong.
This patch modifies the stamp of the address to the access stamp.
Change-Id: I0a805134bbff22f9df5626ccdeda95f41ed721e6
> Use memory access stamp of Read/WriteNode to do address lowering.

- truffle/src/com.oracle.truffle.api/src/com/oracle/truffle/api/CompilerAsserts.java
This PR extends the Javadocs of `CompilerAsserts#compilationConstant(Object)` and
`CompilerAsserts#partialEvaluationConstant(Object)` and makes clear which one is preferred. It also adds cross-references and adjusts the Javadocs of the specialized variants of `CompilerAsserts#partialEvaluationConstant(Object)`.
/cc @chumer
> Clarify difference between constantness checks

- compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64MacroAssembler.java
- compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64ArithmeticLIRGenerator.java
- compiler/src/org.graalvm.compiler.hotspot.aarch64/src/org/graalvm/compiler/hotspot/aarch64/AArch64HotSpotBackendFactory.java
- compiler/src/org.graalvm.compiler.hotspot.test/src/org/graalvm/compiler/hotspot/test/CheckGraalIntrinsics.java
- compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64ArithmeticOp.java
- compiler/src/org.graalvm.compiler.replacements.aarch64/src/org/graalvm/compiler/replacements/aarch64/AArch64GraphBuilderPlugins.java
Math.fma returns the exact product of the first two arguments summed with the third argument and then rounded once. This behaviour has no difference with that of the AArch64 FMADD instruction. So this patch enables Math.fma intrinsics if VM option "UseFMA" is set and the JDK version is greater than 8.
> Enable Math.fma intrinsics for AArch64

- docs/Publications.md
This adds
- the two publications from 2019 mentioned [here](https://www.graalvm.org/community/publications/)
- five publications from the [Software Architecture Group](https://www.hpi.uni-potsdam.de/hirschfeld/publications/index.html), HPI, University of Potsdam, Germany
> Add recent publications

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/hub/DynamicHub.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/classinitialization/ClassInitializationFeature.java
When a class is firstly recoganzied to initialize at RUN_TIME and later proven safe to initialize at BUILD_TIME, it misses the chance to set its DynamicHub.classInitializationInfo to INITIALIZED_INFO_SINGLETON, resulting duplicated initialization at runtime. 
The following test case can reproduce the issue, and it can be fixed by this PR.
```
package test.init;
import java.util.HashMap;
import java.util.Map;
/**
* java -cp bin -agentlib:native-image-agent=config-output-dir=TestDupInitConfig/META-INF/native-image test.init.TestDupInit
* $native_image -cp bin:TestDupInitConfig test.init.TestDupInit
* @author cengfeng.lzy@alibaba-inc.com
*
*/
public class TestDupInit {
static {
//Make sure Letter get initialized at runtime 
System.out.println(Letter.getMappings().size());
}
public static …
```
> Prevent duplicated static initialization at runtime

- compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64Assembler.java
- compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64MacroAssembler.java
- compiler/src/org.graalvm.compiler.core.aarch64.test/src/org/graalvm/compiler/core/aarch64/test/AArch64MultiplyLongTest.java
- compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64ArithmeticLIRGenerator.java
- compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64NodeMatchRules.java
- compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64ArithmeticOp.java
This adds AArch64 node match rules for multiplying two 32-bit integers to a 64-bit long, and/or with an additional add, sub or neg operation. With this patch, the AArch64 backend generates SMULL, SMADDL, SMSUBL or SMNEGL instructions so the sign extend operations are eliminated.
> AArch64: Add missing match rules for signed multiply long

- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/classinitialization/ConfigurableClassInitialization.java
This pull request tries to fix a bug during generate stack traces as a string. 
A stack trace during class initialization has been pruned in the method `ConfigurableClassInitialization.relevantStackTrace()`, where the top `START_OF_THE_TRACE `, i.e., the beginning four irrelevant stack frames are skipped. Therefore, in the method `getTraceString()`, where a stack trace is transformed into a string, it is unnecessary to skip the beginning four frames, since those have already been removed. 
In this pull request, the trace string is generated from the first element of a stack trace.
> Generate complete stack trace string

- compiler/src/org.graalvm.compiler.core.aarch64.test/src/org/graalvm/compiler/core/aarch64/test/AArch64ElideL2ITest.java
- compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64NodeMatchRules.java
Narrowing a value from long to int type will generate a "mov"
instruction. The "mov" generated by L2I can be elided because
the 32-bit instruction will just employ the lower 32bits anyway.
This patch does not elide all the L2I conversions. It only elides
L2I for binary/unary operations by adding match rules.
Change-Id: I1bdc7fc27f9e754875be228d5caad59e517b6578
> AArch64: Elide L2I for binary and unary operations.

- substratevm/src/com.oracle.svm.core.graal.aarch64/src/com/oracle/svm/core/graal/aarch64/SubstrateAArch64Backend.java
Code for reading a frame's return address was not being generated
correctly in one place. As shown in AArch64FrameMap.java, the return
address is at the top of the frame.
Change-Id: I3465956f82846530dfe0eb9e50782540ed4d1056
> AArch64: Fixed a bug in reading return address.

- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/DisallowedImageHeapObjectFeature.java
Fixes https://github.com/oracle/graal/issues/1849.
The commit here fixes the error message printed out by `DisallowedImageHeapObjectFeature`.
> Fix the error message in DisallowedImageHeapObjectFeature to refer to initialize-at-run-time instead of initialize-at-build-time

- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/ForkJoinTest.java
Fixes https://github.com/oracle/graal/issues/1855
The commit here updates the `ForkJoinTest` to try and find the `FileNotFoundException` within the exception hierarchy.
> Fix the com.oracle.svm.test.ForkJoinTest

- compiler/docs/Truffle.md
- compiler/src/org.graalvm.compiler.hotspot.test/src/org/graalvm/compiler/hotspot/test/CompilationWrapperTest.java
- sdk/src/org.graalvm.launcher/src/org/graalvm/launcher/MultiLanguageShell.java
- sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/hosted/Feature.java
- sdk/src/org.graalvm.polyglot/src/org/graalvm/polyglot/Source.java
- substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/linux/ProcFSSupport.java
- truffle/src/com.oracle.truffle.api.dsl.test/src/com/oracle/truffle/api/dsl/test/PolymorphicTest.java
- truffle/src/com.oracle.truffle.api.dsl.test/src/com/oracle/truffle/api/dsl/test/TestHelper.java
- truffle/src/com.oracle.truffle.api/src/com/oracle/truffle/api/source/Source.java
- vm/src/org.graalvm.component.installer/src/org/graalvm/component/installer/Bundle.properties
This typo surfaced in the polyglot shell (see https://github.com/oracle/truffleruby/issues/1831). Turns out there are some more *occur**r**ences* of 'occure'* in the code base.
See https://www.lexico.com/en/definition/occur
> Fix occurrences of occure*

- substratevm/mx.substratevm/mx_substratevm.py
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/SecurityServicesFeature.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/SecurityServiceTest.java
Fixes https://github.com/oracle/graal/issues/1883
The `SecurityServicesFeature` adds an (internal) callback to register certain `java.security.Provider.Service` related classes for reflection. This callback is triggered if/when the `Provider.Service#newInstance` method is reachable in the application. When this callback gets triggered, it uses the `java.util.Provider#knownEngines` (internal) private field to get hold of certain details. This `knownEngines` will only contain details of services that are shipped within the JDK. As a result, if the application uses non-JDK related services, this `knownEngines` will not have information for such service types. The code, which tries to do the reflection registration, however doesn't check for `null` in such cases and that results in the …
> Prevent NullPointerException in SecurityServicesFeature

- substratevm/src/com.oracle.svm.core.graal.amd64/src/com/oracle/svm/core/graal/amd64/SubstrateAMD64LoweringProvider.java
- substratevm/src/com.oracle.svm.core.graal/src/com/oracle/svm/core/graal/meta/SubstrateBasicLoweringProvider.java
- substratevm/src/com.oracle.svm.core.graal/src/com/oracle/svm/core/graal/snippets/ArithmeticSnippets.java
- substratevm/src/com.oracle.svm.core.graal/src/com/oracle/svm/core/graal/snippets/NonSnippetLowerings.java
- substratevm/src/com.oracle.svm.core.graal/src/com/oracle/svm/core/graal/snippets/aarch64/AArch64ArithmeticSnippets.java
- substratevm/src/com.oracle.svm.core.graal/src/com/oracle/svm/core/graal/snippets/aarch64/AArch64NonSnippetLowerings.java
- substratevm/src/com.oracle.svm.core.graal/src/com/oracle/svm/core/graal/snippets/aarch64/AArch64SnippetsFeature.java
- substratevm/src/com.oracle.svm.core.graal/src/com/oracle/svm/core/graal/snippets/aarch64/PosixAArch64VaListSnippets.java
- substratevm/src/com.oracle.svm.core.graal/src/com/oracle/svm/core/graal/snippets/amd64/AMD64ArithmeticSnippets.java
- substratevm/src/com.oracle.svm.core.graal/src/com/oracle/svm/core/graal/snippets/amd64/AMD64NonSnippetLowerings.java
- substratevm/src/com.oracle.svm.core.graal/src/com/oracle/svm/core/graal/snippets/amd64/AMD64SnippetsFeature.java
- substratevm/src/com.oracle.svm.core.graal/src/com/oracle/svm/core/graal/snippets/amd64/PosixAMD64VaListSnippets.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageGenerator.java
Before there was not a proper separation of between AMD64 and AArch64 specific
lowerings.
Refactored architecture-specific functionality into separate classes.
Also added proper AArch64 RemNode lowering support, and removed
AMD64-specific FloatConvertNode and AMD64ArrayIndexOfDispatchNode
lowering from AArch64 path.
Change-Id: I322dc97c8d9ce9fb521c53304400a6e29f5da6fe
> AArch64: Fixed some lowering issues.

- .travis.yml
- compiler/mx.compiler/mx_compiler.py
Currently the travis-ci of the graal community does not support
tests on AArch64. This could not block patches that might break
AArch64. Fortunately the travis-ci has supported the multi-cpu
architecture tests recently. So it's time to enable the AArch64
tests for graal.
To enable the AArch64 tests and make them run smoothly, this patch
gives the following modifications:
- Add compiler tests for AArch64.
- Set the JAVA_HOME if it is not set.
- Adjust the java version checking rule to make it also work for
AdoptOpenJDK, which is the openjdk11 installed on travis Arm64.
Change-Id: Ia5cf7f4ea885c62a630917afd1d2cab74c3bbc19
> Enable AArch64 travis-ci tests.

- substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/aarch64/AArch64UContextRegisterDumper.java
- substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/darwin/DarwinUContextRegisterDumper.java
- substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/headers/Signal.java
This patch was mentioned a couple of months ago by someone from the GraalVM team.
It is sub-optimal since it is not providing a real solution for a register dump on iOS, and it uses the compilerBackend as the condition between using a real registerDumper or a fake one.
On the other hand, this functionality makes little sense on iOS, so from a functional point, this patch seems ok.
Without this patch, native-image fails to compile applications, as there is no Signal$ucontext_t method for Platform.DARWIN_AARCH64.class and neither using the LINUX_AARCH64 or the DARWIN_AMD64 platform will do (since either the architecture or the OS is wrong).
> Use a darwin AMD64 based UContextRegisterDumper in case of darwin AArch64

- substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/util/Timer.java
As a user of Native Image I'd like to be able to see how much heap the Native Image process is using, in order to be able to understand how much I'm using the capacity of my CI instance in order to check it's an appropriate size, and also to monitor if the compilation is using more memory than expected, similar to how the number of methods for runtime compilation is printed.
The alignment formatting will break a little if the process uses 100 GB or more, but harmlessly. We obviously can't calculate maximum column length ahead of time.
Example output:
```
[libjvmcicompiler:29812]    classlist:   3,769.93 ms,  1.21 GB
[libjvmcicompiler:29812]        (cap):   1,068.88 ms,  1.21 GB
[libjvmcicompiler:29812]        setup:   2,416.79 ms,  1.21 GB
[libjvmcicompiler:29812]   (typeflow):  31,246.89 …
```
> Print heap size during Native Image compilation

- compiler/src/org.graalvm.compiler.asm.aarch64.test/src/org/graalvm/compiler/asm/aarch64/test/AArch64LoadStoreMergingAssemblerTest.java
- compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64Assembler.java
- compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64MacroAssembler.java
- compiler/src/org.graalvm.compiler.core.aarch64.test/src/org/graalvm/compiler/core/aarch64/test/AArch64PairLoadStoreTest.java
- compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64Move.java
- compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64Unary.java
- compiler/src/org.graalvm.compiler.lir/src/org/graalvm/compiler/lir/asm/CompilationResultBuilder.java
This patch will merge two ldr/str to one ldp/stp, like:
```
str x1, [sp, #128]
str x2, [sp, #120]
```
will be merged to:
```
stp x2, x1, [sp, #120]
```
The same to the load operation.
We have to begin this optimization after register allocation,
so that some loads/stores generated for spilling can also be optimized.
Besides we should take care of the following tips:
1. The second ldr/str is not bound to a label.
2. We need to update the Infopoint list when an ImplicitException is
recorded at the second ldr/str position. In this patch, I updated its
position to the first ldr/str position.
3. Some basic ldr/str instruction form checkings when merging to ldp/stp.
More details can be found in my patch.
Here are two jmh cases for this patch:
```
private static int pairLoad() {
int ret = 0;
for …
```
> Merge two consecutive ldr/str to ldp/stp for AArch64.

- compiler/src/org.graalvm.compiler.replacements/src/org/graalvm/compiler/replacements/classfile/Classfile.java
The aot and graalunit jtreg tests fail when run with graal after
the java version of the jdk/jdk master being updated to 15. This
is caused by the class file version checking in Graal. It should
be inside the defined java version range. Currently the max java
version is defined to 14, which should be updated to 15.
Change-Id: I4431ceda3ea2f62efdc5ebee3c8ba13c319b4a4d
> Update supported max java version to 15.

- compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64SuitesCreator.java
- compiler/src/org.graalvm.compiler.core.amd64/src/org/graalvm/compiler/core/amd64/AMD64SuitesCreator.java
- compiler/src/org.graalvm.compiler.java/src/org/graalvm/compiler/java/DefaultSuitesCreator.java
- substratevm/src/com.oracle.svm.core.graal.aarch64/src/com/oracle/svm/core/graal/aarch64/SubstrateAArch64Feature.java
- substratevm/src/com.oracle.svm.core.graal.aarch64/src/com/oracle/svm/core/graal/aarch64/SubstrateAArch64SuitesCreatorProvider.java
- substratevm/src/com.oracle.svm.core.graal.amd64/src/com/oracle/svm/core/graal/amd64/SubstrateAMD64Feature.java
- substratevm/src/com.oracle.svm.core.graal.amd64/src/com/oracle/svm/core/graal/amd64/SubstrateAMD64SuitesCreatorProvider.java
- substratevm/src/com.oracle.svm.core.graal.llvm/src/com/oracle/svm/core/graal/llvm/LLVMFeature.java
- substratevm/src/com.oracle.svm.core.graal/src/com/oracle/svm/core/graal/GraalConfiguration.java
- substratevm/src/com.oracle.svm.core.graal/src/com/oracle/svm/core/graal/code/SubstrateSuitesCreatorProvider.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageGenerator.java
Currently some architecture specific optimizations of GraalVM are lost in
substratevm, like the AArch64ReadReplacementPhase for AArch64. In GraalVM,
they are appended either to the suites or to the LIR suites list.
This patch fixes it by using the platform specific suites creator to create
the Mid-End optimization suites and LIR suites.
Change-Id: Ia9b4f26c456311513bba40841221905e11ce3beb
> Native Image: Add arch dependent optimization phases.

- compiler/src/org.graalvm.compiler.core.aarch64.test/src/org/graalvm/compiler/core/aarch64/test/AArch64FloatSqrtTest.java
- compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64ArithmeticLIRGenerator.java
- compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64NodeMatchRules.java
- compiler/src/org.graalvm.compiler.core/src/org/graalvm/compiler/core/gen/NodeMatchRules.java
We can optimize the implementation for float sqrt by adding match rule
like C2:
match(Set dst (ConvD2F (SqrtD (ConvF2D src))))
fcvt    d0, s0
fsqrt   d0, d0
fcvt    s0, d0
After this patch, generated assembly above can be optimized to below:
fsqrt   s0, s0
> AArch64: Better implementation for float sqrt.

- compiler/src/org.graalvm.compiler.asm.aarch64.test/src/org/graalvm/compiler/asm/aarch64/test/AArch64AddressingModeTest.java
- compiler/src/org.graalvm.compiler.asm.aarch64.test/src/org/graalvm/compiler/asm/aarch64/test/AArch64MoveConstantTest.java
- compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64MacroAssembler.java
Code generation of AArch64 constant move is optimized in this patch.
Original implementation uses one MOVZ with one or three MOVK(s) to build
all kinds of 32- or 64-bit constants, respectively. E.g. Below code is
generated for long integer constant -200000L.
```
mov     x1, #0xf2c0
movk    x1, #0xfffc, lsl #16
movk    x1, #0xffff, lsl #32
movk    x1, #0xffff, lsl #48
```
After this patch, we generate a variable length of instruction sequence
containing MOVZ, MOVN with MOVK(s), based on the value of the constant.
Generated assembly in above example is optimized to below.
```
movn    x1, #0xd3f
movk    x1, #0xfffc, lsl #16
```
We also renamed AArch64MacroAssemblerTest to AArch64AddressModeTest in
this patch.
> AArch64: Better instruction sequence for constant move

- compiler/src/org.graalvm.compiler.core.test/src/org/graalvm/compiler/core/test/OffHeapUnsafeAccessTest.java
- compiler/src/org.graalvm.compiler.core.test/src/org/graalvm/compiler/core/test/ea/PartialEscapeUnsafeStoreTest.java
- compiler/src/org.graalvm.compiler.test/src/org/graalvm/compiler/test/GraalTest.java
Use `GraalUnsafeAccess` where possible. Let's not write out `Field theUnsafe = Unsafe.class.getDeclaredField("theUnsafe");` so many times.
https://github.com/Shopify/truffleruby/issues/1
> Use GraalUnsafeAccess where available

- compiler/src/org.graalvm.compiler.core.aarch64.test/src/org/graalvm/compiler/core/aarch64/test/AArch64ArrayAddressTest.java
- compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64AddressLoweringByUse.java
- compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64NodeMatchRules.java
- compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64PointerAddNode.java
- compiler/src/org.graalvm.compiler.core.match.processor/src/org/graalvm/compiler/core/match/processor/MatchProcessor.java
- compiler/src/org.graalvm.compiler.core.test/src/org/graalvm/compiler/core/test/MatchRuleTest.java
- compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/HotSpotReferenceMapBuilder.java
- compiler/src/org.graalvm.compiler.lir/src/org/graalvm/compiler/lir/alloc/lsra/LinearScanLifetimeAnalysisPhase.java
- compiler/src/org.graalvm.compiler.lir/src/org/graalvm/compiler/lir/dfa/RegStackValueSet.java
- compiler/src/org.graalvm.compiler.lir/src/org/graalvm/compiler/lir/phases/EconomyAllocationStage.java
- substratevm/src/com.oracle.svm.core.graal.aarch64/src/com/oracle/svm/core/graal/aarch64/SubstrateAArch64Backend.java
We want to find a better way to implement array offset calculation.
The old pattern for an int array member loading is:
and      x4, x3, #0xffffffff
lsl      x4, x4, #2
add      x4, x4, #0x10
ldr      x0, [x2, x4]
And the optimized pattern is:
add      x1, x2, w3, uxtw #2
ldr      x0, [x1, #16]
Here is a jmh unit test for int array member loading:
```
private final int func(int[] arr) {
int ret = 0;
for (int i=0; i < field0; i++) {
ret += arr[i];
}
return ret;
}
```
And the jmh performance results:
```
without this patch       with this patch       units
1173501.595               948290.420         us/op
```
Here are the additional issues fixed related to this patch:
1. Finetune MarkBasePointers to get better derived reference marking.
Currently there is an issue when marking live base …
> Use add(extended) to generate array index offset for AArch64.

- compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64Assembler.java
- compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64MacroAssembler.java
- compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64Move.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/ELFMachine.java
- substratevm/src/com.oracle.svm.core.graal.aarch64/src/com/oracle/svm/core/graal/aarch64/AArch64CGlobalDataLoadAddressOp.java
- substratevm/src/com.oracle.svm.core.graal.aarch64/src/com/oracle/svm/core/graal/aarch64/AArch64NativeImagePatcher.java
- substratevm/src/com.oracle.svm.core.graal.aarch64/src/com/oracle/svm/core/graal/aarch64/SubstrateAArch64Backend.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/code/aarch64/AArch64HostedPatcher.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/code/aarch64/SingleInstructionHostedPatcher.java
Currently, in SVM relocation is only enabled for adrp/ldr,adrp/add, and
sequences of moves. However, this limitation was previously not always
observed in SVM code.
Also fixed an error in the backend where it was loading an address into
a register, instead of loading the value at the address
Change-Id: I5b4999e73cbd926c4e877f5f43803a08ed7be5b3
> Fixed AArch64 relocation and patching mistakes in SVM.

- compiler/src/org.graalvm.compiler.core.aarch64.test/src/org/graalvm/compiler/core/aarch64/test/AArch64ElideL2ITest.java
- compiler/src/org.graalvm.compiler.core.aarch64.test/src/org/graalvm/compiler/core/aarch64/test/AArch64MergeNarrowWithExtendTest.java
- compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64NodeMatchRules.java
Extending value from narrow type to a wider one will generate a "sxt" or
"and" instruction, and if its input is a NarrowNode, the narrow could be
eliminated.
and     w0, w2, #0xffff
sxth    x0, w0
With this patch, the generated assembly above can be optimized to below:
sxth    x0, w2
Change-Id: Ic1db0f2b11a9d80ca0fab9b042bedff3de66e95a
> AArch64: Elide NarrowNode for Extend.

- compiler/src/org.graalvm.compiler.asm.aarch64.test/src/org/graalvm/compiler/asm/aarch64/test/TestProtectedAssembler.java
- compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64Assembler.java
- compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64MacroAssembler.java
- compiler/src/org.graalvm.compiler.core.aarch64.test/src/org/graalvm/compiler/core/aarch64/test/AArch64RotationTest.java
- compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64NodeMatchRules.java
- compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64ArithmeticOp.java
This patch optimizes the rotation by adding match rules like in C2:
match(Set dst (OrL (LShiftL src1 lshift) (URShiftL src2 rshift)))
match(Set dst (OrI (LShiftI src1 lshift) (URShiftI src2 rshift)))
match(Set dst (AddL (LShiftL src1 lshift) (URShiftL src2 rshift)))
match(Set dst (AddI (LShiftI src1 lshift) (URShiftI src2 rshift)))
match(Set dst (OrL (LShiftL src shift) (URShiftL src (SubI 64 shift))))
match(Set dst (OrL (LShiftL src shift) (URShiftL src (SubI 0 shift))))
match(Set dst (OrI (LShiftI src shift) (URShiftI src (SubI 32 shift))))
match(Set dst (OrI (LShiftI src shift) (URShiftI src (SubI 0 shift))))
match(Set dst (OrL (URShiftL src shift) (LShiftL src (SubI 64 shift))))
match(Set dst (OrL (URShiftL src shift) (LShiftL src (SubI 0 shift))))
match(Set dst (OrI (URShiftI src …
> AArch64: Match rules for rotations.

- compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64MacroAssembler.java
- compiler/src/org.graalvm.compiler.core.aarch64.test/src/org/graalvm/compiler/core/aarch64/test/AArch64BitwiseLogicalNotTest.java
- compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64NodeMatchRules.java
- compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64ArithmeticOp.java
This patch combines bitwise not with logical operations by
adding match rules for AArch64.
It tries to optimize operations like:
mvn w0, w2
and w0, w3, w0
to: bic w0, w3, w2
And it also optimizes:
eor x0, x2, x3
mvn x0, x0
to: eon x0, x2, x3
Change-Id: I535ec70472bfca0fe087cbdeab7daeb2c17ef947
> AArch64: Merge bitwise not into logical operations.

- truffle/src/com.oracle.truffle.api.dsl/src/com/oracle/truffle/api/dsl/Cached.java
This should fix the formatting of the third example. Currently, it looks like this:
> Use <pre/> instead of <code/> for example snippet

- truffle/src/com.oracle.truffle.sl/src/com/oracle/truffle/sl/nodes/SLRootNode.java
`isCloningAllowed` can be set via `setCloningAllowed(boolean)` and "escapes" the node in `isCloningAllowed()`. To be able to use `@CompilationFinal`, an assumption is needed (see https://github.com/oracle/graal/pull/1458). However, it might be good enough to remove `@CompilationFinal` from `isCloningAllowed`, at least it's correct.
/cc @chumer
> `isCloningAllowed` should not be @CompilationFinal

- truffle/docs/Optimizing.md
Are we transitioning all these options over to `--engine`? Why don't some of them have `--engine` equivalents? I've only transitioned the documentation that I wrote here - there are more examples over the code base. Should we get on and move to the new style options everywhere and start to warn when people use the old ones? I'd rather one way to do it.
Related to https://github.com/oracle/truffleruby/pull/1863.
https://github.com/Shopify/truffleruby/issues/1
> Transition --engine options in the Truffle optimization documentation

- compiler/src/jdk.tools.jaotc/src/jdk/tools/jaotc/MetadataBuilder.java
Because not all versions of the JDK have the field aot_metadata._nul_chk_table_begin, you do not always
want to generate this field depending on the target JDK's version. This difference is taken care of by
HotSpotGraalServices which has different implementations based on the target JDK's version. The
HotSpotGraalServices.getImplicitExceptionBytes returns null in case the field does not exist.
Additionally, harmonize how exceptionBytes is generated with the other variables.
This change was previously discussed in the graal-dev mailing list (https://mail.openjdk.java.net/pipermail/graal-dev/2020-January/005935.html)
> Explain why implicitExceptionBytes may be null

- compiler/src/org.graalvm.compiler.printer/src/org/graalvm/compiler/printer/GraalDebugHandlersFactory.java
According to my inspections: The modified code invokes node.toString, though this is wasted effort when debug logs are not enabled.
This is a direct violation of the policy laid out in https://github.com/oracle/graal/blob/a9db7dd44c3a6a37f6805bc93e7c366a201d2e9a/compiler/src/org.graalvm.compiler.core.test/src/org/graalvm/compiler/core/test/VerifyDebugUsage.java . However, the checker misses this code because of the indirection. It is, however, caught by our Yogo tool, which can search for patterns in a way that does not care about indirection. 
I unfortunately did not see an easy fix other than the explicit if-check.
Thanks to @thomaswue for directing us to VerifyDebugUsage.
> Fixing debug usage performance defect in GraalDebugHandlersFactory

- substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/DefaultOptionHandler.java
The `native-image --version` command currently prints:
```
GraalVM Version 19.3.1 CE
```
Given that the Graal VM ships in more than one variant of Java version (i.e. Java 8 and Java 11) and given that we have noticed there can be considerable difference in behaviour of native image generation depending on which variant is used, it is going to be useful to print out, in that `native-image --version` output, the Java version on which that Graal VM is based on.
This has been asked in a couple of places:
https://github.com/oracle/graal/issues/1911#issuecomment-565874506
https://github.com/quarkusio/quarkus/issues/6162
The commit here enhances the `native-image --version` output to even include the Java version. With this change, the output should look something like:
```
GraalVM Version …
```
> Print Java version in the output of "native-image --version" command

- substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/AlignedHeapChunk.java
- substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/DiscoverableReferenceProcessing.java
- substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/GCImpl.java
- substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/GreyObjectsWalker.java
- substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/GreyToBlackObjRefVisitor.java
- substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/HeapChunk.java
- substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/HeapChunkProvider.java
- substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/HeapImpl.java
- substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/HeapOptions.java
- substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/HeapPolicy.java
- substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/HeapPolicyOptions.java
- substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/HeapVerifierImpl.java
- substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/OldGeneration.java
- substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/Space.java
- substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/ThreadLocalAllocation.java
- substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/ThreadLocalMTWalker.java
- substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/UnalignedHeapChunk.java
- substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/YoungGeneration.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/heap/DiscoverableReference.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/heap/InstanceReferenceMapDecoder.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/heap/ObjectReferenceVisitor.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/hub/InteriorObjRefWalker.java
This patch will use the multi-survivors for SVM GC to reduce the frequency of full GC.
In the micro benchmark it could reduce the frequently of full GC(the full GC times could change from ~17/260 to ~9/250)
And in the real workload in Alibaba, it could also reduce the frequency of full GC(the full GC times could change from ~30/100 to ~1/200)
> [SVM GC] Add Survivor Space to SVM GC

- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JNIRegistrationJavaNet.java
8236925: (dc) Upgrade DatagramChannel socket adaptor to extend MulticastSocket
Prior to JDK-8236925 the constructor was no-arg. After, it takes an
argument of type java.net.DatagramSocketImpl.
> Account for JDK-8236925 changes

- sulong/tests/com.oracle.truffle.llvm.tests.llirtestgen/src/com/oracle/truffle/llvm/tests/llirtestgen/LLIRTestGen.java
Test bitcast_x86_fp80 is X86 only.
Add architecture check to LLIRTestGen.java to blacklist it.
> sulong: Don't create bitcast_x86_fp80 test on AArch64

- sulong/mx.sulong/suite.py
- sulong/tests/com.oracle.truffle.llvm.tests.sulongavx.native/avx/intrinsics/compare.c
- sulong/tests/com.oracle.truffle.llvm.tests.sulongavx.native/avx/intrinsics/movemask.c
Move the c/intrinsics/ AVX tests into AVX.
Ensure the AVX tests only run on AMD64.
> sulong: Don't run AVX intrinsic tests on non X86 platforms

- sulong/tests/com.oracle.truffle.llvm.tests.libc.native/libc/getchar/getchar.c
On AArch64, chars are unsigned by default.
The test libc/getchar/getchar requires "c" to be signed, otherwise
an infinite loop will occur. Switch to int (signed).
> sulong: test libc/getchar/getchar should use int

- sulong/mx.sulong/suite.py
- sulong/tests/com.oracle.truffle.llvm.tests.llirtestgen.generated/Makefile
- sulong/tests/com.oracle.truffle.llvm.tests.llirtestgen/src/com/oracle/truffle/llvm/tests/llirtestgen/LLIRTestGen.java
- sulong/tests/com.oracle.truffle.llvm.tests/src/com/oracle/truffle/llvm/tests/Platform.java
- sulong/tests/com.oracle.truffle.llvm.tests/src/com/oracle/truffle/llvm/tests/SulongSuite.java
- sulong/tests/com.oracle.truffle.llvm.tests/src/com/oracle/truffle/llvm/tests/bitcodeformat/BitcodeFormatTest.java
- sulong/tests/com.oracle.truffle.llvm.tests/src/com/oracle/truffle/llvm/tests/interop/LLVMInteropTest.java
Improve OS/Arch detection in tests. Then blacklist all failing AArch64 tests.
I wanted to use the new platform class in lirtestgen, but mx gate checks complained that you can't share the classes across different packages.
Once this and https://github.com/oracle/graal/pull/2173 is merged, then SulongSuite will fully pass on AArch64 Linux.
(I'm also assuming this comment doesn't end up in the final commit message)
> Sulong: Blacklist failing AArch64 tests

- substratevm/src/com.oracle.svm.core.graal.llvm/src/com/oracle/svm/core/graal/llvm/LLVMNativeImageCodeCache.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/LinkerInvocation.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/FeatureImpl.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageGenerator.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/LIRNativeImageCodeCache.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeBootImageViaCC.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageCodeCache.java
To allow post-processing of image binaries after linking it is sometimes necessary to know the symbols that correspond to the AOT-compiled methods. To make that accessible
`List<String> AfterImageWriteAccessImpl.getImageSymbols(boolean onlyGlobal)` is added.
> Make image symbols accessible after image write phase

- substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/PosixOSCommittedMemoryProviderFeature.java
- substratevm/src/com.oracle.svm.core.windows/src/com/oracle/svm/core/windows/WindowsOSCommittedMemoryProvider.java
- substratevm/src/com.oracle.svm.core.windows/src/com/oracle/svm/core/windows/WindowsStackOverflowSupport.java
- substratevm/src/com.oracle.svm.core.windows/src/com/oracle/svm/core/windows/WindowsVirtualMemoryProvider.java
- substratevm/src/com.oracle.svm.core.windows/src/com/oracle/svm/core/windows/headers/MemoryAPI.java
- substratevm/src/com.oracle.svm.core.windows/src/com/oracle/svm/core/windows/headers/WinBase.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/os/CommittedMemoryProvider.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/os/OSCommittedMemoryProvider.java
> Fix memory leak on Windows with isolates

- compiler/src/org.graalvm.compiler.core.test/src/org/graalvm/compiler/core/test/NegateCanonicalizationTest.java
- compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/calc/NegateNode.java
This patch fixes issue: #2220 
Negate a right shift with the max shift amount equals to unsigned right
shift.
As the final code, just take AArch64 for example:
asr x0, x2, #63
neg x0, x0
After this patch, generated assembly above can be optimized to below:
lsr x0, x2, #63
Change-Id: Ifd1c4f7885822b92798341f4728c887fddf7c654
> Canonicalize negate node to unsigned right shift.

- sulong/tests/com.oracle.truffle.llvm.tests/src/com/oracle/truffle/llvm/tests/bitcodeformat/BitcodeFormatTest.java
This is the final patch of my blacklisting series. Not planning on raising any more of these.
With this and my other patches, you should be able to successfully run the following on Aarch64:
`mx gate --tags "build,sulongBasic,sulongLL,llvm"`
> sulong: Blacklist failing bitcodeformat tests on AArch64

- sulong/tests/com.oracle.truffle.llvm.tests/src/com/oracle/truffle/llvm/tests/interop/DerefHandleTest.java
- sulong/tests/com.oracle.truffle.llvm.tests/src/com/oracle/truffle/llvm/tests/interop/TypedExportTest.java
- sulong/tests/com.oracle.truffle.llvm.tests/src/com/oracle/truffle/llvm/tests/interop/TypedInteropTest.java
More failing tests.
I've also written up the current status of AArch64 here: https://github.com/oracle/graal/issues/2276
> sulong: Blacklist failing interop tests on AArch64

- compiler/src/org.graalvm.compiler.replacements.test/src/org/graalvm/compiler/replacements/test/StringIndexOfTestBase.java
The Graal compiler unittest for String.indexOf was disabled for AArch64 before because of the bug JDK-8215792. Now the issue has been fixed and the fix has been backported. We should re-enable the test now.
> Re-enable unittest StringIndexOfTest for AArch64

- substratevm/src/com.oracle.svm.core.jdk14/src/com/oracle/svm/core/jdk14/Target_java_nio_DirectByteBuffer_JDK14OrLater.java
Fixes https://github.com/oracle/graal/issues/2312
The commit https://github.com/oracle/graal/commit/d1fcd57be077d4134eb6141beec128c1c36ccbb9#diff-5fe0fd2a6dd8dccadb3251613d4b1679L25 changed the package name for some substitutions from `com.oracle.svm.core.jdk` to `com.oracle.svm.core.heap`.  The `jdk14` project of substratevm refers to some of these classes and still uses the old package name causing the compilation failure.
The commit in this PR fixes the package name of the imports.
> Fix compilation error on JDK 15

- compiler/src/org.graalvm.compiler.hotspot.aarch64/src/org/graalvm/compiler/hotspot/aarch64/AArch64HotSpotBackendFactory.java
- compiler/src/org.graalvm.compiler.replacements.aarch64/src/org/graalvm/compiler/replacements/aarch64/AArch64GraphBuilderPlugins.java
- compiler/src/org.graalvm.compiler.replacements.amd64/src/org/graalvm/compiler/replacements/amd64/AMD64GraphBuilderPlugins.java
- compiler/src/org.graalvm.compiler.replacements/src/org/graalvm/compiler/replacements/TargetGraphBuilderPlugins.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageGenerator.java
AArch64 specific Math intrinsics are all disabled for svm. Some of them are
foreign calls that don't have the backend implementations for the related
IR on AArch64, like sin/cos/tan/exp/log/log10/pow. For these intrinsics,
the svm actually registers the original Math functions as the foreign call.
And it already has the optimized code sequences for the native methods in
StrictMath.
Howerever, other intrinsics that have the backend implementations are also
disabled, like rint/ceil/floor/fma. These ones can be registered for svm. So
this patch narrows the usage of the registerMathPlugin flag to make it only
disabe the foreign call intrinsics for AArch64.
Change-Id: I9c05b311cdbc56c34917fc321d44494b4b28eefd
> AArch64: Only disable foreign call math intrinsics for native image.

- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/ImageClassLoader.java
The commit in this PR fixes the issue noted in https://github.com/oracle/graal/issues/2287.
This commit changes the implementation of `annotationsAvailable` (private) method to return `true` only if there are any annotations available on the element. 
This commit also introduces a new `canLoadAnnotations` method which returns `true` if there were no errors like loading the annotations on an element (through the use of `AnnotatedElement#getAnnotations()`). This new method is used/necessary to retain the current semantics of how the `ImageClassLoader` decides to hold on to "hosted only classes" and "application classes" (i.e. these classes are held on to, even if they don't have any annotations, since those classes are then checked/used when there's a call on the `ImageClassLoader` to find …
> Fix 2287 - ImageClassLoader should only hold on to method/field that have annotations

- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/ImageClassLoader.java
When running on a large number of cores, within the native image class
loader many threads were being created. Futhermore, these threads were
not being shutdown until the end of execution.
Creating too many threads can cause the process to hang. This is because
each thread makes a call to read /dev/random to get a random seed.
However, it is possible for the system to run out of entropy if too many
threads are created in a short period of time, causing the read of
/dev/random to hang.
To resolve this, I limit the number of threads created by the native
image class loader and also ensure its ForkJoinPool is shutdown
promptly.
Change-Id: I225ba57ab89fee3b7aafcca9913f4ca676aec6bd
> Limit thread scaling and promptly shutdown pool

- compiler/mx.compiler/copyrights/oracle.copyright.regex.star
Currently the copyright regex for Arm part assumes that it has only one year recorded. Considering that we might update the AArch64 files and together with appending the latest modification year after the created year, we should make the copyright regex be matched for other valid pattern. Or it will report warning like "copyright that does not match the regex". This issue has happened when we execute "mx updategraalinopenjdk" and the copyright of one AArch64 file contains "Copyright (c) 2019, 2020, Arm Limited.".
Change-Id: I0a8dc283886150c07286dc4f5efe1e2f2c0f5656
> Update Arm copyright regex.

- compiler/src/org.graalvm.compiler.asm.aarch64.test/src/org/graalvm/compiler/asm/aarch64/test/TestProtectedAssembler.java
- compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64Assembler.java
- compiler/src/org.graalvm.compiler.core.aarch64.test/src/org/graalvm/compiler/core/aarch64/test/AArch64ArrayAddressTest.java
- compiler/src/org.graalvm.compiler.core.aarch64.test/src/org/graalvm/compiler/core/aarch64/test/AArch64MergeExtendWithAddSubTest.java
- compiler/src/org.graalvm.compiler.core.aarch64.test/src/org/graalvm/compiler/core/aarch64/test/AArch64MergeNarrowWithAddSubTest.java
- compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64NodeMatchRules.java
- compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64ArithmeticOp.java
This patch implements two types of match rules like C2.
1. Merge shift pair into add/sub.
2. Merge integral narrow into add/sub.
E.g. Below code is generated for `x + (((y << 56) >> 56) << 3)`
lsl x0, x3, #56
asr x0, x0, #56
add x0, x2, x0, lsl #3
After this patch, generated assembly above can be optimized to below:
add x0, x2, w3, sxtb #3
The test cases in this patch can show more details about those match
rules.
Change-Id: I71b392eefd990d2ad838afc06fccebb3438e467c
> AArch64: Merge shift pair and integral narrow into add/sub

- truffle/mx.truffle/mx_truffle.py
> Fix Truffle build when MX_ALT_OUTPUT_ROOT points outside the repo

- compiler/src/org.graalvm.compiler.replacements/src/org/graalvm/compiler/replacements/IntrinsicGraphBuilder.java
- substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/phases/SubstrateIntrinsicGraphBuilder.java
Fixes a problem introduced by the recent addition of ArrayCopyWithExceptionNode. When System.arraycopy is compiled as a root method, the IntrinsicGraphBuilder needs to properly link the control flow and also create the exception unwind nodes.
> Support WithExceptionNode in IntrinsicGraphBuilder

- substratevm/src/native-image-maven-plugin/src/main/java/com/oracle/substratevm/NativeImageMojo.java
This adds support for Maven Toolchains in the native-image-plugin.
Toolchains are the best practice for multi-module Maven projects where
each module may need to build with a different Java version.
For example, in a shared library project one might want to build most
modules using a conservatively low Java version such as 1.8, to allow
those libraries to be used by a larger population of developers. But
within the same multi-module project you might have a "leaf" module that
builds a standalone application and exports that application as an
executable using GraalVM native-image.
Toolchains allow each module to define the JDK flavour and version it
requires. Toolchains are supported by all the basic Maven plugins such
as maven-compiler-plugin, maven-surefire-plugin etc. Since the …
> Use Maven Toolchain in native-image-maven-plugin

- substratevm/DEBUGINFO.md
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/sources/ApplicationSourceCache.java
Correction to ensure app source roots are computed correctly relative to a jar or directory in the classpath.
> look for app sources in correct locations

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/c/libc/GLibc.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/c/libc/LibCBase.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/c/libc/MuslLibc.java
- substratevm/src/com.oracle.svm.truffle.nfi.posix/src/com/oracle/svm/truffle/nfi/posix/PosixTruffleNFIFeature.java
- substratevm/src/com.oracle.svm.truffle.nfi.posix/src/com/oracle/svm/truffle/nfi/posix/Target_com_oracle_truffle_nfi_impl_NFIContextLinux.java
Currently, isolated namespaces in a context are silently disregarded if compiled native-image uses musl-c.
This PR makes each libc return whether it supports isolated namespaces.
> Implement proper behaviour for POSIX Truffle NFI feature for different libc implementations.

- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/PECoffSymtabStruct.java
Use UTF_8 Charset when calculating length of Windows PE Coff symbols.
> [GR-22749]: Fix native-image buffer overflow on windows using Chinese Charset.

- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/SecurityServicesFeature.java
Fixes issue #2265 
```java
import java.security.SecureRandom;
import java.util.UUID;
import java.util.stream.Collectors;
import java.util.stream.IntStream;
public class Main {
public static void main(String[] args) {
System.out.println("Hello, UUID: " + UUID.randomUUID().toString());
IntStream intStream = new SecureRandom().ints(10, 0, 100);
System.out.println("Hello, secureRandom: " + intStream.boxed().collect(Collectors.toList()));
}
}
```
Fixes the issue #2265, tested with GraalVM substratevm,compiler,sdk HEAD 753b137, system: Windows 2019 Server, Visual Studio 2019, Windows 10 SDK.
```
SET JAVA_HOME=C:\Users\Administrator\source\graal\sdk\mxbuild\windows-amd64\GRAALVM_UNKNOWN_JAVA11\graalvm-unknown-java11-20.1.0-dev
SET GRAALVM_HOME=%JAVA_HOME%
set PATH=%GRAALVM_HOME%\bin;%PATH%
``` …
> Reinitialize random seed at runtime in Windows Native image, JDK 11

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/JavaMainWrapper.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/SubstrateExitHandlerFeature.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/SubstrateOptions.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JNIRegistrationJava.java
This PR provides a fix for #1592
Testing with
```java
public class Main {
public static void main(String[] args) {
Runtime.getRuntime().addShutdownHook(new Thread(() -> {
System.out.println("Shutdown happens!");
}));
try {
System.out.println("Zzzzzzz.....");
Thread.sleep(Long.MAX_VALUE);
} catch (InterruptedException e) {
System.out.println("Good morning!");
e.printStackTrace();
}
}
}
```
shows an image size increase of 48Kb when native-image --install-exit-handlers is used (from 6,802,048 bytes to 6,850,976 bytes)
> Provide java.lang.Terminator.setup() via --install-exit-handlers

- compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/GraalHotSpotVMConfig.java
- compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/GraalHotSpotVMConfigAccess.java
- compiler/src/org.graalvm.compiler.serviceprovider.jdk11/src/org/graalvm/compiler/serviceprovider/GraalServices.java
- compiler/src/org.graalvm.compiler.serviceprovider.jdk13/src/org/graalvm/compiler/serviceprovider/GraalServices.java
- compiler/src/org.graalvm.compiler.serviceprovider.jdk8/src/org/graalvm/compiler/serviceprovider/GraalServices.java
- compiler/src/org.graalvm.compiler.serviceprovider/src/org/graalvm/compiler/serviceprovider/GraalServices.java
Instead of conditionalizing flag AVX3Threshold on a JVMCI-versioned
JDK 11, expect it for any JDK >= 11
Closes #2402
> Expect AVX3Threshold on all JDKs >= 11

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/SubstrateOptions.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/heap/Target_java_lang_ref_Reference.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/Target_java_nio_Bits_JDK8.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/Target_jdk_internal_misc_VM.java
Do not inherit the maximum direct memory size from image generator, and provide same runtime option `-XX:MaxDirectMemorySize` as the Java HotSpot VM.
> Support MaxDirectMemorySize

- sulong/projects/com.oracle.truffle.llvm.parser.factories/src/com/oracle/truffle/llvm/parser/factories/BasicNodeFactory.java
- sulong/projects/com.oracle.truffle.llvm.runtime/src/com/oracle/truffle/llvm/runtime/nodes/intrinsics/c/LLVMCMathsIntrinsics.java
llvm spec; https://llvm.org/docs/LangRef.html#llvm-round-intrinsic
Referenced code from llvm ceil/floor. I found this missing as it was used by a Ruby library, [oj](https://github.com/ohler55/oj). 
https://github.com/Shopify/graal/issues/1
> Add LLVM Round Instrinsic

- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfLineSectionImpl.java
This fixes the problem found when using gdb 9.1 that was raised in issue #2431
The computation of the value for the prologue size field was incorrectly including that field in the byte count for remaining header + dir & file tables, meaning it was identifying a point 4 bytes into the line state machine instructions. With gdb 9.1 the debugger adds the prologue size to the prologue offset to identify the start of those instructions. With 8.3 it simply starts reading instructions from the point where the header + dir & file tables end which is why it went undetected.
> correct computation of prologue size

- sulong/projects/com.oracle.truffle.llvm.runtime/src/com/oracle/truffle/llvm/runtime/nodes/control/LLVMDispatchBasicBlockNode.java
AFAICT, there's no reason to use `#compilationConstant` here. `#partialEvaluationConstant` is to be preferred.
See https://github.com/oracle/graal/blob/8fb8fc502411b3c84308ff5cda4d6c1f775f3920/truffle/src/com.oracle.truffle.api/src/com/oracle/truffle/api/CompilerAsserts.java#L102-L113
> Tweak compiler assertion

- sdk/mx.sdk/mx_sdk_vm.py
- substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/MacroOptionHandler.java
- substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/NativeImage.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/ImageClassLoader.java
- substratevm/src/com.oracle.svm.util.jdk11/src/com/oracle/svm/util/ModuleSupport.java
- substratevm/src/com.oracle.svm.util/src/com/oracle/svm/util/ModuleSupport.java
- truffle/mx.truffle/macro-truffle.properties
This is a proper fix for the workaround added in https://github.com/oracle/graal/commit/4a5f6ae8341071ff9225c93ea82db643a102320a
> Allow user-defined image inclusion of builtin modules.

- compiler/src/org.graalvm.compiler.hotspot.aarch64/src/org/graalvm/compiler/hotspot/aarch64/AArch64HotSpotMove.java
On AArch64 if the VM jaotc is running in uses compressed oops with a
zero base it will not emit instructions to add/subtract the heap base
when compressing/decompressing oops. This causes a crash if the AOT'd
shared library is loaded into a VM with non-zero heap base.
Fix for JDK-8244164.
> AArch64: jaotc generates incorrect code for compressed OOPs with non-zero heap base

- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageGenerator.java
The compiler check can be ignored when ExitAfterRelocatableImageWrite is set and a CAP cache is used.
This not only applies to the LLVM backend.
Fix for #2476
> don't verify compiler if it won't be used

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/SubstrateOptions.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/c/libc/BionicLibc.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageGenerator.java
This PR fixes https://github.com/oracle/graal/issues/2466
Note that unlike MuslC, path to LibC isn't required here since all linking is done externally in Gluon Substrate using native Android toolchain.
> Add initial support for Bionic LibC

- substratevm/src/native-image-maven-plugin/src/main/java/com/oracle/substratevm/NativeImageMojo.java
Adds root cause to MojoExecutionException when an IllegalAccessError is thrown
> Prevent exception from being swallowed in maven-plugin

- .travis.yml
- substratevm/DEBUGINFO.md
- substratevm/mx.substratevm/mx_substratevm.py
- substratevm/mx.substratevm/testhello.py
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/SubstrateOptions.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/sources/JDKSourceCache.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/sources/SourceCache.java
- substratevm/src/com.oracle.svm.test/src/hello/Hello.java
This PR provides a test of the debuginfo capability on Linux. The patch provides an mx command.
$ mx debuginfotest
which compiles a sample program to a native image and scripts a run of the image under gdb, checking that breaks, backtraces, stepping and line listing work as expected.
n.b. for the command to work it requires gdb to be in the path.
The test succeeds on my Linux x86_64 and AArch64 boxes.
I have also modified the travis config to run this test automatically on Linux aarch64 and x86_64. I have no idea if that works or not (yet :-)
> Debug info test

- compiler/src/org.graalvm.compiler.asm.aarch64.test/src/org/graalvm/compiler/asm/aarch64/test/TestProtectedAssembler.java
- compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64Assembler.java
- compiler/src/org.graalvm.compiler.core.aarch64.test/src/org/graalvm/compiler/core/aarch64/test/AArch64VolatileAccessesTest.java
- compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64ArithmeticLIRGenerator.java
- compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64ReadReplacementPhase.java
- compiler/src/org.graalvm.compiler.core.amd64/src/org/graalvm/compiler/core/amd64/AMD64ArithmeticLIRGenerator.java
- compiler/src/org.graalvm.compiler.core.sparc/src/org/graalvm/compiler/core/sparc/SPARCArithmeticLIRGenerator.java
- compiler/src/org.graalvm.compiler.core.test/src/org/graalvm/compiler/core/test/LateMembarInsertionTest.java
- compiler/src/org.graalvm.compiler.hotspot.aarch64/src/org/graalvm/compiler/hotspot/aarch64/AArch64HotSpotLoweringProvider.java
- compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64Move.java
- compiler/src/org.graalvm.compiler.lir/src/org/graalvm/compiler/lir/gen/ArithmeticLIRGeneratorTool.java
- compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/memory/VolatileReadNode.java
- compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/memory/VolatileWriteNode.java
- compiler/src/org.graalvm.compiler.replacements.jdk9.test/src/org/graalvm/compiler/replacements/jdk9/test/VarHandleTest.java
- substratevm/src/com.oracle.svm.core.graal.aarch64/src/com/oracle/svm/core/graal/aarch64/SubstrateAArch64LoweringProvider.java
- substratevm/src/com.oracle.svm.core.graal.llvm/src/com/oracle/svm/core/graal/llvm/LLVMGenerator.java
This builds on top of https://github.com/oracle/graal/pull/1642 and implements volatile field accesses on aarch64 without explicit membar instructions.
> rework handling of volatile accesses on aarch64

- compiler/src/org.graalvm.compiler.core.aarch64.test/src/org/graalvm/compiler/core/aarch64/test/AArch64TestBitAndBranchTest.java
- compiler/src/org.graalvm.compiler.nodes.test/src/org/graalvm/compiler/nodes/test/IfNodeCanonicalizationTest2.java
- compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/IfNode.java
This patch here wants to canonicalize IfNode to ConditionalNode. We want to use "csel" to implement the conditional value selecting operation for more conditions like Math.min/max, instead of using "cmp + b.cond".
The trueSuccessor and falseSuccessor blocks of IfNode must meet the following conditions:
1. The nodes in block only contain a start and an end one except for the constant and parameter node.
2. The merge node only contains a phi member.
All the checking jobs must begin after the final schedule phase is finished, so that the
nodes in each block will not be changed anymore.
Change-Id: I4aa0ae791e05f34e6af3dd1da035e42a97815b9b
> Canonicalize IfNode to ConditionalNode for variable assignment.

- sulong/projects/com.oracle.truffle.llvm.parser/src/com/oracle/truffle/llvm/parser/LLVMParser.java
- sulong/projects/com.oracle.truffle.llvm.parser/src/com/oracle/truffle/llvm/parser/LazyToTruffleConverterImpl.java
- sulong/projects/com.oracle.truffle.llvm.parser/src/com/oracle/truffle/llvm/parser/listeners/FunctionMDOnly.java
- sulong/projects/com.oracle.truffle.llvm.parser/src/com/oracle/truffle/llvm/parser/listeners/Metadata.java
- sulong/projects/com.oracle.truffle.llvm.parser/src/com/oracle/truffle/llvm/parser/listeners/MetadataSubprogramOnly.java
- sulong/projects/com.oracle.truffle.llvm.parser/src/com/oracle/truffle/llvm/parser/model/functions/FunctionDefinition.java
- sulong/projects/com.oracle.truffle.llvm.parser/src/com/oracle/truffle/llvm/parser/model/functions/LazyFunctionParser.java
- sulong/projects/com.oracle.truffle.llvm.runtime/src/com/oracle/truffle/llvm/runtime/LLVMScope.java
- sulong/projects/com.oracle.truffle.llvm.runtime/src/com/oracle/truffle/llvm/runtime/options/SulongEngineOption.java
- sulong/tests/com.oracle.truffle.llvm.tests.interop.native/interop/membersTest.cpp
- sulong/tests/com.oracle.truffle.llvm.tests/src/com/oracle/truffle/llvm/tests/interop/CxxMembersTest.java
- sulong/tests/com.oracle.truffle.llvm.tests/src/com/oracle/truffle/llvm/tests/interop/InteropTestBase.java
- sulong/tests/com.oracle.truffle.llvm.tests/src/com/oracle/truffle/llvm/tests/interop/MembersTest.java
**add function name lookup for c++ functions**
When compiled with Clang++, C++ functions have only been resolved by their linkage name (i.e. when calling a C(++) function from javascript, one had to call them by their linkage names). Now, an additional lookup is done to also look for the C++ function name (such that calling a C++ function from javascript/... by its 'real' name is enabled).
> Add function name lookup for c++ functions.

- compiler/mx.compiler/suite.py
- compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64ArithmeticLIRGenerator.java
- compiler/src/org.graalvm.compiler.hotspot.jdk9.test/src/org/graalvm/compiler/hotspot/jdk9/test/MathDoubleFMATest.java
- compiler/src/org.graalvm.compiler.hotspot.jdk9.test/src/org/graalvm/compiler/hotspot/jdk9/test/MathFMAConstantInputTest.java
- compiler/src/org.graalvm.compiler.hotspot.jdk9.test/src/org/graalvm/compiler/hotspot/jdk9/test/MathFloatFMATest.java
Fix a minor typo in the Arithmetic LIR generator for AArch64 that
avoids assertion errors when they are enabled (using -ea flag).
> Fix assertion error for debug builds on AArch64

- compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64Assembler.java
- compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64MacroAssembler.java
- compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64SpeculativeBarrier.java
Use full system barrier to mitigate speculative exec.
Originally a CSDB was being used. However, this is not sufficient, as
this instruction must be used in conjuction with a data processing
instruction to mitigate speculative execution of memory accesses. For
now, have switched to using a full system barrier (DSB SY + ISB) to
ensure subsequent memory accesses are not executed speculatively.
> AArch64 Speculative Execution Mitigation Fix

- compiler/src/org.graalvm.compiler.hotspot.test/src/org/graalvm/compiler/hotspot/test/CheckGraalIntrinsics.java
- compiler/src/org.graalvm.compiler.jtt/src/org/graalvm/compiler/jtt/lang/Math_abs.java
- compiler/src/org.graalvm.compiler.replacements.aarch64/src/org/graalvm/compiler/replacements/aarch64/AArch64GraphBuilderPlugins.java
Math.abs for int/long type could be implemented with "cmp+cneg" on AArch64, which has a better performance than the current pattern:
```
tbnz w1, #31, label
mov w0, w1
...
label:
neg w0, w1
```
This patch adds the intrinsic support for the integer Math.abs to generate the `"AbsNode"` that will emit `"cmp+cneg"` finally.
Here is the main code of two micro benchmarks:
```
@Benchmark
public void jmhAbsInt() {
int res = 0;
for (int i = 0; i < NUM_INVOKES; ++i) {
int a = rand_int[(i) % NUM_RANDS];
res += Math.abs(a) * Math.abs(a);
}
res_int = res;
}
@Benchmark
public void jmhAbsLong() {
long res = 0;
for (int i = 0; i < NUM_INVOKES; ++i) {
long a = rand_long[i % NUM_RANDS];
res += Math.abs(a) * Math.abs(a);
}
res_long = res;
}
```
And the performance results on an A72 AArch64 machine:
Before: …
> AArch64: Add integer Math.abs intrinsics

- compiler/mx.compiler/suite.py
- compiler/src/org.graalvm.compiler.hotspot.test/src/org/graalvm/compiler/hotspot/test/CheckGraalIntrinsics.java
- compiler/src/org.graalvm.compiler.replacements.aarch64/src/org/graalvm/compiler/replacements/aarch64/AArch64GraphBuilderPlugins.java
- compiler/src/org.graalvm.compiler.replacements.jdk10.test/src/org/graalvm/compiler/replacements/jdk10/test/MathMultiplyHighTest.java
Math.multiplyHigh() could be implemented with a single instruction "smulh" on AArch64. This patch adds the intrinsic support for it when the JDK version is greater than 9.
Here is the main code of a JMH benchmark:
```
@Benchmark
public void jmhTimeMultiplyHigh() {
long res = 0;
for (int i = 0; i < 64; ++i) {
long a = rand_long[i % 1024];
long b = rand_long[(i + 1) % 1024];
res += Math.multiplyHigh(a, b);
}
res_long = res;
}
```
With this patch, it has about` 346% ~ 840%` performance improvement on different AArch64 machines.
Change-Id: I4758849d82895f4df708711af26ec8935949aafe
> AArch64: Add Math.multiplyHigh intrinsic on AArch64.

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/aarch64/AArch64CPUFeatureAccess.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/aarch64/AArch64LibCHelper.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageOptions.java
- substratevm/src/com.oracle.svm.native.libchelper/include/aarch64cpufeatures.h
- substratevm/src/com.oracle.svm.native.libchelper/src/cpuid.c
The fDMBATOMICS CPU feature was only ever implemented on a
prototype CPU and never made it into a production CPU.
See https://bugs.openjdk.java.net/browse/JDK-8242469
> Remove AArch64 feature fDMBATOMICS in SVM

- substratevm/src/com.oracle.svm.driver/resources/HelpExtra.txt
- substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/DefaultOptionHandler.java
* It can also be a combination of `<host>:<port>`, and host can also be `*`.
* Let the JDK itself validate and throw the appropiate the error if needed.
* Avoids duplicating JDK validation code.
> Remote attach options are not only ports #2532

- compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64ArithmeticLIRGenerator.java
- compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64NodeMatchRules.java
- compiler/src/org.graalvm.compiler.core.amd64/src/org/graalvm/compiler/core/amd64/AMD64ArithmeticLIRGenerator.java
- compiler/src/org.graalvm.compiler.core.amd64/src/org/graalvm/compiler/core/amd64/AMD64NodeMatchRules.java
- compiler/src/org.graalvm.compiler.core.match.processor/src/org/graalvm/compiler/core/match/processor/MatchProcessor.java
- compiler/src/org.graalvm.compiler.core/src/org/graalvm/compiler/core/gen/NodeLIRBuilder.java
- compiler/src/org.graalvm.compiler.core/src/org/graalvm/compiler/core/match/MatchContext.java
- compiler/src/org.graalvm.compiler.core/src/org/graalvm/compiler/core/match/MatchPattern.java
- compiler/src/org.graalvm.compiler.core/src/org/graalvm/compiler/core/match/MatchableNode.java
- compiler/src/org.graalvm.compiler.core/src/org/graalvm/compiler/core/match/SharedMatchValue.java
This patch fixes issue: https://github.com/oracle/graal/issues/2216
Unused constant load won't be deleted after match rules. As a result, it might generate redundant "mov/orr" instructions if the constants cannot be inlined to codes.
For example, the original codes:
lsr    w0, w0, #6
orr    w1, wzr, #0xfffff
and    w0, w0, w1
will be optimized to the following pattern by adding match rules:
orr    w1, wzr, #0xfffff
ubfx   w0, w0, #6, #20
However, the constant `"0xfffff"` is not deleted even though it will never be used. To fix it, this patch inserts a phase applied to LIRInstructions. It's used to eliminate the unused constant load ops before code generation. Although it is limited to constant load ops currently, it can also be extended to remove other kinds of unused instructions if …
> AArch64: Eliminate redundant constant load instructions.

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/OS.java
- substratevm/src/native-image-maven-plugin/src/main/java/com/oracle/substratevm/NativeImageMojo.java
> Fix native-image-maven-plugin for Windows

- truffle/src/com.oracle.truffle.api.dsl.test/src/com/oracle/truffle/api/dsl/test/ReachabilityTest.java
- truffle/src/com.oracle.truffle.dsl.processor/src/com/oracle/truffle/dsl/processor/model/SpecializationData.java
- truffle/src/com.oracle.truffle.dsl.processor/src/com/oracle/truffle/dsl/processor/parser/NodeParser.java
Fixes a behavior of the Truffle specialization DSL, where uncached specializations would be marked unreachable, even if they are reachable in the node generated with `@GenerateUncached`.
The logic implemented here is: if `@GenerateUncached` is present, an uncached specialization cannot be shadowed by a cached one.
> Fix reachability checks in the presence of @GenerateUncached.

- compiler/src/org.graalvm.compiler.core.test/src/org/graalvm/compiler/core/test/LateMembarInsertionTest.java
- compiler/src/org.graalvm.compiler.core.test/src/org/graalvm/compiler/core/test/VolatileReadEliminateWrongMemoryStateTest.java
- compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/memory/VolatileReadNode.java
- compiler/src/org.graalvm.compiler.replacements/src/org/graalvm/compiler/replacements/DefaultJavaLoweringProvider.java
This is bug https://bugs.openjdk.java.net/browse/JDK-8247832
VolatileReadNode.simplify() removes VolatileReadNodes that have no use other than Memory uses. The current logic updates the uses' Memory input with the VolatileReadNode's lastLocationAccess. That's broken as the LocationIdentity of the VolatileReadNode and the one of its uses likely differ. To make that optimization possible, I suggest the VolatileReadNode keeps track of the entire memory state in its lastLocationAccess input with a MemoryMapNode.
> Optimizing VolatileReadNode out causes wrong memory state to propagate

- .travis.yml
Trusty's EOL was April 2019
Related to #2608
> Travis: Update Ubuntu distribution

- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/ClassEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/DebugInfoBase.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/Range.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debuginfo/DebugInfoProvider.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfARangesSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfFrameSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfInfoSectionImpl.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageDebugInfoProvider.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/meta/HostedMethod.java
This is a proposed fix for issue #2587. It handles the case where deopt target methods are included in a native image. Compiled code for these methods is generated after the compiled code for normal compiled methods . In consequence, a class which contains deopt targets has code occupying two distinct code cache address ranges and code form different classes may be interleaved.
This is a problem because DWARF debug data (info, ranges, frame) must be generated as a sequence of entries associated with non-overlapping address ranges ordered low to high. So, a class containing deopt target methods must be processed twice, generating DWARF entries first for the normal methods and then for the deopt targets.
> Generate correct debug info for deoptimization target methods

- substratevm/mx.substratevm/mx_substratevm.py
- substratevm/src/com.oracle.svm.driver/resources/HelpExtra.txt
- substratevm/src/com.oracle.svm.driver/resources/HelpServer.txt
- substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/NativeImageServer.java
- substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/ServerOptionHandler.java
> Disable the image build server by default

- substratevm/src/org.graalvm.polyglot.nativeapi/src/org/graalvm/polyglot/nativeapi/PolyglotNativeAPI.java
It seems that the documentation value of the `poly_value_remove_array_element` method is copy of the `poly_value_set_array_element` method. That is a remove method but its comment is "Sets the value".
I found the relationship between the PolyglotNativeAPI class and org.graalvm.polyglot.Value class, so I got the correct comment of the `poly_value_remove_array_element` method from the `removeArrayElement` of the Value class.
> Fix the documentation in PolyglotNativeAPI

- compiler/src/org.graalvm.compiler.core.test/src/org/graalvm/compiler/core/test/VolatileAccessReadEliminationTest.java
- compiler/src/org.graalvm.compiler.virtual/src/org/graalvm/compiler/virtual/phases/ea/PEReadEliminationClosure.java
The following sequence:
v1 = Read of field
v2 = Unsafe volatile read
v3 = Read of field
// use of v1 & v3
is erroneously transformed to:
v1 = Read of field
v2 = Unsafe volatile read
// use of v1 only
by PEReadEliminationClosure
that is first and last reads of field are commoned.
> Reads around unsafe volatile read should not be commoned

- .travis.yml
Downloads labs OpenJDK 11 instead of using the one provided by travis and tests debuginfo both on arm64 and amd64
> Test debuginfo on JDK 11 on both arm64 and amd64

- substratevm/DEBUGINFO.md
- substratevm/mx.substratevm/mx_substratevm.py
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/ClassEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/DebugInfoBase.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/FileEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/Range.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debuginfo/DebugInfoProvider.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfAbbrevSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfDebugInfo.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfInfoSectionImpl.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageDebugInfoProvider.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/sources/SourceManager.java
This PR adds the DW_AT_comp_dir attribute to debug info, making it
point to the appropriate source file cache. This removes the need of
using `set directores sources/jdk:sources/graal:sources/src` in gdb.
At the moment there are 3 directories that might contain sources:
1. `sources/jdk`
2. `sources/graal`
3. `sources/src`
This patch detects the corresponding path for each compilation unit and adds it to the `DW_AT_comp_dir` attribute.
For instance for `java.base/java/lang/Shutdown.java` it sets `DW_AT_comp_dir` to `sources/jdk`, and for `com/oracle/svm/core/RegisterDumper.java` it sets it to `sources/graal`.
> Add compilation directory to debug info

- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfAbbrevSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfDebugInfo.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfInfoSectionImpl.java
This patch fixes issue #2697. It was tested by applying it on top of the patch for #2695 where it resolved the gdb 7.11 crash that is stopping that latter patch pass the debuginfotest gate. The fix allows for two variants of the info Compile Unit record for a top level compiled method, one with a stmt_list and one without. The latter  is used when there are no line records associated with a method.
> Omit stmt_list from CU info record when it has no associated line records

- compiler/src/org.graalvm.compiler.replacements.test/src/org/graalvm/compiler/replacements/test/UnsafeSubstitutionsTest.java
Running this test on AArch64 with -XX:-UseCompressedOops crashes the VM
with a SIGBUS. This is caused by a call to unsafePutObjectVolatile with
a non-64-bit-aligned offset (12). The VM should throw an exception here
rather than crash, and that needs to be fixed separately (it's a variant
of JDK-8246051), but we should also fix the test to use the offset of
the correct field.
> UnsafeSubstitutionsTest stores object to int field

- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/c/codegen/CCompilerInvoker.java
Having a directory called gcc/ in your search path will cause
native image to error.
Instead, native image should just ignore directories.
> SVM: Ignore directories when searching for default GCC

- compiler/src/org.graalvm.compiler.replacements.aarch64/src/org/graalvm/compiler/replacements/aarch64/AArch64GraphBuilderPlugins.java
- compiler/src/org.graalvm.compiler.replacements.amd64/src/org/graalvm/compiler/replacements/amd64/AMD64GraphBuilderPlugins.java
Intrinsics replace the bytewise read/write operations by necessary word sized chunks while performing unaligned memory accesses using the unsafe API. Covers char, short, int and long types.
**Microbenchmarking results:**
Relevant snippet of the microbenchmark is:
```
@Benchmark
public void jmhTimeUnsafeGetPutInt() {
int res = 0;
int pos;
for (int i = 0; i < NUM_INVOKES; ++i) {
pos = (i * intSize);
res += unsafe.getIntUnaligned(intArr, arrBaseOffset + pos + 1);
unsafe.putIntUnaligned(intArr, arrBaseOffset + pos + 1, res);
}
res_int = res;
}
```
Performance results on an A72 AArch64 machine are:
Before:
```
Benchmark                 Mode  Cnt     Score   Error  Units
jmhTimeUnsafeGetPutChar   avgt   10   367.850 ± 0.058  ns/op
jmhTimeUnsafeGetPutShort  avgt   10   321.127 ± 1.524  ns/op …
```
> Add intrinsics for get/put unsafe unaligned methods on AArch64

- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageDebugInfoProvider.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/sources/SourceManager.java
This patch fixes issue  #2693. It ensures that the NativeImageDebugInfoProvider hands out consistent source file names and class names when providing info about types compiled into a native image.
> Enforce consistent lookup of class and file names

- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageGenerator.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/c/CAnnotationProcessor.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/c/CAnnotationProcessorCache.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/c/NativeLibraries.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/c/codegen/QueryCodeWriter.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/c/info/InfoTreeVisitor.java
* Added `ExitAfterQueryCodeGeneration` native-image argument (output query code for target platform without executing it)
* Added `QueryCodeDir` native-image argument (directory where query code for target platform should be output)
* Split query code function and main
* Output which value is missing from CAP cache if CAP cache is corrupted or isn't up to date.
> CAP cache improvements

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/Target_java_time_zone_ZoneRules.java
Closes #2637 
* Before this patch, the image would contain zone rules cache from the JVM computing the image.
* Side effects here, such as class or source cache lookups, were affecting its contents and leading to error when writing image.
* With this change, we guarantee that the zone rules cache in the image is a brand new instance, separate from the one in the JVM computing the image.
> Keep image zone rules cache separate #2637

- substratevm/mx.substratevm/mx_substratevm.py
- substratevm/mx.substratevm/testhello.py
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/ClassEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/DebugInfoBase.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/FileEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/Range.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/StringTable.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfInfoSectionImpl.java
Since inlined methods may be defined in a different file than the one
defining a compiled method, the cache paths of all the source files
contributing code to the compiled method need to be set as the
compilation directory to make gdb work.
E.g. If:
1. `foo` invokes `bar` and `baz`
2. `bar` and `baz` get inlined in `foo`
3. `foo`'s source file is cached in `sources/src`
4. `bar`'s source file is cached in `sources/jdk`
5. `baz`'s source file is cached in `sources/graal`
then the compilation directory in `foo`'s compilation unit needs to be
set to `sources/src:sources/jdk:sources/graal`
> Fixes inlined code's cache paths for DWARF generation

- substratevm/src/com.oracle.svm.native.libchelper/src/cSunMiscSignal.c
Fixes https://github.com/oracle/graal/issues/2742
> [GR-25507] Use unnamed semaphore for cSunMiscSignal on Linux.

- .travis.yml
- compiler/mx.compiler/mx_compiler.py
- compiler/mx.compiler/suite.py
- sdk/mx.sdk/mx_sdk.py
- sdk/mx.sdk/mx_sdk_vm_impl.py
- sdk/mx.sdk/suite.py
- substratevm/mx.substratevm/mx_substratevm.py
- substratevm/mx.substratevm/suite.py
As of mx 5.270.0 (https://github.com/graalvm/mx/pull/221), mx projects can be built even outside a vcs repository.
This patch makes the necessary changes to allow graal to be built outside a vcs repository.
> Fix code that assumes suites are under a vcs repository

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JavaLangSubstitutions.java
This PR fixes #2421.
The "get" method of ClassValue  has the special property that racing threads must return the same value.
In the substitution this is ensured by using a ConcurrentHashMap. The problem is, that this map can't handle null values - but null is a valid response. Without the PR a NPE occurs if null is a response.
To support null we can use a dummy null. This dummy null can be store in the map.
The dummy null is also here to distinguish between "value was computed = null" and "value was not yet computed".
Because a simple `if (newValue == null) return null;` is not correct. 
If we would do this simple check, instead of using a dummy null, the next time the "get" method is called for the same type, "computeValue" would be called again. This is not correct.
> ClassValue substitution: Fix computeValue usage

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/code/InstalledCodeObserverSupport.java
This change gives `InstalledCodeObserver.Factory` the flexibility to make installing a `InstalledCodeObserver` optional.
> [GR-25560] Allow optional CodeObserver installation.

- .github/workflows/quarkus.yml
This PR adds a github action for building the latest graal and then using it to build and test the latest quarkus.
The goal of this github action is to assist the graalvm team in detecting changes that break quarkus.
> Github action for testing latest quarkus `master` with latest graal `master` 

- compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64Assembler.java
- compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64MacroAssembler.java
- compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64LIRGenerator.java
- compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64ControlFlow.java
Previously the AArch64 emitCompare was issuing many unnecessary loads.
In addition, some of the logic for using zr/sp within cmp, sub(s), and
add(s) needed to be fixed.
> Fixing AArch64 emitCompare and zr/sp issues

- substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/DefaultOptionHandler.java
Since graal is sensitive to JDK changes printing the build number along
with the java version, makes issue reporting and debugging a bit easier.
> Prints JDK build number along with  java.version

- substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/PosixSubstrateOperatingSystemMXBean.java
- substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/headers/Unistd.java
Replace getdtablesize with sysconf(_SC_OPEN_MAX)
Fix for #2812
> Replace getdtablesize with sysconf(_SC_OPEN_MAX)

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/LocalizationFeature.java
With JDK-8236548 in OpenJDK 11 an issue running
a generated native image may arise on programs using
TimeZone.getDisplayName(). With JDK-8236548 this might
become more noticeable since it now occurs on the
English locale too (no caching of English locales
happens any more).
Since all time zone data is included by default now,
also include the TimeZoneNames resource bundle by
default.
Closes: #2776
> Fix missing localization info issue for timezones

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/RandomNumbersFeature.java
As a fix for https://github.com/oracle/graal/issues/1610 the `RandomNumbersFeature` was introduced https://github.com/oracle/graal/commit/294c0b1ad97e5ef196165719f27e11a2087900f0. This feature however, right now, isn't automatically enabled. This means that users have to enable it themselves or frameworks have to enable it for them. Here's a recent issue reported in Quarkus https://github.com/quarkusio/quarkus/issues/11573.
Given that this is such a core feature/necessity of the Java random APIs, enabling this automatically, IMO, would be better.
The commit here adds the `@AutomaticFeature` to enable this.
> Mark RandomNumbersFeature as an @AutomaticFeature

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JavaNetSubstitutions.java
Fixes https://github.com/oracle/graal/issues/2058
Field java.net.URL.handlers has been annotated as @delete, but is still
reachable from method
java.net.URL.setURLStreamHandlerFactory(URLStreamHandlerFactory fac).
For example, it can be reached in Tomcat:
```
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported field java.net.URL.handlers is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Trace:
at parsing java.net.URL.setURLStreamHandlerFactory(URL.java:1140)
Call path from entry point to java.net.URL.setURLStreamHandlerFactory(URLStreamHandlerFactory):
at java.net.URL.setURLStreamHandlerFactory(URL.java:1132)
at …
```
> Field java.net.URL.handlers is deleted but still reachable

- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JNIRegistrationJava.java
`String.getBytes()` gets used through JNI, for example[1]. The commit in this PR registers it for JNI runtime access to avoid issues like the one reported in Quarkus here[2]
[1] https://github.com/openjdk/jdk/blob/master/src/java.base/share/native/libjava/jni_util.c#L831
[2] https://github.com/quarkusio/quarkus/issues/10682
> native-image - Register String.getBytes() for JNI access at runtime

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/RuntimeAssertionsSupport.java
Since all regular assertions options work as expected (see https://github.com/oracle/graal/pull/2859) this obsolete non-API option can be removed.
> [GR-26475] Remove obsolete hosted option RuntimeAssertionsFilter.

- vscode/graalvm/src/extension.ts
The section is called ‘env.osx’, not ‘env.mac’ on macOS. Add a case for Windows. Also, throw a better error when `env` is not found.
Please assign to @dbalek.
> Fix activation code of VSCode extension

- compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64Assembler.java
- compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64ArithmeticLIRGenerator.java
- compiler/src/org.graalvm.compiler.core.common/src/org/graalvm/compiler/core/common/type/ArithmeticOpTable.java
- compiler/src/org.graalvm.compiler.core.common/src/org/graalvm/compiler/core/common/type/FloatStamp.java
- compiler/src/org.graalvm.compiler.core.common/src/org/graalvm/compiler/core/common/type/IntegerStamp.java
- compiler/src/org.graalvm.compiler.core.test/src/org/graalvm/compiler/core/test/ReassociateAndCanonicalTest.java
- compiler/src/org.graalvm.compiler.hotspot.test/src/org/graalvm/compiler/hotspot/test/CheckGraalIntrinsics.java
- compiler/src/org.graalvm.compiler.jtt/src/org/graalvm/compiler/jtt/lang/Math_minMax.java
- compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64ArithmeticOp.java
- compiler/src/org.graalvm.compiler.lir/src/org/graalvm/compiler/lir/gen/ArithmeticLIRGeneratorTool.java
- compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/calc/BinaryArithmeticNode.java
- compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/calc/MaxNode.java
- compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/calc/MinMaxNode.java
- compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/calc/MinNode.java
- compiler/src/org.graalvm.compiler.replacements.aarch64/src/org/graalvm/compiler/replacements/aarch64/AArch64GraphBuilderPlugins.java
Emit `fmin/fmax` instructions when `Math.min()/Math.max()` function is called with single or double precision floating point values on AArch64. The existing mechanism emits `cmp+csel` combination for the integer variants of `Math.min()/Math.max()`.
Relevant snippet of the microbenchmark is shown below (only the double variant for `Math.max()` is shown for brevity).
```
@Benchmark
public void jmhTimeMaxDouble() {
double res = 0.0d;
for (int i = 0; i < NUM_INVOKES; ++i) {
double a = rand_double[i % NUM_RANDS];
double b = rand_double[(i + 1) % NUM_RANDS];
res += Math.max(a, b);
}
res_double = res;
}
```
Performance results on an A72 AArch64 machine
Before:
```
Benchmark         Mode  Cnt    Score   Error  Units
jmhTimeMaxDouble  avgt   15  288.019 ± 5.645  ns/op
jmhTimeMaxFloat   avgt   15 …
```
> Add intrinsics for floating point Math.min/Math.max on AArch64

- substratevm/mx.substratevm/testhello.py
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/ObjectFile.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/DebugInfoBase.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/Range.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/StringTable.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debuginfo/DebugInfoProvider.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/PECoff.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/PECoffMachine.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/PECoffObjectFile.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/cv/CVConstants.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/cv/CVDebugConstants.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/cv/CVDebugInfo.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/cv/CVFileTableRecord.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/cv/CVLineRecord.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/cv/CVLineRecordBuilder.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/cv/CVSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/cv/CVStringTableRecord.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/cv/CVSymbolRecord.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/cv/CVSymbolSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/cv/CVSymbolSubrecord.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/cv/CVSymbolSubsection.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/cv/CVSymbolSubsectionBuilder.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/cv/CVTypeConstants.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/cv/CVTypeRecord.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/cv/CVTypeSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/cv/CVUtil.java
- substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/FirstObjectTable.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/SubstrateOptions.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageDebugInfoProvider.java
This PR is for an initial implementation of debug support for Graal on Windows. At this stage I submit it more for discussion before I go much further down this road.
The patch allows Graal to emit CodeView 4 records into windows .obj files, which the windows linker then moves to PDB files at link time. Visual Studio can then open the executable, breakpoints can be set, and single-stepping, etc. will work.
Variables, and type information are not currently supported, and there is limited support for stack frames traceback.
I work closely with Andrew Dinn @adinn on debug support, so my code makes use of his previous work; I duplicate some of the shared classes from his PR here.
There are some differences in how I approach line information, but these are currently compile-time switches. For …
> Windows debug information prototype

- tools/src/org.graalvm.tools.api.lsp/src/org/graalvm/tools/api/lsp/LSPCommand.java
- tools/src/org.graalvm.tools.api.lsp/src/org/graalvm/tools/api/lsp/LSPExtension.java
- tools/src/org.graalvm.tools.api.lsp/src/org/graalvm/tools/api/lsp/LSPServer.java
- tools/src/org.graalvm.tools.api.lsp/src/org/graalvm/tools/api/lsp/LSPServerAccessor.java
- tools/src/org.graalvm.tools.lsp.test/src/org/graalvm/tools/lsp/test/server/LSPExtensionTest.java
- tools/src/org.graalvm.tools.lsp.test/src/org/graalvm/tools/lsp/test/server/LSPExtensionTestInstance.java
- tools/src/org.graalvm.tools.lsp.test/src/org/graalvm/tools/lsp/test/server/TruffleLSPTest.java
- tools/src/org.graalvm.tools.lsp/src/org/graalvm/tools/lsp/instrument/LSPInstrument.java
- tools/src/org.graalvm.tools.lsp/src/org/graalvm/tools/lsp/server/ContextAwareExecutor.java
- tools/src/org.graalvm.tools.lsp/src/org/graalvm/tools/lsp/server/LanguageServerImpl.java
- tools/src/org.graalvm.tools.lsp/src/org/graalvm/tools/lsp/server/TruffleAdapter.java
- tools/src/org.graalvm.tools.lsp/src/org/graalvm/tools/lsp/server/types/LanguageClient.java
- tools/src/org.graalvm.tools.lsp/src/org/graalvm/tools/lsp/server/types/LanguageServer.java
This adds the ability to extend the list of commands supported by the GraalLS through other instruments that provide the new `LSPExtension` service. See `LSPExtensionTestInstance` for an example.
Based on this change and #2906, we were able to implement Live Programming features on top of GraalLS and GraalVM's extension for VS Code.
Please assign to @dbalek and discuss! /cc @MartinBalin and @chumer
> [lsp] Add support for LSPExtensions

- vscode/graalvm/src/extension.ts
- vscode/graalvm/src/graalVMLanguageServer.ts
This PR lets GraalVM's extension for VS Code expose a public API that other extensions can use to register handlers for custom client notifications from the GraalLS backend. For this, extensions should depend on the GraalVM extension using `extensionDependencies` (see [here](https://code.visualstudio.com/api/references/vscode-api#extensions)).
Here's how the API can be used in a third-party extension:
```typescript
const graalVMExtension = vscode.extensions.getExtension('oracle-labs-graalvm.graalvm');
if (!graalVMExtension) {
return console.error('Unable to find GraalVM extension.');
}
graalVMExtension.exports.onClientNotification('my_notification', (response: any) => console.log(response)).then((result: boolean) => {
if (!result) {
console.error('Failed to register 'my_notification' …
```
> [vscode] Add public API to register LSP notification handlers

- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageGenerator.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/c/NativeLibraries.java
- substratevm/src/com.oracle.svm.truffle.nfi/src/com/oracle/svm/truffle/nfi/libffi/LibFFIHeaderDirectives.java
Currently we always statically link against `libffi.a` even if there is no need for it (no use of TruffleNFI in the image). This PR fixes the issue.
> Do not use CLibrary annotations from inactive @CContexts

- .github/workflows/quarkus.yml
Changes are picked from https://github.com/quarkusio/quarkus/pull/11599
Closes #2782
> CI: Use docker image for Elasticsearch ITs

- .github/workflows/quarkus.yml
Even if Quarkus 1.8.1 is the latest version, if 1.7.5 gets released after 1.8.1,
github will return 1.7.5 as the latest. Using maven's repo metadata to
get the latest version fixes this.
> [CI] Get Quarkus latest version from maven repo metadata

- compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64MacroAssembler.java
- compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64LIRGenerator.java
- compiler/src/org.graalvm.compiler.core.amd64/src/org/graalvm/compiler/core/amd64/AMD64LIRGenerator.java
- compiler/src/org.graalvm.compiler.core.sparc/src/org/graalvm/compiler/core/sparc/SPARCNodeMatchRules.java
- compiler/src/org.graalvm.compiler.hotspot.sparc/src/org/graalvm/compiler/hotspot/sparc/SPARCHotSpotLIRGenerator.java
- compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64AtomicMove.java
- compiler/src/org.graalvm.compiler.lir/src/org/graalvm/compiler/lir/gen/LIRGeneratorTool.java
- compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/java/LogicCompareAndSwapNode.java
- compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/java/ValueCompareAndSwapNode.java
- substratevm/src/com.oracle.svm.core.graal.llvm/src/com/oracle/svm/core/graal/llvm/LLVMGenerator.java
Graal always uses LDAXR+STLXR for Unsafe atomic operations. However this is not sufficient on AArch64 for the VM internal atomics that need the full barrier semantics (See [1]).
Another issue in Graal is for the java volatile read. Currently graal uses the LDR+DMB for volatile read, which might have issues when it is used together with STLR/STLXR (See [2]). And this has
already made several Renaissance benchmarks hang on some machines (See [3]).
This patch resolved these issues with the modifications:
1. Add a "conservative" field for "LocationIdentity" to decide whether to use the full semantic barriers for VM internal atomic operations.
2. Always use the optimized "ldaxr/stlxr" pattern for java atomics.
3. Temporarily insert a full barrier after STLXR for the normal atomics to make the …
> AArch64: Conditionally use barriers for atomic operations.

- compiler/src/org.graalvm.compiler.hotspot.aarch64/src/org/graalvm/compiler/hotspot/aarch64/AArch64HotSpotLIRGenerator.java
- compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/GraalHotSpotVMConfig.java
As discussed in https://bugs.openjdk.java.net/browse/JDK-8253015?focusedCommentId=14368932&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14368932, this is a graal part of the https://github.com/openjdk/jdk/pull/154
I'll mark the PR ready for review after the JDK patch will be integrated.
> Graal part of JDK-8253015: Aarch64: Move linux code out from generic CPU feature detection

- compiler/src/org.graalvm.compiler.replacements.amd64/src/org/graalvm/compiler/replacements/amd64/AMD64StringLatin1Substitutions.java
- compiler/src/org.graalvm.compiler.replacements.amd64/src/org/graalvm/compiler/replacements/amd64/AMD64StringUTF16Substitutions.java
JDK-8138732 renames HotSpotIntrinsicCandidate to IntrinsicCandidate and moves it to jdk.internal.vm.annotation.
It only seems to be referenced in comments. This change avoids the changes being overwritten the next time a "Update Graal" is done in the JDK.
See https://github.com/openjdk/jdk/pull/45
> Rename HotSpotIntrinsicCandidate to IntrinsicCandidate

- sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/hosted/RuntimeReflection.java
- substratevm/src/com.oracle.svm.agent/src/com/oracle/svm/agent/BreakpointInterceptor.java
- substratevm/src/com.oracle.svm.agent/src/com/oracle/svm/agent/NativeImageAgent.java
- substratevm/src/com.oracle.svm.agent/src/com/oracle/svm/agent/NativeImageAgentJNIHandleSet.java
- substratevm/src/com.oracle.svm.configure/src/com/oracle/svm/configure/ConfigurationTool.java
- substratevm/src/com.oracle.svm.configure/src/com/oracle/svm/configure/config/ConfigurationSet.java
- substratevm/src/com.oracle.svm.configure/src/com/oracle/svm/configure/config/SerializationConfiguration.java
- substratevm/src/com.oracle.svm.configure/src/com/oracle/svm/configure/trace/AccessAdvisor.java
- substratevm/src/com.oracle.svm.configure/src/com/oracle/svm/configure/trace/SerializationProcessor.java
- substratevm/src/com.oracle.svm.configure/src/com/oracle/svm/configure/trace/TraceProcessor.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/classinitialization/ClassInitializationInfo.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/configure/ConfigurationFiles.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/configure/ConfigurationParser.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/configure/SerializationConfigurationParser.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/configure/doc-files/SerializationConfigurationFilesHelp.txt
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JavaIOSubstitutions.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/Target_jdk_internal_reflect_AccessorGenerator.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/serialize/SerializationRegistry.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/util/json/JSONParser.java
- substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/NativeImage.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/FallbackFeature.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/classinitialization/ClassInitializationFeature.java
- substratevm/src/com.oracle.svm.jni/src/com/oracle/svm/jni/nativeapi/JNIFunctionPointerTypes.java
- substratevm/src/com.oracle.svm.jni/src/com/oracle/svm/jni/nativeapi/JNINativeInterface.java
- substratevm/src/com.oracle.svm.jvmtiagentbase/src/com/oracle/svm/jvmtiagentbase/JNIHandleSet.java
- substratevm/src/com.oracle.svm.jvmtiagentbase/src/com/oracle/svm/jvmtiagentbase/Support.java
- substratevm/src/com.oracle.svm.reflect/src/com/oracle/svm/reflect/serialize/SerializationSupport.java
- substratevm/src/com.oracle.svm.reflect/src/com/oracle/svm/reflect/serialize/hosted/SerializationFeature.java
- substratevm/src/com.oracle.svm.util/src/com/oracle/svm/util/SerializationChecksumCalculator.java
JDK's serialization/deserialization features are implemented by `java.io.java.io.ObjectInputStream.readObject` and `java.io.ObjectOutputStream.writeObject` APIs which are not supported by native image. This patch supports  these two APIs in native image.
- Support serialization API `Ljava/io/ObjectOutputStream;#writeObject(Ljava/lang/Object;)V`
- Support deserialization API `Ljava/io/ObjectInputStream;#readObject()Ljava/lang/Object;`
- Add a new configuration file `serialization-config.json` to provide serialization/deserialization target class information for 
- native-image at build time. The agent can intercept serialization/deserialization calls to store the serialization/deserialization target class information to the configuration file automatically.
- This patch doesn't depend on …
> Support JDK serialization/deserialization features

- compiler/src/org.graalvm.compiler.serviceprovider.jdk8/src/org/graalvm/compiler/serviceprovider/GraalServices.java
- substratevm/mx.substratevm/suite.py
- substratevm/src/com.oracle.svm.graal.test/src/com/oracle/svm/graal/test/IsolatedSpeculationLogEncodingNativeTest.java
- substratevm/src/com.oracle.svm.graal.test/src/com/oracle/svm/graal/test/IsolatedSpeculationLogEncodingTest.java
- substratevm/src/com.oracle.svm.graal/src/com/oracle/svm/graal/isolated/IsolatedCodeInstallBridge.java
- substratevm/src/com.oracle.svm.graal/src/com/oracle/svm/graal/isolated/IsolatedSpeculationLog.java
- substratevm/src/com.oracle.svm.graal/src/com/oracle/svm/graal/isolated/IsolatedSpeculationReasonEncoding.java
- substratevm/src/com.oracle.svm.graal/src/com/oracle/svm/graal/isolated/SpeculationReasonEncodingClone.java
Fixes #2933
Note that this PR fixes only the specific issue discussed in #2933, which is necessary to create a Mandrel build based on graalvm's master.  Even after merging this PR parts of GraalVM will fail to build using OpenJDK 11, for instance `mx --primary-suite-path substratevm --components='Native Image' build` will fail.
> Work around the absence of SpeculationReasonEncoding in OpenJDK11

- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JNIRegistrationAwt.java
> Fix UnsatisfiedLinkError when using ImageIO and jpeg

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/util/ClasspathUtils.java
- substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/NativeImage.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/AbstractNativeImageClassLoaderSupport.java
Closes #3071
* Ignore classpath entries that are not jars.
* A more robust check to see if a file is a zip/jar, is to check whether the magic is the correct one, rather than relying on the file extension.
> Ignore non zip/jar files in classpath

- truffle/docs/Languages.md
This PR adds [Enso](https://github.com/enso-org/enso) to the list of languages implemented using the Truffle framework.
> Add Enso to the list of truffle languages

- substratevm/mx.substratevm/mx_substratevm.py
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/SubstrateOptions.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageDebugInfoProvider.java
To improve the debugging experience with CE debuginfo we should not emit lineinfo for non-root SourceMappings (i.e. inlined code) for now. Only when we later add debuginfo that species PC ranges for inlined methods (with `DW_TAG_inlined_subroutine`) having lineinfo for inlined code will work reasonably well when stepping through code with GDB.
This change will improve the stepping through experience with the CE debuginfo
It gets rid of jumping in-and-out of `GenScavengeAllocationSnippets` while line-stepping through code.
> Omit DebugLineInfo originating from inlined methods for now

- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/agent/NativeImageBytecodeInstrumentationAgent.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/classinitialization/ClassInitializationFeature.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/classinitialization/ConfigurableClassInitialization.java
`-H:+TraceClassInitialization` can only print out trace information when class initialization error happens, but sometimes we still need to check the reason why a class is initialized without error.
This patch helps to achieve this goal. The specified class' initialization stack trace is printed out when the option is set.
> Print TraceClassInitialization without error

- substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/DefaultOptionHandler.java
- substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/NativeImage.java
This PR Replaces #3149.
It uses a more fine grained approach to exclude configuration from jars. A new option `--exclude-config` is added that takes as a value a comma separating a jar name and regular expression of resources to exclude from the given jar. Jar names can include path elements for situations where two jar names have the same name but different leading path.
Examples:
```
--exclude-config foo.jar,META-INF\/native-image\/.*.properties
--exclude-config bar.jar,META-INF\/native-image\/.*.json
--exclude-config foo/example.jar,META-INF\/native-image\/.*.json
--exclude-config bar/example.jar,META-INF\/native-image\/.*.json
```
The approach was agreed with @olpaw on [this slack chat](https://graalvm.slack.com/archives/CN9KSFB40/p1611664256033900).
> Add exclude-config option

- truffle/src/com.oracle.truffle.api.test/src/com/oracle/truffle/api/test/polyglot/ChildContextTest.java
- truffle/src/com.oracle.truffle.polyglot/src/com/oracle/truffle/polyglot/EngineAccessor.java
- truffle/src/com.oracle.truffle.polyglot/src/com/oracle/truffle/polyglot/PolyglotContextImpl.java
Fixes a bug in a child `TruffleContext` builder, where it required the instantiating language to be public. 
See the newly added test case, which fails with `language il is not installed` without the fixes implemented.
> Child context creation from an internal language

- substratevm/src/com.oracle.svm.configure/src/com/oracle/svm/configure/trace/SerializationProcessor.java
- substratevm/src/com.oracle.svm.configure/src/com/oracle/svm/configure/trace/TraceProcessor.java
Adds `advisor.shouldIgnore` to `SerializationProcessor` class (in line with other `native-image-agent` processors).
> Make sure that access filter applies to SerializationProcessor

- substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/typestate/PointsToStats.java
PrintPointsToStatistics has NullPointerException and thread safe issues, as described in the issue: https://github.com/oracle/graal/issues/3267
This PR can fix the issues.
> Make -H:+PrintPointsToStatistics option thread safe

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/thread/VMOperationControl.java
Fixes https://github.com/graalvm/mandrel/issues/225
https://github.com/oracle/graal/commit/c323ce752d3611c3b39e99e0875849d6d91cb879 results in the following error when building Mandrel:
```
Error: @RestrictHeapAccess warning: Restricted method: 'GCImpl$CollectionVMOperation.operate(NativeVMOperationData)' calls 'VMOperationControl$VMOpHistory$$Lambda$ca91da068fbe395c2178d758d4d0702d388c9790.get$Lambda()' that violates restriction NO_ALLOCATION.
[Path:
app//com.oracle.svm.core.genscavenge.GCImpl$CollectionVMOperation.operate(GCImpl.java:1110)
app//com.oracle.svm.core.genscavenge.GCImpl.access$200(GCImpl.java:97)
app//com.oracle.svm.core.genscavenge.GCImpl.collectOperation(GCImpl.java:174)
app//com.oracle.svm.core.genscavenge.ThreadLocalAllocation.disableAndFlushForAllThreads(ThreadLocalAllo …
```
> Avoid implicit allocation in VMOperationControl

- compiler/mx.compiler/mx_updategraalinopenjdk.py
JDK-8258407 refactored the build scripts.
Fix updategraalinopenjdk to take this into account.
> Fix updategraalinopenjdk for JDK17

- substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/DefaultOptionHandler.java
- substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/NativeImage.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/VMFeature.java
As discussed in https://github.com/graalvm/mandrel/issues/230 and https://github.com/oracle/graal/issues/3313 in 21.1-dev the `native-image` bash-launcher no longer prints a meaningful version.
This PR makes the bash launcher print:
```
native-image 21.1.0 Java 11 CE (Java Version 11.0.11+5-jvmci-21.1-b02)
```
for GraalVM CE and
```
native-image 21.1.0.0 Java 11 Mandrel Distribution (Java Version 11.0.10+9)
```
for Mandrel.
The corresponding **native** `native-image` binaries print:
```
GraalVM 21.1.0 Java 11 CE (Java Version 11.0.11+5-jvmci-21.1-b02)
```
for GraalVM CE and
```
GraalVM 21.1.0.0 Java 11 Mandrel Distribution (Java Version 11.0.10+9)
```
for Mandrel.
> Native image bash launcher version and vm config

- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/c/codegen/CCompilerInvoker.java
cl.exe prints its banner in system default language. In some languages, there is word "Microsoft" before "C/C++", in other languages there is "C/C++" before "Microsoft".
Fixes #3161.
> Fix for cl.exe check for non-english languages.

- substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/NativeImage.java
- substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/NativeImageServer.java
`NativeImage` may pass `-Xmx0` and `-Xms0` to start `NativeImageGeneratorRunner` in very rare cases, leading to JVM startup failure. Details are described in this issue: https://github.com/oracle/graal/issues/3255
This PR proposes a fix to avoid the possible failure.
> Fix possible "-Xmx0" issue

- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/ClassEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/DebugInfoBase.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/InterfaceClassEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/MethodEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/PrimaryEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/Range.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/StructureTypeEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debuginfo/DebugInfoProvider.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfARangesSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfInfoSectionImpl.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageDebugInfoProvider.java
As discussed in https://github.com/oracle/graal/pull/3290 this PR ensures that every debug `Range` is associated with a `MethodEntry`. This PR will enable us to continue working on https://github.com/oracle/graal/pull/2880 and associate the debug info for nested inline methods with `MethodEntry` instances.
> Associate debug Ranges with MethodEntries

- sdk/mx.sdk/mx_sdk_vm_impl.py
This patch allows GraalVM CE to build with OpenJDK 8 and the
--no-jlinking flag by not adding --upgrade-module-path and --add-exports
parameters when OpenJDK 8 is used.
> Allow GraalVM CE to build with OpenJDK 8 and --no-jlinking

- substratevm/src/com.oracle.svm.agent/src/com/oracle/svm/agent/BreakpointInterceptor.java
- substratevm/src/com.oracle.svm.agent/src/com/oracle/svm/agent/ClassLoaderDefineClassSupport.java
- substratevm/src/com.oracle.svm.agent/src/com/oracle/svm/agent/NativeImageAgent.java
- substratevm/src/com.oracle.svm.agent/src/com/oracle/svm/agent/NativeImageAgentJNIHandleSet.java
- substratevm/src/com.oracle.svm.configure/src/com/oracle/svm/configure/ConfigurationTool.java
- substratevm/src/com.oracle.svm.configure/src/com/oracle/svm/configure/config/ConfigurationDynamicClass.java
- substratevm/src/com.oracle.svm.configure/src/com/oracle/svm/configure/config/ConfigurationSet.java
- substratevm/src/com.oracle.svm.configure/src/com/oracle/svm/configure/config/DynamicClassesConfiguration.java
- substratevm/src/com.oracle.svm.configure/src/com/oracle/svm/configure/config/TypeConfiguration.java
- substratevm/src/com.oracle.svm.configure/src/com/oracle/svm/configure/json/JsonWriter.java
- substratevm/src/com.oracle.svm.configure/src/com/oracle/svm/configure/trace/DynamicClassesProcessor.java
- substratevm/src/com.oracle.svm.configure/src/com/oracle/svm/configure/trace/TraceProcessor.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/configure/ConfigurationFiles.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/configure/DynamicClassesConfigurationParser.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/hub/ClassForNameSupport.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/Target_java_lang_ClassLoader.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/util/JavaClassUtil.java
- substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/NativeImage.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/config/ConfigurationParserUtils.java
- substratevm/src/com.oracle.svm.jni/src/com/oracle/svm/jni/nativeapi/JNIFunctionPointerTypes.java
- substratevm/src/com.oracle.svm.jni/src/com/oracle/svm/jni/nativeapi/JNINativeInterface.java
- substratevm/src/com.oracle.svm.jvmtiagentbase/src/com/oracle/svm/jvmtiagentbase/Support.java
- substratevm/src/com.oracle.svm.reflect/src/com/oracle/svm/reflect/MultiClassLoaderReporter.java
- substratevm/src/com.oracle.svm.reflect/src/com/oracle/svm/reflect/dynamicclasses/hosted/DynamicClassesFeature.java
**Overview**
This patch supports `java.lang.ClassLoader.defineClass(String name, byte[] b, int off, int len)` based dynamic class loading in native image. It is separated from the previous PR (https://github.com/oracle/graal/pull/2323). 
The basic idea for supporting dynamic class loading is dumping classes generated at run time in a beforehand run with native-image-agent to a specified directory which is added to the classpath for building native image. 
This is implemented in 3 steps:
1. Intercept `java.lang.ClassLoader.postDefineClass` by native-image-agent to dump the dynamically generated class to file system.
2. User should make sure the generated classes' names are fixed through Hotspot version runtime and native-image version runtime.
3. Substitute relevant classes in SubstrateVM …
> Support dynamic class loading

- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/ResourcesFeature.java
Fixes #3467 by checking if jar is really a jar before scanning it.
> Only scan for resources in jar if really a jar #3467

- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/SecurityServicesFeature.java
> Trace removed security providers

- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/c/codegen/CCompilerInvoker.java
Parse clang version correctly even when it contains dashes.
> Parse clang version correctly even when it contains dashes

- .github/workflows/main.yml
- common.json
- vm/ci_includes/vm.hocon
Trying to fix https://github.com/oracle/graal/issues/3423
> Fix github actions failures.

- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/BasicProgbitsSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/ObjectFile.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/StringSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/ClassEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/DebugInfoBase.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/MethodEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/Range.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/StructureTypeEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debuginfo/DebugInfoProvider.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/ELFProgbitsSection.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/ELFUserDefinedSection.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfInfoSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/macho/MachORegularSection.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/macho/MachOUserDefinedSection.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/PECoffProgbitsSection.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/PECoffRelocationTable.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/PECoffUserDefinedSection.java
As of https://github.com/oracle/graal/pull/3304 we associate every range
with the `MethodEntry` of the method it was compiled from, and as a
result we know that a `MethodEntry` exists for each compiled method in
the image. Actually we create `MethodEntry`s even for methods that are
not compiled but are part of `ClassEntry` that describes a Class
reachable in the image.
For every range we generate a DIE (Debugging Information Entry) which
references another DIE that holds the specification of the method that
this range was generated from. So for every range we need a method DIE
containing information for the corresponding method.
Till now we have been generating these DIEs by traversing the primary
ranges of each ClassEntry. There are, however, subranges that might be
compiled from a …
> Use method entries instead of primary ranges for method DIE generation

- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/ServiceLoaderFeature.java
The service exclusion options documentation says it supports comma-separated arguments but it does not.
example command:
```
native-image \
-H:ServiceLoaderFeatureExcludeServices=package1.Service1,package2.Service2 \
-H:ServiceLoaderFeatureExcludeServices=package3.Service3 \
-H:ServiceLoaderFeatureExcludeServiceProviders=package1.impl.ServiceImpl1,package2.impl.ServiceImpl2 \
-H:ServiceLoaderFeatureExcludeServiceProviders=package3.impl.ServiceImpl3
```
This results in the exclusion sets to contain the entries without splitting the comma-separated values:
```
SERVICES_TO_SKIP = ["package1.Service1,package2.Service2", "package3.Service3"]
SERVICE_PROVIDERS_TO_SKIP = ["package1.impl.ServiceImpl1,package2.impl.ServiceImpl2", "package3.impl.ServiceImpl3"]
```
while they should be:
``` …
```
> ServiceLoaderFeature correctly supports comma-separated options

- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/snippets/SubstrateGraphBuilderPlugins.java
- substratevm/src/com.oracle.svm.test/src/META-INF/native-image/proxy-config.json
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/proxy/CustomInvocationHandler.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/proxy/CustomProxy.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/proxy/DummyClass.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/proxy/ProxyExceptionTest.java
The **neo4j-analytics** benchmark is not working due to a proxy initialization problem. 
Stacktrace is:
> java.lang.NoSuchMethodError: org.neo4j.kernel.impl.api.index.IndexingService$Monitor.awaitingPopulationOfRecoveredIndex(org.neo4j.storageengine.api.schema.StoreIndexDescriptor)
> 	at com.sun.proxy.$Proxy196.<clinit>(Unknown Source)
> The following benchmarks failed: neo4j-analytics
> 	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
> 	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:490)
> 	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1022)
> 	at …
> Fix: neo4j-analytics benchmark.

- substratevm/src/com.oracle.svm.reflect/src/com/oracle/svm/reflect/serialize/SerializationSupport.java
- substratevm/src/com.oracle.svm.reflect/src/com/oracle/svm/reflect/serialize/hosted/SerializationFeature.java
- substratevm/src/com.oracle.svm.test/src/META-INF/native-image/com.oracle.svm.test/native-image.properties
- substratevm/src/com.oracle.svm.test/src/META-INF/native-image/serialization-config.json
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/AbstractClassSerializationTest.java
There was a problem in native image when trying to serialize an abstract class. More about the problem can be found at https://github.com/oracle/graal/issues/3485.
Problem was that when building native image of a program class which constructor is used is set to be java.lang.Object. And in runtime, that class was found to be java.util.Dictionary. Chosen class is the first class in hierarchy that is not serializable. In the serialization map in project key was created using java.lang.Object in build time and using java.util.Dictionary in runtime. This problem occurs only for abstract classes. In build time target class constructor is being set to stubConstructor (created in file SerializationFeature, line ).
Problem was fixed by adding stubConstructor to SerializationSupport class in its …
> [GR-32241] Support serialization of abstract classed

- truffle/src/com.oracle.truffle.nfi.native/src/api.c
- truffle/src/com.oracle.truffle.nfi.native/src/closure.c
- truffle/src/com.oracle.truffle.nfi.native/src/internal.h
- truffle/src/com.oracle.truffle.nfi.native/src/jni.c
- truffle/src/com.oracle.truffle.nfi.native/src/lookup.c
- truffle/src/com.oracle.truffle.nfi.native/src/signature.c
- truffle/src/com.oracle.truffle.nfi.test.native/src/varargs.c
Properly casting pointers to integers (and vice-versa) needs casting to `intptr_t` as an intermediary type.
> Properly cast pointers to integers and vice-versa

- sdk/mx.sdk/suite.py
- sdk/src/org.graalvm.nativeimage/snapshot.sigtest
- sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/hosted/RuntimeSerialization.java
- sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/impl/RuntimeSerializationSupport.java
- substratevm/src/com.oracle.svm.configure/src/com/oracle/svm/configure/config/ConfigurationSet.java
- substratevm/src/com.oracle.svm.configure/src/com/oracle/svm/configure/config/SerializationConfiguration.java
- substratevm/src/com.oracle.svm.configure/src/com/oracle/svm/configure/config/SerializationConfigurationType.java
- substratevm/src/com.oracle.svm.configure/src/com/oracle/svm/configure/config/SignatureUtil.java
- substratevm/src/com.oracle.svm.configure/src/com/oracle/svm/configure/config/TypeConfiguration.java
- substratevm/src/com.oracle.svm.configure/src/com/oracle/svm/configure/trace/SerializationProcessor.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/configure/SerializationConfigurationParser.java
- substratevm/src/com.oracle.svm.reflect/src/com/oracle/svm/reflect/serialize/SerializationRegistry.java
- substratevm/src/com.oracle.svm.reflect/src/com/oracle/svm/reflect/serialize/SerializationSupport.java
- substratevm/src/com.oracle.svm.reflect/src/com/oracle/svm/reflect/serialize/hosted/SerializationFeature.java
- substratevm/src/com.oracle.svm.reflect/src/com/oracle/svm/reflect/serialize/hosted/package-info.java
- substratevm/src/com.oracle.svm.reflect/src/com/oracle/svm/reflect/target/Target_jdk_internal_reflect_AccessorGenerator.java
- substratevm/src/com.oracle.svm.test/src/META-INF/native-image/com.oracle.svm.test/native-image.properties
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/SerializationRegistrationTest.java
It is only possible to add serialization registrations from `serialization-config.json` files, these changes would add a `RuntimeSerialization` class which is accessible from within feature implementations so during image building, classes can be registered for serialization programatically using `RuntimeSerialization.register(YourClass.class)`.
This PR does 3 things:
* add programatical registration of serialization classes
* change the output of the serialization-config.json file to write out array classes as `org.example.ClassName[]` instead of `[org.example.ClassName;`
* support reading in the []-suffix syntax from the config file, so this also fixes https://github.com/oracle/graal/pull/3048
> [GR-32289] Programmatic serialization registration from inside features

- substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/api/HostVM.java
- substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/meta/AnalysisUniverse.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/HostedConfiguration.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageGenerator.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/SVMHost.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/analysis/Inflation.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/substitute/SubstitutionReflectivityFilter.java
- substratevm/src/com.oracle.svm.truffle.tck/src/com/oracle/svm/truffle/tck/WhiteListParser.java
It is not necessary to keep platform field in AnalysisUniverse class.
All usages of "platform" field are in com.oravle.svm.hosted package, and
it is irrelevent for general purpose Java program pointsto analysis.
> Move platform from AnalysisUniverse to SVMHost

- compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/extended/BoxNode.java
- compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/java/NewArrayNode.java
- compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/java/NewInstanceNode.java
- compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/spi/VirtualizerTool.java
- compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/util/GraphUtil.java
- compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/virtual/CommitAllocationNode.java
- compiler/src/org.graalvm.compiler.replacements/src/org/graalvm/compiler/replacements/nodes/ObjectClone.java
- compiler/src/org.graalvm.compiler.truffle.compiler/src/org/graalvm/compiler/truffle/compiler/nodes/frame/NewFrameNode.java
- compiler/src/org.graalvm.compiler.virtual/src/org/graalvm/compiler/virtual/phases/ea/VirtualizerToolImpl.java
This is proposed as a simple fix for the problem reported in issue #3620.
> ensure source position for new instance node is tracked

- substratevm/src/com.oracle.svm.jfr/src/com/oracle/svm/jfr/JfrManager.java
Fixes #3638
```
$ export JAVA_HOME=/home/karm/X/JDKs/graalvm-ce-java11-21.2.0/;export PATH=${JAVA_HOME}/bin:${PATH}
$ native-image --version
GraalVM 21.2.0 Java 11 CE (Java Version 11.0.12+6-jvmci-21.2-b08)
$ javac Main.java
$ native-image -H:+AllowVMInspection Main
$ java -XX:+FlightRecorder -XX:StartFlightRecording=maxsize=10M,filename=flight-java.jfr -Xlog:jfr Main
[0.279s][info][jfr] Flight Recorder initialized
[0.279s][info][jfr] Created repository /tmp/2021_07_30_15_11_00_295289
[0.309s][info][jfr] Creating thread sampler for java:20 ms, native 0 ms
[0.309s][info][jfr] Enrolling thread sampler
[0.309s][info][jfr] Enrolling thread sampler
[0.309s][info][jfr] Updated thread sampler for java: 20  ms, native 0 ms
[0.309s][info][jfr] Updated thread sampler for java: 20  ms, native 0 ms …
```
> Enables parsing units for maxsize, fixes units for delay in JfrManager.java

- substratevm/src/com.oracle.svm.jfr/src/com/oracle/svm/jfr/JfrEventSubstitution.java
- substratevm/src/com.oracle.svm.jfr/src/com/oracle/svm/jfr/JfrFeature.java
>  Fix reflection registration for JFR eventHandler fields

- espresso/src/com.oracle.truffle.espresso/src/com/oracle/truffle/espresso/classfile/ClassfileParser.java
- espresso/src/com.oracle.truffle.espresso/src/com/oracle/truffle/espresso/classfile/attributes/CodeAttribute.java
- espresso/src/com.oracle.truffle.espresso/src/com/oracle/truffle/espresso/impl/Method.java
- espresso/src/com.oracle.truffle.espresso/src/com/oracle/truffle/espresso/nodes/BytecodeNode.java
This PR makes `com.oracle.truffle.espresso.classfile.attributes.CodeAttribute` class fully immutable by moving mutable `code` field and appropriate methods to `com.oracle.truffle.espresso.impl.MethodVersion`.
> [Espresso] Make CodeAttribute fully immutable

- compiler/src/org.graalvm.compiler.truffle.compiler/src/org/graalvm/compiler/truffle/compiler/phases/inlining/DefaultInliningPolicy.java
- compiler/src/org.graalvm.compiler.truffle.compiler/src/org/graalvm/compiler/truffle/compiler/phases/inlining/InliningPolicy.java
- compiler/src/org.graalvm.compiler.truffle.compiler/src/org/graalvm/compiler/truffle/compiler/phases/inlining/TrivialOnlyInliningPolicy.java
- compiler/src/org.graalvm.compiler.truffle.compiler/src/org/graalvm/compiler/truffle/compiler/phases/inlining/TrivialOnlyPolicyProvider.java
- compiler/src/org.graalvm.compiler.truffle.options/src/org/graalvm/compiler/truffle/options/PolyglotCompilerOptions.java
- compiler/src/org.graalvm.compiler.truffle.test/src/org/graalvm/compiler/truffle/test/inlining/InlineOnlyTest.java
https://github.com/oracle/graal/issues/3492
Add an option to exclude a method `--engine.ExcludeInlining=bloooop`  
When the nodes are being checked in `DefaultInliningPolicy.java`, I added a check to see if the node is a method that was excluded. If it is, we avoid the inlining and `continue;`. 
I'm not sure if you'd like this change, but I've also added a new state, `CallNode.State.Excluded` to mark a node excluded. This makes the `--engine.TraceInlining` output more readable to the user (see the trace below). Without this change, the nodes would remain as `Expanded`. 
I'm testing this change locally using this Ruby script `test.rb`:
```ruby
def baz; end
def bar
baz
end
def foo 
bar
bar
bar
bar
baz
end
loop do
foo
end
```
And running
`jt ruby --experimental-options …
> Add option to exclude inlining, `--engine.ExcludeInlining=`

- regex/mx.regex/suite.py
Fixes https://github.com/oracle/graal/issues/3707
> Require `java.logging` from `com.oracle.truffle.regex`

- substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/PosixStat.java
- substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/headers/darwin/DarwinStat.java
This PR fixes #3667 by replacing stat64 symbols with stat symbols on Darwin.
> 3667: fix deprecated stat64 on Darwin

- substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/DefaultOptionHandler.java
- substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/NativeImage.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageGeneratorRunner.java
This PR adresses two problems related to `native-image` argument handling. Namely, it:
- fixes `NullPointerException` in cases when a class could not be found on the provided module path
- modifies argument handling so that when image name is combined with `--module` argument, the image name is not mistakenly interpreted as a class name
Currently, our main class resolving is done via:
https://github.com/oracle/graal/blob/8d70605a5ec73bb2f0f0aef9a84cf4d8d8816366/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageGeneratorRunner.java#L340
There is a catch block present for `ClassNotFoundException`, however, looking at the call chain, it is possible that control will reach `java.lang.Class.forName(Module, String)`, and by looking at the documentation for this method …
> [GR-33359] Fix image name argument parsing when combined with -m option

- substratevm/src/com.oracle.svm.driver/resources/Help.txt
- substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/DefaultOptionHandler.java
- substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/NativeImage.java
This PR introduces 2 changes to the Native Image Driver (and its argument parsing mechanism):
1) Adds support for `@argFile` command line option to the `native-image` tool. This command is implemented in the [same way as in `java` tool](https://docs.oracle.com/en/java/javase/14/docs/specs/man/java.html#java-command-line-argument-files) (on JDK9+).
2) Configures Native Image driver to pass all of the JVM arguments through argument file when invoking `NativeImageGeneratorRunner` on JDK9+. This enables usage of `classpath jar` workaround when user encounters a problem with long command line invocation. _IMO this change is a bugfix, and should as such be backported to all of the supported versions_.
Closes #3696.
> Use `@argFiles` to prevent issues with long command line invocations

- compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/InvokeWithExceptionNode.java
- substratevm/mx.substratevm/testhello.py
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/ClassEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/DebugInfoBase.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/MethodEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/PrimaryEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/Range.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debuginfo/DebugInfoProvider.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfAbbrevSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfDebugInfo.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfInfoSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfLineSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/cv/CVLineRecordBuilder.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageDebugInfoProvider.java
- substratevm/src/com.oracle.svm.test/src/hello/Hello.java
- substratevm/src/com.oracle.svm.test/src/hello/Target_hello_Hello_DefaultGreeter.java
This PR supersedes PR #2880 posted by @zakkak with one extra commit. With that extra change the PR should be ready for review and able to close issue #2701.
The PR supplies a small fix to the compiler which ensures that inline call source positions are propagated through to compilation results.
It also updates and corrects the debuginfotest driver script to correctly validate the processing of those inline source positions into debug info embedded in a native image.
> [GR-33516] Updated fix for inline debuginfo to fix issue 2701

- substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/reports/AnalysisReporter.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageGenerator.java
Refactor analysis result reporting code from `NativeImageGenerator` to a seperated class `AnalysisReporter` to improve its reusability.
> Extract analysis reporting to a seperated class

- substratevm/src/com.oracle.svm.truffle/src/com/oracle/svm/truffle/TruffleBaseFeature.java
- truffle/src/com.oracle.truffle.api.staticobject.test/src/com/oracle/truffle/api/staticobject/test/StaticTest.java
- truffle/src/com.oracle.truffle.api.staticobject/src/com/oracle/truffle/api/staticobject/ArrayBasedStaticShape.java
This PR is a pre-requisite for `LinkedKlass` caching during context pre-initialization (see https://github.com/oracle/graal/pull/3482). These offsets need to be re-computed so cached `LinkedKlass`es can be re-used on SVM.
> [Espresso] Re-compute StaticPropertyKind.Object offsets for SVM

- .github/workflows/main.yml
- compiler/src/org.graalvm.compiler.options.jdk11/src/org/graalvm/compiler/options/ModuleSupport.java
- sdk/mx.sdk/mx_sdk_vm_impl.py
- substratevm/ci_includes/gate.hocon
- substratevm/mx.substratevm/mx_substratevm.py
- substratevm/mx.substratevm/suite.py
- substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/MacroOptionHandler.java
- substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/NativeImage.java
@ivan-ristovic please have a look. This will eliminate the need for using `USE_NATIVE_IMAGE_JAVA_PLATFORM_MODULE_SYSTEM=true`.
Whenever native-images gets passed `-p` or `-m` (or the equivalent long forms) the driver will switch to running the image builder on modulepath.  Note that `USE_NATIVE_IMAGE_JAVA_PLATFORM_MODULE_SYSTEM=true` can still be used to force running the image builder on modulepath even when no `-p` or `-m` is used.
> [GR-33549] Run image-builder on modulepath when module options are used.

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/NashornSupport.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/Target_jdk_nashorn_api_scripting_NashornScriptEngineFactory.java
- substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/NativeImage.java
Add jdk.scripting.nashorn modules for module look-up on JDK 11.
Target_jdk_nashorn_api_scripting_ClassFilter substitution needs nashorn
target class loaded.
cc11ae1d1fad550424b1fdc0a6cf7e9d6815874a re-ordered arguments passed to
the native image generator. Add -XX:+UnlockExperimentalVMOptions before
actually using any one of those experimental options as that's needed
for some JVMs.
Add relevant modules to the upgraded module path list since for
non-jlinked-builds they are either not there or too old.
Closes #3778
> [GR-33796] Non-jlinked-build fixes for breakage after cc11ae1

- docs/reference-manual/native-image/Reports.md
- substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/reports/CallTreePrinter.java
This PR is a second version of the one proposed [here](https://github.com/oracle/graal/pull/2957).
It enhances the print analysis call tree to generate extra files that make it easy to import into graph databases such as Neo4j. It generates the following files:
* CSV file with all methods.
* CSV file with all virtual methods.
* CSV file with all direct call relationships.
* CSV file with all virtual call relationships.
* CSV file with all overriden by relationships.
* Neo4j Cypher that loads all the CSV files.
To load the data into Neo4j, just call:
```
cp ${REPORTS_DIR}/*.csv ${NEO_HOME}/import
time cat $(find ${REPORTS_DIR} -name '*.cypher') | ${NEO_HOME}/bin/cypher-shell -u neo4j -p xxx
```
By loading the method universe into a graph database, issues such as …
> Call tree analysis with graph databases (e.g. Neo4j) v2

- substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/phases/NoClassInitializationPlugin.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/classinitialization/EarlyClassInitializerAnalysis.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/lambda/LambdaProxyRenamingSubstitutionProcessor.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/phases/IntrinsifyMethodHandlesInvocationPlugin.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/substitute/UnsafeAutomaticSubstitutionProcessor.java
AnalysisClassInitializationPlugin is only used for standalone pointsto, so that there won't be acutal nodes emitted and the types are not get initialized at byte code parsing time.
> Prepare standalone pointsto with AnalysisClassInitializationPlugin

- regex/CHANGELOG.md
- regex/src/com.oracle.truffle.regex/src/com/oracle/truffle/regex/RegexOptions.java
- regex/src/com.oracle.truffle.regex/src/com/oracle/truffle/regex/tregex/nodes/TRegexExecutorNode.java
- regex/src/com.oracle.truffle.regex/src/com/oracle/truffle/regex/tregex/parser/flavors/RubyFlavorProcessor.java
- regex/src/com.oracle.truffle.regex/src/com/oracle/truffle/regex/tregex/string/Encodings.java
- regex/src/com.oracle.truffle.regex/src/com/oracle/truffle/regex/tregex/string/StringASCII.java
- regex/src/com.oracle.truffle.regex/src/com/oracle/truffle/regex/tregex/string/StringBufferASCII.java
This PR adds a new ASCII encoding to TRegex, which has half the range of valid values as Latin-1. If a guest language knows the regex consists only of ASCII characters, it can specify that when constructing a regex object.
TRegex already has a good mechanism to restrict the code point range for things like POSIX bracket expressions based on the regex's associated encoding. The new ASCII encoding hooks into that existing mechanism to further limit the set of code point ranges based on data the caller knows at regex creation time. Below is a table of the number of code point ranges for the set of POSIX bracket expressions, along with two non-POSIX bracket expressions that the Ruby language uses:
| POSIX Bracket Expr. | Full Unicode # of Ranges | LATIN-1 Range # of Ranges | ASCII # of …
> TRegex: Add ASCII encoding to reduce range of Unicode char sets to ASCII if match string is ASCII-only.

- regex/src/com.oracle.truffle.regex/src/com/oracle/truffle/regex/tregex/nodes/TRegexExecutorNode.java
This is a bug fix for #3806. It looks like I had amended a commit to add the assertion, but failed to force-push over my branch, so it never ended up being part of the PR. I've updated TruffleRuby to use Graal 4b94d2d384460319d02e5a1706d7fb4e4165bd6b with this patch applied and the TruffleRuby test suite passes.
Please feel free to apply the patch as part of another PR if that's easier.
> TRegex: Update assertion to allow usage of ASCII encoding.

- substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/NativeImage.java
NativeImage passes some arguments via the \@file feature of the
JDK launcher. When some arguments, separated by new lines, contain
whitespace *and* aren't properly quoted, the JDK launcher code fails
to parse the argument file and the native image generator class is
never launched.
Shell-quoting arguments before writing them to an \@argument file
avoids this issue.
Closes #3769
> Properly quote arguments passed via argument files

- compiler/mx.compiler/mx_compiler.py
- sdk/mx.sdk/mx_sdk_vm_impl.py
- substratevm/mx.substratevm/mx_substratevm.py
Building 'Native Image' should be enough to run the `mx debuginfotest` if no specific profile has been provided.
This change is meant to reduce the time spent on building `native-image` for `mx debuginfotest` when it is not already available.
> [GR-34028] Avoid building more components than necessary for running the debug info tests

- compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64MacroAssembler.java
- compiler/src/org.graalvm.compiler.core.aarch64.test/src/org/graalvm/compiler/core/aarch64/test/AArch64BitFieldTest.java
- compiler/src/org.graalvm.compiler.core.aarch64.test/src/org/graalvm/compiler/core/aarch64/test/AArch64NegateShiftTest.java
- compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64NodeMatchRules.java
- compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64ArithmeticOp.java
Add three node match rules to handle the three varieties of shift, together with capability to emit a combined negate instruction with shift.
> AArch64: Changes to combine shift and negate to a single instruction.

- substratevm/mx.substratevm/suite.py
LibGraal fails to build with upstream OpenJDK 11 due to it's dependency
on `HotSpotJVMCIRuntime.getCurrentJavaThread()` which has not been
backported to upstream OpenJDK 11. Preventing LibGraal from being build by
default enables us to build components of GraalVM that do not depend on
it, e.g., 'Native Image'.
> Don't build LibGraal component by default

- substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/reports/CallTreePrinter.java
- substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/reports/ReportUtils.java
FYI @cstancu a follow up to https://github.com/oracle/graal/pull/3128
During that PR I added symbolic links for the CSV files to make it easier to import them into graph dbs. However, amongst all the rebasing I somehow lost that commit. So, sending this PR to add this bit.
> Add call tree csv links for easier imports into graph db

- substratevm/src/com.oracle.svm.hosted.jdk11/src/com/oracle/svm/hosted/ModuleLayerFeature.java
- substratevm/src/com.oracle.svm.util/src/com/oracle/svm/util/ReflectionUtil.java
> [GR-34108] Extend boot module layer to include required modules

- .github/workflows/main.yml
- substratevm/mx.substratevm/testhello.py
Complementary to https://github.com/oracle/graal/pull/3967
> Replace jdk8 github gates with jdk17 ones

- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JNIRegistrationJava.java
More than one user in the Quarkus project has reported that they run into the following exception when building a native image for a Quarkus application:
```
java.lang.NoSuchMethodError: java.lang.String.<init>([B)V 
at com.oracle.svm.jni.functions.JNIFunctions$Support.getMethodID(JNIFunctions.java:1113) 
at com.oracle.svm.jni.functions.JNIFunctions$Support.getMethodID(JNIFunctions.java:1098) 
at com.oracle.svm.jni.functions.JNIFunctions.GetMethodID(JNIFunctions.java:411) 
at java.io.UnixFileSystem.canonicalize0(UnixFileSystem.java) 
at java.io.UnixFileSystem.canonicalize(UnixFileSystem.java:178) 
at java.io.File.getCanonicalPath(File.java:626) 
at java.io.File.getCanonicalFile(File.java:651) 
at sun.security.provider.FileInputStreamPool.getInputStream(FileInputStreamPool.java:84) 
at …
```
> Register String(byte[]) constructor for runtime JNI access

- docs/Publications.md
Hi all, I saw that in [this](https://www.graalvm.org/community/publications/) page that you all accept PRs to include research work done with GraalVM.
I'm sending this PR to include some work that I started during my internship at OracleLabs in the summer of 2019. Thanks!
I also noticed that the publications [page](https://www.graalvm.org/community/publications/) hasn't been updated in some time. Will it be updated again anytime soon with the contents of this README? I noticed that the 2020 papers don't show up, for example. Thanks again!
Also tagging @lukasstadler, who was involved in this work :-)
> Adding the "Towards a polyglot framework for factorized ML" paper

- java-benchmarks/mx.java-benchmarks/mx_java_benchmarks.py
- substratevm/src/com.oracle.svm.configure/src/com/oracle/svm/configure/trace/AccessAdvisor.java
- vm/mx.vm/mx_vm_benchmark.py
This PR is solving a problem with `finagle-chirper` and `finagle-http` benchmarks.
Exception:
> java.lang.ExceptionInInitializerError
> The following benchmarks failed: finagle-chirper
> 	at com.twitter.finagle.server.ListeningStackServer$$anon$1.<init>(ListeningStackServer.scala:41)
> 	at com.twitter.finagle.server.ListeningStackServer$class.serve(ListeningStackServer.scala:39)
> 	at com.twitter.finagle.Http$Server.superServe(Http.scala:670)
> 	at com.twitter.finagle.Http$Server.serve(Http.scala:683)
> 	at com.twitter.finagle.Http$.serve(Http.scala:690)
> 	at com.twitter.finagle.Server$class.serve(Server.scala:131)
> 	at com.twitter.finagle.Http$.serve(Http.scala:48)
> 	at com.twitter.finagle.Server$class.serve(Server.scala:135)
> 	at com.twitter.finagle.Http$.serve(Http.scala:48)
> 	at …
> Fix: finagle-chirper and finagle-http benchmarks on renaissance 0.13.0.

- substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/AbstractImageHeapLayouter.java
- substratevm/src/com.oracle.svm.core.windows/src/com/oracle/svm/core/windows/WindowsImageHeapProvider.java
- substratevm/src/com.oracle.svm.core.windows/src/com/oracle/svm/core/windows/WindowsUtils.java
- substratevm/src/com.oracle.svm.core.windows/src/com/oracle/svm/core/windows/WindowsVirtualMemoryProvider.java
- substratevm/src/com.oracle.svm.core.windows/src/com/oracle/svm/core/windows/headers/FileAPI.java
- substratevm/src/com.oracle.svm.core.windows/src/com/oracle/svm/core/windows/headers/LibC.java
- substratevm/src/com.oracle.svm.core.windows/src/com/oracle/svm/core/windows/headers/MemoryAPI.java
- substratevm/src/com.oracle.svm.core.windows/src/com/oracle/svm/core/windows/headers/WinBase.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/os/AbstractCopyingImageHeapProvider.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageViaCC.java
This PR adds a copy-on-write image heap provider for Windows.
A few high-level notes on implementation:
- New image heaps are provided by memory mapping views of the loaded image heap.
- In case of failure to map a new image heap, the implementation falls back to copying from memory as before.
- For memory mapping to work, the OS must have support for memory placeholders. This is checked at runtime as not all Windows versions have the necessary support.
- The use of memory placeholders is transparent to the rest of the system, i.e., it is completely encapsulated in `WindowsVirtualMemoryProvider` .
> [GR-21865] Introduce copy-on-write image heap provider on Windows.

- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/Range.java
This PR fixes an error introduced during refactoring of the debug types info code (GR-31277). Full method names used in log statements are supposed to list the method param type names in the signature. The are currently listing the method parameter names (which at present are empty strings).
> [GR-35274] Restore missing param type names in method signatures in debug log statements

- substratevm/mx.substratevm/mx_substratevm.py
- substratevm/src/com.oracle.svm.core.jdk11/src/com/oracle/svm/core/jdk11/Target_java_lang_Module_JDK11OrLater.java
- substratevm/src/com.oracle.svm.hosted.jdk11/src/com/oracle/svm/hosted/ModuleLayerFeature.java
- substratevm/src/com.oracle.svm.jfr/src/com/oracle/svm/jfr/JfrFeature.java
- substratevm/src/native-image-module-tests/hello.app/src/main/java/hello/Main.java
This PR implements runtime relations between modules by transferring hosted module relations to runtime.
Fixes #3911 and addresses #3935
> [GR-34444] Replicate hosted module relations in runtime boot module layer

- substratevm/mx.substratevm/testhello.py
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/Range.java
- substratevm/src/com.oracle.svm.test/src/hello/Hello.java
* Stops merging leaf subranges with non-leaf ones.
As we are generating line info only for leaf ranges, merging a leaf range with a non-leaf one results in not generating line info for the former (previously leaf) range.
* Substitutes or removes tests relying on standard library PrintStream.
**Note**: This PR is based on 4550c69898bf6c0eec11e4965f86b66b25396268 instead of `master` to avoid the AssertionError introduced by https://github.com/oracle/graal/commit/ee638aadb6201aa713e44c4865858a84f856d06e and reported in #4018 so that it can be tested without getting the AssertionError.
Closes: #4036
> [GR-35277] Fix merging of debug info subranges and make debuginfotest more resiliant to JDK changes

- .github/workflows/main.yml
- sulong/mx.sulong/suite.py
Looks like the update to CMake 3.22.0 broke the LLVM CMake build. Building libc++ and libc++abi individually still seems to work.
> Fix sulong build in github actions.

- substratevm/mx.substratevm/suite.py
4609007cba98c4d02738170401c55900b001c97f breaks builds with mx 5.310.0 due to
its dependency on
https://github.com/graalvm/mx/commit/2a364eec1736fb0c858703491bd30605526cb2ea
> Bump mx version for substratevm

- compiler/mx.compiler/suite.py
- substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/PosixStat.java
- substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/headers/darwin/DarwinStat.java
- substratevm/src/com.oracle.svm.truffle.nfi.posix/src/com/oracle/svm/truffle/nfi/posix/PosixTruffleNFIFeature.java
Looks like `fstat` and some other system calls don't have `$INODE64` suffix on aarch64 anymore, even if `_DARWIN_USE_64_BIT_INODE` is given, since they're only for a backward-compatible issue which only happens on Intel platform.
This PR is to fix the failure on darwin-aarch64.
<details>
<summary>Failed test</summary>
```
$ mx native-unittest --regex ImageInfoTest 
========================================================================================================================
GraalVM Native Image: Generating 'com.oracle.svm.junit.svmjunitrunner'...
========================================================================================================================
[1/7] Initializing...                                                                                   (18.4s @ …
```
> Fix fstat call in darwin-aarch64.

- sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/hosted/RuntimeSerialization.java
- sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/impl/RuntimeSerializationSupport.java
- substratevm/src/com.oracle.svm.configure/src/com/oracle/svm/configure/config/SerializationConfiguration.java
- substratevm/src/com.oracle.svm.reflect/src/com/oracle/svm/reflect/serialize/hosted/SerializationFeature.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/SerializationRegistrationTest.java
When a class is registered as serialization target, all its associated
classes are registered as well.
The associated classes are:
- Boxed type for primitive type
- All super classes that implements Serializable interface
- All fields' classes
Classes shall be excluded from registering:
- Not effective final classes. It could be the given class' any subclass
at runtime, so only register the base class is not sufficient. But to
automatically explore all subclasses and their associated classes could be
expensive. So such classes should be registered via configurations.
- Class with "writeObject" method. We can't automatically find out what
the customized serialization method does.
> [GR-35887] Register serialization with associated classes

- .github/workflows/main.yml
- substratevm/mx.substratevm/testhello.py
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/ClassEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/MethodEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/Range.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfInfoSectionImpl.java
- substratevm/src/com.oracle.svm.jni/src/com/oracle/svm/jni/JNIJavaCallTrampolines.java
- substratevm/src/com.oracle.svm.jni/src/com/oracle/svm/jni/JNIJavaCallWrappers.java
- substratevm/src/com.oracle.svm.jni/src/com/oracle/svm/jni/access/JNIAccessFeature.java
- substratevm/src/com.oracle.svm.jni/src/com/oracle/svm/jni/hosted/JNICallWrapperFeature.java
- substratevm/src/com.oracle.svm.jni/src/com/oracle/svm/jni/hosted/JNINativeCallWrapperSubstitutionProcessor.java
* Fix line numbers in debuginfotest (broke with https://github.com/oracle/graal/pull/4046/commits/cd0790a2dc2f9596cc401530b89bcffbf62e6d8d#diff-105ea9ecbf6b46cbee13172668e206702bfb7927851d2033614b06ce9cef6fabR140-R142)
* Don't create JNINativeCallWrapperMethods for JNICallTrampolineMethods
* Optimize debug info generation by not allocating two 0-sized arrays per method with no arguments   
Closes: #4018
> Fix debuginfotest gate

- substratevm/src/com.oracle.svm.jfr/src/com/oracle/svm/jfr/JfrThreadLocal.java
- substratevm/src/com.oracle.svm.jfr/src/com/oracle/svm/jfr/JfrThreadState.java
- substratevm/src/com.oracle.svm.jfr/src/com/oracle/svm/jfr/SubstrateJVM.java
- substratevm/src/com.oracle.svm.jfr/src/com/oracle/svm/jfr/events/ExecutionSampleEvent.java
- substratevm/src/com.oracle.svm.test.jdk11/src/com/oracle/svm/test/jdk11/jfr/TestThreadEvent.java
- substratevm/src/com.oracle.svm.test.jdk11/src/com/oracle/svm/test/jdk11/jfr/ThreadEvent.java
This PR is introducing the `ExecutionSample` event and adds one test for the thread repository.
Event signature:
> @Name("jdk.ExecutionSample")
> @Category({"Java Virtual Machine", "Profiling"})
> @Label("Method Profiling Sample")
> @Description("Snapshot of a threads state")
> class ExecutionSample extends jdk.jfr.Event {
>   @Label("Start Time")
>   @Timestamp("TICKS")
>   long startTime;
> 
>   @Label("Thread")
>   Thread sampledThread;
> 
>   @Label("Stack Trace")
>   StackTrace stackTrace;
> 
>   @Label("Thread State")
>   String state;
> }
> Adding support for JFR ExecutionSample event.

- substratevm/src/com.oracle.svm.core.containers/src/com/oracle/svm/core/containers/CgroupSubsystemFactory.java
- substratevm/src/com.oracle.svm.test/src/META-INF/native-image/com.oracle.svm.test/native-image.properties
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/CgroupSubsystemFactoryTest.java
The cgroups detection code ported from OpenJDK contained a bug
that made the cgroup factory return an empty optional result
on cgroups v2. On such a system, all cgroup hierarchy ids are 0
in /proc/cgroups, yet there is a /proc/self/mountinfo entry
for the cgroup2 pseudo filesystem. However, a later - or
previous - line in mountinfo not containing the cgroup filesystem
type would (wrongly) enter the if condition returning an empty
result.
The intention is to only return that if there really isn't any
cgroup pseudo filesystem mount.
Regression tests for the cgroup detection code have been added.
Closes #3992
> Fix cgroups v2 detection code

- substratevm/mx.substratevm/testhello.py
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageDebugInfoProvider.java
This is a fix for the problem reported in issue #4224.
The fix also enables printing of objects, including those reachable via a static field, under mx debuginfotest when gdb with version 11.0 or greater is in the path. Issue #4224 was not found until recently because the test was disabled due to a bug in gdb 10.x.
> [GR-36446] Fix static field printing when isolates are enabled and test printing in debuginfotest with gdb 11.0+

- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/DebugInfoBase.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/Range.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/StructureTypeEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debuginfo/DebugInfoProvider.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageDebugInfoProvider.java
This trivial fix improves the quality of debug info log output
- Log info for compiled code subranges is moved from level VERBOSE to DETAILED. 
- Log info for heap object/primitive data is moved from level VERBOSE to DETAILED and generated under log context id DebugDataInfo instead of the current DebugCodeInfo.
Subrange messages constitute about 3/4 of the log output for a normal image build when log pattern DebugCodeInfo is passed. Data info messages produce much less output but separating them from code info messages is appropriate since info about heap objects is needed much less often than code info.
> [GR-36532] Improve debug info log output

- substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/GCImpl.java
- substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/GenScavengeGCName.java
- substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/JfrGCEventSupport.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/heap/GCName.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/JfrEvent.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/JfrType.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/JfrTypeRepository.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/JFRTest.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/TestGCEvents.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/TestStringEvent.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/TestThreadEvent.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/utils/JFR.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/utils/JFRFileParser.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/utils/LocalJFR.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/utils/poolparsers/GCCauseConstantPoolParser.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/utils/poolparsers/GCNameConstantPoolParser.java
The patch implements GarbageCollection JFR event. 
```
jdk.GarbageCollection {
startTime = 12:59:39.673
duration = 1.148 ms
gcId = 1
name = "GenScavenge"
cause = "java.lang.System.gc()"
sumOfPauses = 1.148 ms
longestPause = 1.148 ms
}
```
The patch also enhances test framework, so that tests can check expected events are actually recorded. And a new TestGCEvents.java is added to verify currently supported GC events.
> Implementation of GarbageCollection event

- docs/reference-manual/native-image/README.md
In the Windows prerequisites section, all of the Visual Studio references mean the "traditional" Visual Studio, not the newer Visual Studio Code.
> Fix references to Visual Studio in prerequisites

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/JfrEvent.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/JfrTicks.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/events/SafepointBeginEvent.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/events/SafepointEndEvent.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/thread/Safepoint.java
Add implementation of Safepoint event that provides safepoint latency information.
e.g. 
```
jdk.SafepointBegin {
startTime = 15:43:26.488
duration = 4.315 us
safepointId = 2
totalThreadCount = 5
jniCriticalThreadCount = 0
eventThread = "main" (javaThreadId = 1)
}
jdk.SafepointEnd {
startTime = 15:43:26.490
duration = 0.318 us
safepointId = 2
eventThread = "main" (javaThreadId = 1)
}
```
> Implementation of Safepoint events

- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageDebugInfoProvider.java
This prevents `ClassEntry`s from appearing twice in the `primaryClasses`
list which is indexed (in `primaryClassesIndex`) using the type.
Fix #4328
> [GR-37091] Ensure NativeImageDebugLineInfo#ownerType returns the unwrapped type

- substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/GCImpl.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/TestGCEvents.java
This patch adds detail phase pause events for Serial GC's scanning phase.  The phase counts majority time of a GC cycle, it makes sense to further breakdown the phase into sub phases, gives a detailed insight of GC performance characters.
> Add detail phase pause events for scanning phase

- substratevm/mx.substratevm/suite.py
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/Resources.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/resources/ResourceURLConnection.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/NativeImageResourceFileSystemProviderTest.java
- substratevm/src/com.oracle.svm.test/src/resources/.mxkeep
> [GR-37154] Fix handling of resources with trailing slashes

- docs/getting-started/graalvm-community/macos.md
- docs/getting-started/graalvm-enterprise/installation-macos.md
Fixed a typo in the MacOS documentation where "darvin" was used instead of "darwin"
> Typo fix "darvin" -> "darwin"

- truffle/src/com.oracle.truffle.api/src/com/oracle/truffle/api/nodes/ExplodeLoop.java
We were somehow under the impression that loops weren't unrolled unless they had a pe-constant number of iterations. Also took the opportunity to clarify that it doesn't apply to inlined methods.
Found with @eregon and @mattalp.
> Clarify documentation for @ExplodeLoop

- substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/reports/CallTreePrinter.java
Fixes #4355
This makes links work both inside and outside containers with ease.
> Make CSV link relative instead of absolute

- compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64ASIMDAssembler.java
- compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64ASIMDMacroAssembler.java
- compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64ArrayCompareToOp.java
This patch add the SIMD implementation for the String.compareTo()
intrinsic for AArch64. The string comparison switches from
sequential to chunk-based version at the threshold of 32 bytes.
The patch improves performance up to 36% (relative to master) while
comparing strings of 512 bytes on N1 systems.
> Add SIMD version of String.compareTo intrinsic for AArch64

- compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64ASIMDAssembler.java
- compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64MacroAssembler.java
- compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64ArrayEqualsOp.java
- compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64ArrayIndexOfOp.java
The PR adds SIMD version of the AArch64ArrayEqualsOp and improved version of the AArch64ArrayIndexOfOp that jointly implement functionality of `String.indexOf()`.
> Add SIMD version of AArch64ArrayEqualsOp and AArch64ArrayIndexOf

- compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64ASIMDAssembler.java
- compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64ASIMDMacroAssembler.java
- compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64LIRGenerator.java
- compiler/src/org.graalvm.compiler.hotspot.aarch64/src/org/graalvm/compiler/hotspot/aarch64/AArch64HotSpotBackendFactory.java
- compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/meta/HotSpotGraphBuilderPlugins.java
- compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/meta/UnimplementedGraalIntrinsics.java
- compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64StringLatin1InflateOp.java
- compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64StringUTF16CompressOp.java
- compiler/src/org.graalvm.compiler.replacements.aarch64/src/org/graalvm/compiler/replacements/aarch64/AArch64GraphBuilderPlugins.java
- compiler/src/org.graalvm.compiler.replacements.amd64/src/org/graalvm/compiler/replacements/amd64/AMD64GraphBuilderPlugins.java
- compiler/src/org.graalvm.compiler.replacements.test/src/org/graalvm/compiler/replacements/test/StringCompressInflateTest.java
- compiler/src/org.graalvm.compiler.replacements/src/org/graalvm/compiler/replacements/StandardGraphBuilderPlugins.java
- compiler/src/org.graalvm.compiler.replacements/src/org/graalvm/compiler/replacements/StringLatin1InflateNode.java
- compiler/src/org.graalvm.compiler.replacements/src/org/graalvm/compiler/replacements/StringUTF16CompressNode.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageGenerator.java
During microbenchmarking, the patch demonstrates speedup of about 4.5 while compressing and 2.4 while inflating
strings of 512 bytes on N1 systems.
> Add AArch64 SIMD intrinsic for StringLatin1.inflate and StringUTF16.compress

- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/cv/CVLineRecord.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/cv/CVLineRecordBuilder.java
Currently when emitting CodeView debugger records, Graal emits several (binary address, source line) records per line.  While this works, the user experience is less than ideal; single-stepping may appear to stay on the same line, for example, and setting a breakpoint may actually set multiple breakpoints.
This patch will not emit a new line record if the source line is the same as the previous source line.
Besides improving the user experience, there is a 1% reduction in object file size.
This patch also modifies some debug() statements to improve readability.
> Combine Windows debugger line number records.

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JavaIOClassCacheAbsent.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JavaIOClassCachePresent.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JavaIOSubstitutions.java
Closes #4477
* Create a new conditional option to define a boundary for the old substitutions.
* Also add a new conditional for new substitutions.
* Use a custom recompute to create a new instance of the anonymous inner class implementations of ClassCache.
> Adjust ObjectStreamClass Cache recomputations for ClassCache

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/CalleeSavedRegisters.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/heap/SubstrateReferenceMapBuilder.java
This patch fixes the problem reported in issue #4542.
> [GR-38665] Avoid compile failures on AArch64 when full infopoints enabled

- substratevm/mx.substratevm/mx_substratevm.py
- substratevm/mx.substratevm/suite.py
- substratevm/mx.substratevm/testhello.py
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/ClassEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/DebugInfoBase.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/MethodEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/Range.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debuginfo/DebugInfoProvider.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/ELFObjectFile.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfAbbrevSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfDebugInfo.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfInfoSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfLineSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfLocSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfSectionImpl.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/code/CompilationResultFrameTree.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/SVMHost.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImage.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageDebugInfoProvider.java
- substratevm/src/com.oracle.svm.test/src/hello/Hello.java
Implementation PR for  issue #4504
This includes location info for parameters and locals that ar ein registers or on the stack.
It does not yet include info for bindings to constants.
Updates to the reference manual will be provided as a separate PR.
> [GR-38416] Implement debug location info

- sdk/src/org.graalvm.nativeimage/snapshot.sigtest
- sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/c/type/CTypeConversion.java
- sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/impl/CTypeConversionSupport.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/c/CTypeConversionSupportImpl.java
The class `org.graalvm.nativeimage.c.type.CTypeConversion` has provided some convenient methods to convert types between Java and C, but there is no method to transfer a Java byte array to C. This requirement seems duplicated with the existing `toCString` methods, but not all byte arrays are from String. A `toCBytes` method would be more general.
Therefore, this PR proposes to add a new `toCBytes` in `CTypeConversion` class.
> Convert Java byte array to CCharPointerHolder

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/meta/ObjectConstantEquality.java
Mandrel builds don't build/include `org.graalvm.compiler.truffle.compiler` and this import is causing them to fail.
Closes https://github.com/graalvm/mandrel/issues/387
> Removes import needed by javadoc to eliminate build-time dependency

- sdk/mx.sdk/mx_sdk_vm_impl.py
The problem does not affect distributions that use native-image executable.
Mandrel distribution uses native-image as a launcher script, bash on Linux, cmd on Windows and it suffers when installed in a path with spaces in it.
> [GR-39065] Enables native-image script to handle module path with spaces.

- docs/reference-manual/native-image/DebugInfo.md
This PR includes proposed changes to the debug manual in the wake of support for parameter and local vars. The changes do not just document this new feature they also change the example sessions so that they employ the feature to reference data by name that were previously pulled out of memory using registers or raw addresses plucked out of thin air.
> [GR-39144] Update reference manual now debug info includes local vars

- substratevm/src/com.oracle.svm.reflect/src/com/oracle/svm/reflect/hosted/ReflectionDataBuilder.java
Fixes [issue introduced in CI runs](https://github.com/oracle/graal/runs/6960233607?check_suite_focus=true#step:8:333) by https://github.com/oracle/graal/pull/4614
`null` AnnotationValues may be generated in https://github.com/oracle/graal/blob/d5fae2920c65c6b3d2a964a6c875c5a585d54685/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/annotation/AnnotationValue.java#L69-L71
> [GR-39313] Avoid NPEs in includeAnnotation when annotationValue is null

- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/classinitialization/ClassInitializationConfiguration.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JDKInitializationFeature.java
When marking a class `my.package.MyClass` for initialization for a given
reason before this patch `my` and `my.package` would also be assigned
the reason implicitly.  This resulted in reporting the wrong reason in
some cases.  For instance before this patch
`java.lang.AbstractStringBuilder` would be marked as initialized because
it's a "super type of sun.security.util.UntrustedCertificates" which is
clearly not the case.  This patch fixes the underlying problem and
reports "Core JDK classes are initialized at build time" as the reason
for initializing `AbstractStringBuilder` at `BUILD_TIME`.
> [GR-39483] Avoid implicitly setting class initialization reason for classes/packages

- sulong/docs/contributor/INTEROP.md
Previous description does not mention how method resolution is done if C++ methods are involved - this is now added. Feel free to give feedback if something of the content should be changed. 
Mainly for internal discussion with Sulong team (but not restricted to).
> Add C++ interoperability properties

- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/ArrayTypeEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/ClassEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/DebugInfoBase.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/EnumClassEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/HeaderTypeEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/MethodEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/StructureTypeEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/TypeEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debuginfo/DebugInfoProvider.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfDebugInfo.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfInfoSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfSectionImpl.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageDebugInfoProvider.java
This PR is the promised cleanup to the debug info generator that ensures the model of the class base used to drive debug info generation is built by identifying TypeEntry and MethodEntry records using ResolvedJavaClass and ResolvedJavaMethod instances rather than their associated names.  This means the model can cope with multiple types that have the same name and cope with multiple methods attached to some given class that have the same name and signature.
The cleanup also modifies the Dwarf Properties model that associates Dwarf section offsets and other information with a TypeEntry, MethodEntry or Range. Properties records are still stored in hash tables. However, the hash tables are now keyed using the Type/MethodEntry objects rather than the type/method names. Also method Properties …
> [GR-39018] Debug id cleanup

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/JfrEvent.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/events/JavaMonitorWaitEvent.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/monitor/JavaMonitorQueuedSynchronizer.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/monitor/MultiThreadedMonitorSupport.java
Add support for JFR jdk.JavaMonitorWait events in native images. This implementation tries to mirror the implementation in Hotspot native code by leveraging the nodes that wait on the `JavaMonitorConditionObject` wait queue.
> Add jdk.JavaMonitorWait events to JavaMonitorQueuedSynchronizer

- compiler/src/org.graalvm.compiler.java/src/org/graalvm/compiler/java/BytecodeParser.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/phases/SharedGraphBuilderPhase.java
[`CHECKCAST`](https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-6.html#jvms-6.5.checkcast) must not throw an exception when the object is `null`, even if the type cannot be resolved.
> Fix the implementation of CHECKCAST byte code instruction.

- docs/reference-manual/native-image/DebugInfo.md
- docs/reference-manual/native-image/DebuggingAndDiagnostics.md
- substratevm/mx.substratevm/mx_substratevm.py
- substratevm/mx.substratevm/testhello.py
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/ClassEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/CompiledMethodEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/DebugInfoBase.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/FieldEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/MemberEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/MethodEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/StringTable.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debuginfo/DebugInfoProvider.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfARangesSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfAbbrevSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfDebugInfo.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfFrameSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfInfoSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfLineSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfLocSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/cv/CVLineRecordBuilder.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/cv/CVSymbolSubrecord.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/cv/CVSymbolSubsectionBuilder.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImage.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageDebugInfoProvider.java
This PR implements changes to Linux debug info generation specified in issue #4810. These enable the Linux tool `perf` to display profile information for GraalVM native images.
This patch 'fixes' `perf` modulo from a few small remaining details:
`perf` expects many references from definitions to associated declarations (`specification` or `abstract_origin` attribute values) to be implemented as compile unit (CU) local offsets because it assumes that a single CU owns both the referring and referenced records. There are still a few cases in Java debug info where definitions and declarations need to be in different CUs and so must use an info section global offset. This is no problem for `gdb` but `perf` cannot cope with it.
`perf` does display generated machine code for sampled code …
> [GR-40874] Perf support

- substratevm/mx.substratevm/suite.py
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jni/functions/JNIFunctions.java
[GetDirectBufferCapacity()](https://docs.oracle.com/en/java/javase/11/docs/specs/jni/functions.html#getdirectbuffercapacity) JNI must return -1 if the given object is not a direct java.nio.Buffer.
This is a continuation of #4715.
> Fix GetDirectBufferCapacity() implementation

- substratevm/src/com.oracle.graal.pointsto.standalone/src/com/oracle/graal/pointsto/standalone/PointsToAnalyzer.java
- substratevm/src/com.oracle.graal.pointsto.standalone/src/com/oracle/graal/pointsto/standalone/features/StandaloneAnalysisFeatureImpl.java
- substratevm/src/com.oracle.graal.pointsto.standalone/src/com/oracle/graal/pointsto/standalone/features/StandaloneAnalysisFeatureManager.java
- substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/meta/AnalysisUniverse.java
Add Feature mechanism in standalone pointsto analysis framework, so that the analysis can be extended by specifying feature through -H:AnalysisTimeFeatures= option. 
This PR is part of the standalone pointsto analysis, see https://github.com/oracle/graal/pull/4375 for details.
> Support Feature mechanism in standalone pointsto

- substratevm/src/com.oracle.graal.pointsto.standalone/src/com/oracle/graal/pointsto/standalone/PointsToAnalyzer.java
- substratevm/src/com.oracle.graal.pointsto.standalone/src/com/oracle/graal/pointsto/standalone/StandaloneOptions.java
Loaded the analysis framework and target classes with different classloaders.
- The pointsto analysis framework classes are specified with JVM's `-cp` and loaded by the application classloader.
- The analysis target classes are specified with a new option `-H:AnalysisTargetAppCP` and loaded by a dedicated classloader.
> Load analysis classes with a dedicated classloader

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/methodhandles/Target_java_lang_invoke_MethodHandleNatives.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/methodhandles/MethodHandleFeature.java
Fixes #4794.
Can you provide guidance on where to add the `Unsafe.putReference` reflection registration so that users don't have to do this?
> [GR-41270] Verify access should only be called when caller is not null

- substratevm/mx.substratevm/suite.py
- substratevm/src/com.oracle.graal.pointsto.standalone.test/src/com/oracle/graal/pointsto/standalone/test/ClassEqualityTest.java
- substratevm/src/com.oracle.graal.pointsto.standalone.test/src/com/oracle/graal/pointsto/standalone/test/PointstoAnalyzerTester.java
- substratevm/src/com.oracle.graal.pointsto.standalone.test/src/com/oracle/graal/pointsto/standalone/test/StandaloneAnalyzerReachabilityTest.java
- substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/util/PointsToOptionParser.java
Adding unit tests and a tester framework to run standalone pointsto analysis and verifies the results.
This PR is part of the standalone pointsto analysis, see https://github.com/oracle/graal/pull/4375 for details.
> Add unit tests for standalone pointsto analysis

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/localization/LocalizationSupport.java
Blindly replacing dots with slashes results in errors like the following:
```
Error: Resource pattern "java/xml:com/sun/org/apache/xerces/internal/impl/msg/XMLMessages_en_IE\.properties"s specifies unknown module java/xml
com.oracle.svm.core.util.UserError$UserException: Resource pattern "java/xml:com/sun/org/apache/xerces/internal/impl/msg/XMLMessages_en_IE\.properties"s specifies unknown module java/xml
at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:73)
at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ResourcesFeature.makeResourcePattern(ResourcesFeature.java:296)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) …
```
> [GR-41500] Avoid replacing dots with slashes in module names when preparing bundles

- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JNIRegistrationManagementExt.java
On some systems/apps, libawt_headless gets pulled in. This currently brings in libmanagement_ext unconditionally. However, libmanagement_ext should only be present for linking iff
com.sun.management.internal.OperatingSystemImpl class becomes reachable. The fix is to only add `management_ext` as a dependency for `awt_headless` when class `OperatingSystemImpl` is actually reachable.
Closes: #5119
> [GR-41675] Only require libmanagement_ext if it's actually needed.

- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/ClassEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/DebugInfoBase.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/Range.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfDebugInfo.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfInfoSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfSectionImpl.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageDebugInfoProvider.java
This PR implements significant improvements to debug info footprint. It only addresses changes local to the debug info generator. Although this is a great improvement the limited scope of the changes means that a large amount of the footprint that results from enabling of debug info is still present (debug info-related output by the compiler and ELF image modelling). An accompanying report (to be attached) identifies these overheads as well as the overheads addressed by this patch and suggests some areas where space savings might perhaps still be achieved in these other components.
> [GR-42531] Debug info memory footprint improvements

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/CgroupMetricsJDK.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/HasGetTotalMemorySize0.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/Target_jdk_internal_platform_CgroupMetrics.java
Latest JDK code received an update to bound the
reported container memory above by the total physical memory
of the host running the container. See [JDK-8292541](https://bugs.openjdk.org/browse/JDK-8292541)
Implement the same in GraalVM, only substituting the class/methods
if they exist in the JDK.
Closes #5387
> [GR-42460] Add support for CgroupMetrics.getTotalMemory0

- substratevm/src/com.oracle.graal.pointsto.standalone.test/src/com/oracle/graal/pointsto/standalone/test/ClassEqualityCase.java
- substratevm/src/com.oracle.graal.pointsto.standalone.test/src/com/oracle/graal/pointsto/standalone/test/ClassEqualityTest.java
- substratevm/src/com.oracle.graal.pointsto.standalone.test/src/com/oracle/graal/pointsto/standalone/test/ConstantFieldTest.java
- substratevm/src/com.oracle.graal.pointsto.standalone.test/src/com/oracle/graal/pointsto/standalone/test/PointstoAnalyzerTester.java
- substratevm/src/com.oracle.graal.pointsto.standalone.test/src/com/oracle/graal/pointsto/standalone/test/StandaloneAnalyzerReachabilityCase.java
- substratevm/src/com.oracle.graal.pointsto.standalone/src/com/oracle/graal/pointsto/standalone/PointsToAnalyzer.java
- substratevm/src/com.oracle.graal.pointsto.standalone/src/com/oracle/graal/pointsto/standalone/heap/StandaloneImageHeapScanner.java
- substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/meta/AnalysisUniverse.java
1.Directly look up fields, methods and types from universe instead of walking through to search when checking the reachability of the given items. It will improve the testing performance.
2.Accept Field, Method and Class type at setting expected (un)reachable time.
This PR is part of https://github.com/oracle/graal/pull/4375.
> Refactor standalone tests

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/VM.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/SystemPropertiesSupport.java
- substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/NativeImage.java
Certain monitoring tools that rely on sys props, e.g. [Micrometer](https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmInfoMetrics.java), might report unpopulated fields when operating with native-image built apps, e.g.
[Quarkus Micrometer Quickstart](https://github.com/quarkusio/quarkus-quickstarts/tree/main/micrometer-quickstart) reports in native mode:
```
jvm_info_total{runtime="unknown",vendor="Oracle Corporation",version="unknown",} 1.0
```
while it works correctly in HotSpot, JVM mode:
```
jvm_info_total{runtime="OpenJDK Runtime Environment",vendor="Eclipse Adoptium",version="17.0.5+8",} 1.0
```
With this patch, we have both more meaningful values and a way to affect them if needed (e.g. vendor url …
> Populate SystemProperties for SVM runtime

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/IsolateArgumentParser.java
Add an API to return long typed option values (-Xmx,-Xms and -Xmn) that are setting in Isolate parameters.
This PR fixes the issue https://github.com/oracle/graal/issues/4851
> Return long option from Isolate parameters

- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/ClassEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/cv/CVConstants.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/cv/CVDebugInfo.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/cv/CVNames.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/cv/CVSymbolSubrecord.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/cv/CVSymbolSubsectionBuilder.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/cv/CVTypeConstants.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/cv/CVTypeRecord.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/cv/CVTypeSectionBuilder.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/cv/CVTypeSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/cv/CVUtil.java
This PR adds type information to the CodeView 4 debug information (See PR #2396).  It is related to issue #2986, but is targeted to Windows and Visual Studio.
This PR is based off (and highly dependant on) the work in PR #3046.
With this patch, memory can be examined from the Visual Studio or WinDbg command line and cast to Java types as laid out by the Graal compiler.  Static member variables can be referenced directly.
Caveats:
- Pointer types for instance members in the presence of isolates are not yet implemented, as there appears to be no way to express a pointer that is an offset from r14 in CodeView.  I will continue to research this, but at this time, this implementation works best if isolates are disabled.
- As there is no local variable information added by this PR, users must …
> [GR-34179] Upgrade CE debug info feature to provide information about Java types for Windows/PECOFF

- .github/workflows/quarkus.yml
There are a couple of failures that I will have a look at soon, but this should be good to get merged in the meantime.
> [GR-43491] CI: Use jdk-20-based builds for Quarkus nightly tests

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/CgroupMetricsJDK.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/HasGetTotalMemorySize0.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/Target_jdk_internal_platform_CgroupMetrics.java
Latest JDK code received an update to bound the reported container memory
above by the total physical memory of the host running the container.
Implement the same in GraalVM, only substituting the class/methods if they
exist in the JDK.
Cherry-picked commit from master: 3dcf7c7eaea22504cac1f7520b675fd025a0e0df
Closes #5495
> [Backport][22.3] Add support for CgroupMetrics.getTotalMemory0

- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/ClassEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/CompiledMethodEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/DebugInfoBase.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/MemberEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/Range.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/range/CallRange.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/range/LeafRange.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/range/PrimaryRange.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/range/Range.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/range/SubRange.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debuginfo/DebugInfoProvider.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfARangesSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfDebugInfo.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfFrameSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfInfoSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfLineSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfLocSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/cv/CVLineRecordBuilder.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/cv/CVSymbolSubsectionBuilder.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageDebugInfoProvider.java
This is a second round of improvements to debug info footprint. It involves one change to the COMPILER phase and four to the DWARF phase:
1. Each entry in a compiled method's `Infopoint` list includes a leaf `BytecodeFrame` which links an associated linear chain of caller `BytecodeFrame` instances. In many cases the chains in adjacent `Infopoint` instances are either identical or share most ancestors (based on `BytecodeFrame.equals`). Storage can be compressed by merging this list of lists to an equivalent tree where common ancestors are reduced to unique instances. This can be done as a final step during compilation, ensuring that the reduction in memory is delivered incrementally over the compilation phase rather than as one final step.
n.b. It would be preferable to generate the …
> [GR-43600] Additional debuginfo memory footprint improvements

- substratevm/src/com.oracle.graal.pointsto.standalone.test/src/com/oracle/graal/pointsto/standalone/test/AnalysisEntryPointsFileTest.java
- substratevm/src/com.oracle.graal.pointsto.standalone.test/src/resources/entrypoints
- substratevm/src/com.oracle.graal.pointsto.standalone/src/com/oracle/graal/pointsto/standalone/MethodConfigReader.java
- substratevm/src/com.oracle.graal.pointsto.standalone/src/com/oracle/graal/pointsto/standalone/PointsToAnalyzer.java
- substratevm/src/com.oracle.graal.pointsto.standalone/src/com/oracle/graal/pointsto/standalone/StandaloneOptions.java
- substratevm/src/com.oracle.graal.pointsto.standalone/src/com/oracle/graal/pointsto/standalone/StandalonePointsToAnalysis.java
- substratevm/src/com.oracle.graal.pointsto.standalone/src/com/oracle/graal/pointsto/standalone/doc-files/AnalysisEntryPointsFileHelp.txt
In many static analysis scenarios, users need to set more analysis entry points than Main method. This PR supports such requirement by adding option `-H:AnalysisEntryPointFile=` to set a file where all entry point methods are listed. The method names are matched by `org.graalvm.compiler.debug.MethodFilter`.
This PR is part of https://github.com/oracle/graal/pull/4375
> Read entrypoints from file

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/graal/jdk/SubstrateArraycopySnippets.java
`System.arraycopy​(Object src, int, Object dest, int, int)` should throw an `ArrayStoreException` when:
- `src` is an instance of `Object[]`, and
- `dest` is an instance of `Object`, and
- `src.getClass()` != `dest.getClass()`.
In the previous implementation, the following condition is satisfied:
```java
DynamicHub.toClass(toHub).isAssignableFrom(DynamicHub.toClass(fromHub))
```
where:
- `DynamicHub.toClass(toHub)` is `Object`, and
- `DynamicHub.toClass(fromHub)` is `Object[]`
because an `Object` variable can be assigned an `Object[]` value.
In this situation, `JavaMemoryUtil.copyObjectArrayForward()` is called, and the behavior is undefined.
The correct behavior should be throwing an `ArrayStoreException`.
> `System.arraycopy()` should not copy `Object[]` into `Object`

- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JmxCommonFeature.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JmxServerFeature.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jmx/JmxTest.java
This PR tries to optimize some of the configuration needed for remote JMX support. Another round of optimizations will be done at some point in the future.
Unfortunately, even after these changes, the native image doesn't get much smaller. But this might help increase maintainability at least. 
Added some more tests in substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jmx/JmxTest.java
Removed BufferPoolMXBean test because it's not actually implemented (so the test always passes anyway).
Slimmed down reflection configuration for platform MXBeans in substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JmxServerFeature.java 
(this doesn't actually make the image much smaller unfortunately). Only the dynamic proxy configuration and reflection configuration for the …
> [GR-40463] RJMX Configuration Optimization.

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/JfrChunkWriter.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/JfrMethodRepository.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/JfrStackTraceRepository.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/JfrSymbolRepository.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/JfrThreadRepository.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/TestConstantPoolClearing.java
**Summary of Changes**
Always clear symbol, method, and stacktrace constant pools after a write. 
**Description of Bug**
Previously, the constant pool epochData was only cleared after a write if there were unflushed entries. This is incorrect because a flushpoint may clear the serialized entry buffer and reset unflushedEntries, then if there are no entries added before the next chunk rotation, [the constant pool will not be cleared at the chunk rotation](https://github.com/oracle/graal/pull/6293/files#diff-e7b044a7ea6e171ab0088db387f18f9e25275f64a3ce2b3d98a968a2670c4742R116). This is a problem because the next time that epochData is active its data buffer will be empty, but the hash table used for deduplication will still contain entries from the a prior epoch. This results in references …
> Fix bug in JFR constant pool clearing

- substratevm/src/com.oracle.graal.pointsto.standalone.test/src/com/oracle/graal/pointsto/standalone/test/ArrayNewInstancePluginCase.java
- substratevm/src/com.oracle.graal.pointsto.standalone.test/src/com/oracle/graal/pointsto/standalone/test/PointstoAnalyzerTester.java
- substratevm/src/com.oracle.graal.pointsto.standalone.test/src/com/oracle/graal/pointsto/standalone/test/StandardGraphPluginTest.java
- substratevm/src/com.oracle.graal.pointsto.standalone/src/com/oracle/graal/pointsto/standalone/PointsToAnalyzer.java
Register invocation plugins for standalone analysis.
This PR should be merged after PR https://github.com/oracle/graal/pull/5894, otherwise the tests will fail. 
This PR is part of https://github.com/oracle/graal/pull/4375.
> Add StandardGraphBuilderPlugins for standalone analysis

- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/ClassEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/CompiledMethodEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/DebugInfoBase.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/DirEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/FileEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/InterfaceClassEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/LoaderEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/MemberEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/MethodEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/PrimitiveTypeEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/StringEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/StructureTypeEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/TypeEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/range/PrimaryRange.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/range/Range.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/range/SubRange.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debuginfo/DebugInfoProvider.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfARangesSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfAbbrevSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfDebugInfo.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfFrameSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfInfoSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfLineSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfLocSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfSectionImpl.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageDebugInfoProvider.java
This PR reorganizes the DWARF debug info layout so that all info is all contained in a single compile unit (CU) rather than employing a CU for every Java class type.
It profits from that reorganization to achieve several important goals:
- reduce the overall size of debug info by avoiding replication of DIEs shared by multiple classes
- reduce the overall size of debug info by omitting unnecessary CU boiler plate
- decouple compiled method info and definition order from class declaration order, thereby freeing the image builder to order method code ranges without respect to class grouping
The re-implementation also has the benefit that it simplifies many of the DWARF generation steps, both when iterating the generic debug model to write specific debug sections and when cross-indexing …
> [GR-45654] Single compile unit for Java DWARF debug info

- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/sources/SourceCache.java
This patch avoids a potential NPE when the buildJDK does not include sources file `lib/src.zip`.
> Avoid NPE when build JDK has no source zip.

- substratevm/src/com.oracle.svm.configure/src/com/oracle/svm/configure/trace/AccessAdvisor.java
The implementation of `java.util.jar.Pack200.newInstance()` calls `Class.newInstance()`, and that invocation needs to be recorded by `native-image-agent`.
> `native-image-agent` scan should consider `java.util.jar.Pack200`.

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jni/functions/JNIFunctions.java
The following JNI functions accept some UTF-8 strings as arguments:
- `FindClass`
- `GetFieldID`
- `GetMethodID`
- `GetStaticFieldID`
- `GetStaticMethodID`
- `RegisterNatives`
This patch checks that the UTF-8 strings provided to these methods are correctly encoded. If they are not, then the proper [JNI error reporting behavior](https://docs.oracle.com/en/java/javase/11/docs/specs/jni/functions.html) is performed, mainly:
- `FindClass` throws `NoClassDefFoundError`.
- `GetFieldID` and `GetStaticFieldID` throw `NoSuchFieldError`.
- `GetMethodID`, `GetStaticMethodID` and `RegisterNatives` throw `NoSuchMethodError`.
> Check UTF-8 encoding in JNI functions

- substratevm/mx.substratevm/suite.py
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JmxClientFeature.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JmxCommonFeature.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JmxServerFeature.java
This adds reflection configuration for `com.sun.jmx.remote.protocol.rmi.ClientProvider` and `com.sun.jmx.remote.protocol.rmi.ServerProvider`.
When the JMX mbean server is set up to  accept remote connections, [`JMXConnectorServerFactory.newJMXConnectorServer`](https://github.com/openjdk/jdk/blob/master/src/java.management/share/classes/javax/management/remote/JMXConnectorServerFactory.java#L275) is called, which eventually can result in a call to `Class.forName()` with `com.sun.jmx.remote.protocol.rmi.ServerProvider`.
A similar path starting from [`JMXConnectorFactory.newJMXConnector`](https://github.com/openjdk/jdk/blob/master/src/java.management/share/classes/javax/management/remote/JMXConnectorFactory.java#L327) can lead to requiring reflection metadata for …
> [GR-46055] Add Javadocs and reflection registrations for `ServerProvider` and `ClientProvider` in JMX Features

- substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/darwin/DarwinThreadCpuTimeSupport.java
- substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/headers/Unistd.java
- substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/headers/linux/LinuxPthread.java
- substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/linux/LinuxThreadCpuTimeSupport.java
- substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/thread/PosixVMThreads.java
- substratevm/src/com.oracle.svm.core.windows/src/com/oracle/svm/core/windows/WindowsThreadCpuTimeSupport.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/LibCHelper.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/thread/PlatformThreads.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/thread/ThreadCpuTimeSupport.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/thread/VMThreads.java
- substratevm/src/com.oracle.svm.native.libchelper/src/getThreadUserTime.c
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jmx/ThreadCpuTimeTest.java
This is a proposal for a thread user cpu time implementaion in `LinuxThreadCpuTimeSupport.getThreadCpuTime()` method:  https://github.com/oracle/graal/blob/be7610ba0c935325098746b7431f1577661c89b3/substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/linux/LinuxThreadCpuTimeSupport.java#L63
The logic which retrieves thread user time is based on jdk [static jlong slow_thread_cpu_time(Thread *thread, bool user_sys_cpu_time)](https://github.com/openjdk/jdk/blob/9df20600592427550998c6685f103737e3115a51/src/hotspot/os/linux/os_linux.cpp#L5035) method.
- `PosixVMThreads.getCurrentOSThreadId()` is updated to return `gettid()` on Linux platform.
-  `ThreadCpuTimeSupport.getThreadCpuTime(OSThreadHandle, boolean)` method is changed to  `getThreadCpuTime(IsolateThread, boolean)`. …
> Thread user cpu time implementation for LinuxThreadCpuTimeSupport.getThreadCpuTime() method

- substratevm/src/com.oracle.graal.pointsto.standalone.test/src/com/oracle/graal/pointsto/standalone/test/PointstoAnalyzerTester.java
- substratevm/src/com.oracle.graal.pointsto.standalone.test/src/com/oracle/graal/pointsto/standalone/test/StandaloneAnalysisReportTest.java
- substratevm/src/com.oracle.graal.pointsto.standalone/src/com/oracle/graal/pointsto/standalone/PointsToAnalyzer.java
- substratevm/src/com.oracle.graal.pointsto.standalone/src/com/oracle/graal/pointsto/standalone/StandaloneOptions.java
Refactor the SubstrateOptions.Path option to a common place for both pointsto and SVM, so that the analysis report can be printed to the location specified by Path in standalone pointsto.
This PR is part of https://github.com/oracle/graal/pull/4375
> Print reports after standalone pointsto analysis

- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/TestVirtualThreadsBasic.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/TestVirtualThreadsChunkRotation.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/TestVirtualThreadsJfrStreaming.java
It's possible for threads to reuse IDs of inactive threads. This means that we have to replace the `expectedThreads` set with a map that records a count of seen threads for each ID. Additionally, the previous implementation of `expectedThreads` was not thread safe. Writes from some threads may not be immediately visible to other threads.  It's been changed to a `ConcurrentHashMap`. This should resolve some of the JFR virtual thread test failures.
This PR does not fix all the problems with `TestVirtualThreadsChunkRotation`. There is still a problem related to dumping snapshots I must investigate further, so it is still skipped for now.
This is related to : https://github.com/oracle/graal/pull/6464#issuecomment-1551367336
> Fix for JFR virtual thread tests

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/JfrStackTraceRepository.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/JfrSymbolRepository.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/TestSymbolTraceIdUniqueness.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/TestVirtualThreadsChunkRotation.java
**Description of Bug**
The `JfrSymbolRepository` was allowing for JFR IDs to be duplicated across epochs. This results in incorrect symbol constant pool data. Consumer code that reads the JFR data on disk will confuse the values that share the same IDs. VisualVm also interprets the wrong symbol values due to the ID duplication.
Although `JfrSymbolHashtable.nextId` monotonically increases and is never reset, there were separate `JfrSymbolHashtable`s for each epoch, resulting in two `nextId` counts. This effectively results in allowing the same ID key to be used twice. 
The[ hotspot code that handles symbol IDs forces them to be unique.](https://github.com/openjdk/jdk/blob/master/src/hotspot/share/jfr/support/jfrSymbolTable.cpp#L37-L39) 
The stacktrace repo suffers from the same problem. …
> Fix constant pool JFR ID bug

- substratevm/mx.substratevm/testhello.py
- substratevm/src/com.oracle.svm.test/src/hello/Hello.java
Catches cases like https://github.com/graalvm/mandrel/issues/355 caused by [JDK-8281266](https://bugs.openjdk.java.net/browse/JDK-8281266)
> [GR-44098] Add lambda methods test in debuginfotest

- sdk/mx.sdk/mx_sdk_benchmark.py
- vm/mx.vm/mx_vm_benchmark.py
Benchmarks with JNI classes, such as Renaissance with the PAPI agent plugin, require adding `-Djava.library.path` to the JVM in the agent and run phases. This patch permits injecting the option via `-Dnative-image.benchmark.extra-jvm-arg`.
@farquet Could you please take a look if this or something with similar functionality could be added ?
> Injecting JVM arguments via `-Dnative-image.benchmark.extra-jvm-arg`

- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/ClassEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/DebugInfoBase.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/DirEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/FileEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/MemberEntry.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/range/Range.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/ELFObjectFile.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfARangesSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfAbbrevSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfDebugInfo.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfFrameSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfInfoSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfLineSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfLocSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfRangesSectionImpl.java
- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfSectionImpl.java
This patch restores the DWARF debug info generator to generating a compilation unit (CU) per Java class. This helps alleviate the performance problem identified in issue  #6936.
> [GR-47106] Return to separate CUs per class to improve gdb startup time

- substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/JfrGCEventSupport.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/JfrEvent.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/JfrNativeEventSetting.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/SubstrateJVM.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/events/JavaMonitorEnterEvent.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/events/JavaMonitorInflateEvent.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/events/JavaMonitorWaitEvent.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/events/SafepointBeginEvent.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/events/SafepointEndEvent.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/events/ThreadParkEvent.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/events/ThreadSleepEventJDK17.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/JfrRecordingTest.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/JfrStreamingTest.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/TestThreshold.java
fixes: https://github.com/oracle/graal/issues/6944 
**Description**
Adds checking that duration threshold is exceeded before emitting native events. Java level events are not affected because their threshold values are maintained by `jdk.jfr.internal.PlatformEventType`
This issue is present in previous versions of Native Image JFR and might be worth backporting to 23.0 because the changes are minimal.
> Check threshold for native JFR events

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/JfrThreadLocal.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/Target_jdk_jfr_internal_EventWriter.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/TestJavaLevelVirtualThreadEvents.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/TestThreadParkEvents.java
**Summary of Changes**
The java-level JFR EventWriter substitution code has been out-of-date since Java 11 and so does not properly support virtual threads. As a result, incorrect thread data was attached to events emitted by virtual threads. 
Each carrier thread has it's own java-level EventWriter which is shared among all the vthreads that get mounted on it. This means that when a vthread uses the java-level EventWriter, it must update the appropriate members with its own specific data. This is the same situation as in hotspot: https://github.com/openjdk/jdk/blob/master/src/hotspot/share/jfr/writers/jfrJavaEventWriter.cpp#L250
Added a test to catch this problem in the future. 
Added a test for `jdk.ThreadPark` because I noticed this event was missing a test (not related to the …
> Update JFR EventWriter substitutions to support java-level virtual thread events

- docs/reference-manual/native-image/guides/create-heap-dump-from-native-executable.md
- sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/VMRuntime.java
- sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/impl/HeapDumpSupport.java
- substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/GCImpl.java
- substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/PosixRawFileOperationSupport.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/DumpHeapOnSignalFeature.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/SubstrateOptions.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/heap/dump/HeapDumpSupportImpl.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/heapdump/HeapDumpSupportImpl.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/os/RawFileOperationSupport.java
Closes #4641.
Implements support for `-XX:+HeapDumpOnOutOfMemoryError` flag.
I've made some small changes to the `HeapDumpOperation` to be able to use it for this use case. The key thing is that all code in the operation has to be allocation free, which meant tweaking the error reporting method to not allocate. After discussing with @christianhaeubl, a new set of `open` and `create` methods have been added that take a `CCharPointer`. On startup, if `-XX:+HeapDumpOnOutOfMemoryError` is passed, the filename is pre-calculated and stored temporarily in case it's needed. Then, when OOME hits, the `CCharPointer` is used to create the file descriptor and pass it to the native VM operation.
To use `-XX:+HeapDumpOnOutOfMemoryError`, native image has to be built with `--enable-monitoring=heapdump`. …
> Add support for -XX:+HeapDumpOnOutOfMemoryError

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/JfrManager.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/events/ThreadCPULoadEvent.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/TestThreadCPULoadEvent.java
This PR fixes two native image JFR problems. 
1. Problem: Periodic end/begin chunk events do not get emitted when the JFR API is used. This is because the appropriate periodic events were previously only registered when JFR is started from the command line. However, this is a problem if recordings are instead started using the JFR API (which is what the unit tests use).
This part of the PR should be backported to previous GraalVM versions because it affects every version the JFR custom event API is supported. 
2. Problem: ThreadCPULoad events attach thread data of the thread that is emitting the event instead of the thread that the data belongs to. This problem only manifests when the event is emitted at the end of a chunk (one thread will emit events on behalf of all running threads). …
> Fix bug in JFR periodic chunk events and fix thread data in ThreadCPULoad events

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/JfrEvent.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/JfrManager.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/JfrThreadLocal.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/SubstrateJVM.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/events/EndChunkNativePeriodicEvents.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/events/EveryChunkNativePeriodicEvents.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/events/ThreadAllocationStatisticsEvent.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/events/ThreadCPULoadEvent.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/thread/PlatformThreads.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/TestThreadAllocationStatisticsEvent.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/TestThreadCPULoadEvent.java
This pull request does: 
1. Add support for the ThreadAllocationStatistics event and does some refactoring to emit all periodic chunk events in a single VM operation. 
2. Modifies the checking of thread exclusion to account for the case where a single thread (during a VM operation) is emitting events on behalf of multiple other threads. It should be checking the other thread's exclusion state, not it's own. This is important for periodic chunk events like ThreadCPULoad and ThreadAllocationStatistics.
3. Moves ClassLoadingStatistics and ThreadCPULoad event code to `EveryChunkNativePeriodicEvents` class.  This is so that they will match the period specified in Hotspot https://github.com/openjdk/jdk/blob/master/src/hotspot/share/jfr/metadata/metadata.xml#L842
> Add support for jdk.ThreadAllocationStatistics event and fix thread exclusion for chunk periodic events

- truffle/src/com.oracle.truffle.api.exception/src/com/oracle/truffle/api/exception/DefaultStackTraceElementObject.java
> Ensure that `DefaultStackTraceElementObject` satisfies the contract of `InteropLibrary`

- substratevm/mx.substratevm/testhello.py
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageBFDNameProvider.java
- substratevm/src/com.oracle.svm.test/src/hello/Hello.java
This PR fixes issue #7421 (q.v.)
The issue is susceptible to a simple fix and a more sophisticated fix as outlined below. The current patch implements the more sophisticated patch in order to minimize symbol footprint
The simplest solution to the problem is to encode primitive type name using embedded symbol names. So, given the two examples cited in the issue
```
void java.util.Arrays::fill(byte[]*, int, int, byte)
java.lang.String[]* java.lang.String::split(java.lang.String*, int, boolean)
```
the encodings would be
```
_ZN16java.util.Arrays4fillEJvP6byte[]ii4byte
_ZN16java.lang.String5splitEJP18java.lang.String[]PS_i7boolean
```
which successfully decode as desired
```
$ c++filt _ZN16java.util.Arrays4fillEJvP6byte[]ii4byte
void java.util.Arrays::fill(byte[]*, int, int, byte)
$ c++filt …
```
> [GR-49402] Correct mangling of primitive types in BFD name mangler

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/Target_jdk_jfr_internal_JVM_ChunkRotationMonitor.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/events/JavaMonitorWaitEvent.java
This is a very minor change to replicate the behavior in OpenJDK by omitting internal `jdk.JavaMonitorWait` events emitted by the JFR periodic task.  This basically just reduces some noise, especially when the application is idle.
Bugzilla: https://bugs.openjdk.org/browse/JDK-8286707?jql=text%20~%20%22jfr%22
OpenJDK PR: https://github.com/openjdk/jdk/pull/8883
See before (sorted by thread name):
And after:
> Omit internal jdk.JavaMonitorWait JFR events

- sdk/mx.sdk/mx_sdk_vm_impl.py
- substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/NativeImage.java
In #7171 `graal-sdk` got split into several parts. This patch accounts for that and adds
the new dependencies to the module path when the JDKs `jimage` is being queried for built-in modules.
`--add-modules org.graalvm.polyglot` has been dropped from the native-image launcher. It
gets added to the module path on demand if needed.
Closes #7085
> [GR-48144] Fix native-image build with --no-jlinking

- sdk/mx.sdk/mx_sdk_vm_impl.py
Disable the stripping of debug symbols from the generated native bits
Closes https://github.com/oracle/graal/issues/6995
If accepted, we would like to backport it to 23.1 and 23.0 as well.
> Introduce `--disable-debuginfo-stripping` mx argument

- substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/AbstractMemoryPoolMXBean.java
- substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/GenScavengeMemoryPoolMXBeans.java
This PR addresses #6814.
It turns out max eden size is enforced post factum, i.e. if 'memory used' >= 'max size' then GC is started (see [`AbstractCollectionPolicy::shouldCollectOnAllocation`](https://github.com/oracle/graal/blob/8b81a03fee458013b8b703e234e77edc4836be43/substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/AbstractCollectionPolicy.java#L90)). This applies also to young generation as a whole -- see [`BasicPolicy::shouldCollectOnAllocation`](https://github.com/oracle/graal/blob/8b81a03fee458013b8b703e234e77edc4836be43/substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/BasicCollectionPolicies.java#L60). So we cannot assume that maximum size, as reported by collection policy, will never be exceeded. It seems there …
> Use -1 as max value for eden and survivor spaces

- sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/impl/ReflectionRegistry.java
- substratevm/mx.substratevm/mx_substratevm.py
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/ConditionalConfigurationRegistry.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jni/JNIAccessFeature.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/reflect/ReflectionDataBuilder.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/ReflectionRegistrationTest.java
Don't allow null values to be passed to the `register` method of `RuntimeJNIAccess` and `RuntimeReflection`. Since these are public APIs GraalVM should either handle null values (by ignoring them in this case) or throw a `NullPointerException` before creating an asynchronous task to perform the registration in the analysis, which then results in `NullPointerException`s being thrown later when it's no longer possible to understand where the null value originate from.
Closes: https://github.com/quarkusio/quarkus/issues/34698 
If accepted, it would also be good to get this backported to 23.1 and 23.0 (and 22.3?).
> [GR-49816] Throw exception for null pointers passed to RuntimeJNIAccess / RuntimeReflection register methods

- substratevm/mx.substratevm/testhello.py
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageDebugInfoFeature.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageDebugInfoProvider.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageDebugInfoProviderBase.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/debug/CStructTests.java
- substratevm/src/com.oracle.svm.test/src/hello/Hello.java
This PR modifies the debug info provider to use the compiler calling convention when generating locations for incoming parameters. This ensures that the correct locations are used appropriate to the current operating system, target CPU and incoming call API type (Java or Native).
> Use calling convention to derive incoming param register and stack slot locations

- substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/HeapImpl.java
As per @peter-hofer 's [suggestion](https://github.com/oracle/graal/issues/7652#issuecomment-1777610982), this patch fixes #7652 
I can confirm it works on the platforms available to me:
* Linux aarch64 ✔️
* Linux amd64 ✔️
* Windows amd64 ✔️
> Fixes issue-7652 for epsilon gc [master]

- substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/GCImpl.java
Brings the formatting of GC logs more in line with the implementations in HotSpot. Implementations in HotSpot differentiate between log messsages that provide details about pauses versus log messages that are auxiliary. This change will make it easier to integrate with existing tools that already parse HotSpot GC logs.
Before this change, the output would look like this:
```
[658.653s] GC(11) Incremental GC (Collect on allocation) 54.50M->9.50M 3.346ms
[658.793s] GC(12) Full GC (Collect on allocation) 53.50M->9.00M 23.244ms
```
After this change, it looks like:
```
[94.035s] GC(2257) Pause Incremental GC (Collect on allocation) 8.00M->4.00M 0.301ms
[94.046s] GC(2258) Pause Full GC (Collect on allocation) 8.00M->4.00M 1.863ms
```
And here's a HotSpot G1 log message for comparison:
``` …
```
> Add a `Pause` prefix to the serial GC log entries

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/Target_jdk_jfr_internal_MirrorEvents.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/TestMirrorEvents.java
Adds a test to ensure mirror events are handled and set up correctly.  This should help catch changes in OpenJDK that might affect such events in SubstrateVM.
> Add test to verify JFR mirror events

- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/ReachabilityHandlerFeature.java
Prevents data races in reachability handlers registration when using
`-H:-RunReachabilityHandlersConcurrently`.
The fact that https://github.com/oracle/graal/issues/5868 is not deterministic and it's related to enabling/disabling concurrency hints that it's probably caused by a data race. 
Adding a synchonized blocks in `com.oracle.svm.hosted.ReachabilityHandlerFeature#registerReachabilityHandler(org.graalvm.nativeimage.hosted.Feature.BeforeAnalysisAccess, java.lang.Object, java.lang.Object[])` seems to resolve the issue.
Closes https://github.com/oracle/graal/issues/5868
> Synchronize accesses to reachability handlers

- substratevm/mx.substratevm/suite.py
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/ResourcesFeature.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/NativeImageResourceFileSystemProviderTest.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/NativeImageResourceTest.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/NativeImageResourceUtils.java
- substratevm/src/com.oracle.svm.test/src/resources/dir with space/.mxkeep
- substratevm/src/com.oracle.svm.with.space.test/src/META-INF/native-image/com.oracle.svm.with.space.test/native-image.properties
- substratevm/src/com.oracle.svm.with.space.test/src/com/oracle/svm/with/space/test/NativeImageResourceTest.java
- substratevm/src/com.oracle.svm.with.space.test/src/com/oracle/svm/with/space/test/NativeImageResourceUtils.java
- substratevm/src/com.oracle.svm.with.space.test/src/resources/resource-in-jar-with-space.txt
Since https://github.com/oracle/graal/pull/7670 it is no longer possible to build projects that include resources from paths with spaces.
How to reproduce:
1. Build graal `master` from source
2. `export GRAALVM_HOME=/path/to/graal/master/build`
3. `git clone https://github.com/quarkusio/quarkus`
4. `cd quarkus`
5. `./mvnw -Dquickly`
6. `./mvnw -Dnative -pl integration-tests/simple\ with\ space -Dnative.surefire.skip -Dformat.skip -Dno-descriptor-tests clean verify -Dquarkus.native.container-build=false`
This PR resolves this issue and adds a set of tests for resource names with spaces (which don't catch the issue at hand, but are still good to test against).
Closes https://github.com/quarkusio/quarkus/issues/36998
> [GR-50220] Allow resources inclusion from jar files in paths containing spaces

- substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/NativeImage.java
`destination` is the classpath GraalVM creates from parsing the jar files passed to it. The ordering of the entries in the classpath is important. Jar files themselves should be added before the entries of their corresponding "Class-Path" attributes.
At the same time we want to process the contents of `META-INF/native-image` of the entries in the "Class-Path" before processing the contents of `META-INF/native-image` of the jar itself. This is required to ensure that the jar `META-INF/native-image` contents can override those of the entries in its "Class-Path".
As a result I chose to optimistically add the path to the classpath (aka `destination`) and remove it afterwards if deemed necessary.
Fixes https://github.com/oracle/graal/issues/7677
The fix should be backported to 23.1 as well
> [GR-50675] Fix class-path order when Manifests include "Class-Path" attributes

- substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/ELFObjectFile.java
This PR addresses cases when GraalVM sometimes generates corrupted debug info by ensuring that  debug sections have alignment set to 1.
Current we mistakenly generate debug info sections with alignment of 8 (for 64-bit OS) and this causes linker to generate corrupt debug info when it has several object files with debug info with different alignment. For example on Alpine Linux crt1.o and crti.o libraries have debug information section with alignment of 1. Linker writes those sections first and then pads to alignment of 8 before processing Graal-generated debug info section because it has alignment of 8.
Evidently calling `newUserDefinedSection` was an oversight as `newDebugSection` method already has a comment on this exact issue:
```
// debugging information is mostly unaligned; padding …
```
>  [GR-50985] Set alignment to 1 for Java DWARF debug info sections

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/JfrFeature.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/Target_jdk_jfr_internal_JVM.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jfr/JfrEventFeature.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jfr/JfrEventSubstitution.java
Some minor house cleaning in 3 areas:
1. Remove the "hack" in JfrEventSubstitution.java. It's no longer needed because JDK code has changed to make `EventWriter.reset()` public.
2. Added javadoc and logging in `Target_jdk_jfr_internal_JVM.java`. Currently, whenever a new JFR @Deprecated event is used an unclear error message is logged:
```
[warn][jfr,setting] Exception occurred when setting value "forRemoval" for class jdk.jfr.internal.Control
Passed
```
One issue is that there may be too much useless logger output that drowns out meaningful logs. A possible solution is to simply log that a feature is unimplemented only once. Instead of logging every time an attempt to use it is made.  What do you think about this?
3. Avoid unnecessary module opening. [This caused issues with …
> Small JFR clean-up

- .github/workflows/quarkus.yml
Quarkus no longer supports JDK 11
See https://github.com/oracle/graal/actions/runs/7162366442/job/19499236553#step:12:2328
> [GR-51017] Use JDK 17 for building Quarkus

- truffle/docs/DynamicObjectModel.md
The other reference to the method is correct, but the call to `layout` was missing here.
> Fix typo in Shape.newBuilder().layout()

- .github/workflows/quarkus.yml
Quarkus integration tests expect a JDK-23-based build of GraalVM
`master`.
> [GR-51276] Use latest labsjdk in Quarkus github workflow

- truffle/docs/LanguageTutorial.md
There is a typo in toc_group. It have to be `truffle`, not the `truffles`.
This causes the sidebar toc to disappear. Fixed it.
> Fix typo in toc_group

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/SubstrateOptions.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/doc-files/FlightRecorderOptionsHelp.txt
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/JfrManager.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/JfrOptionSet.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/SubstrateJVM.java
`-XX:FlightRecorderOptions` can be passed on the command line when launching your app. This PR adds support for the following JFR options in native image: 
- `globalbuffercount`
-  `globalbuffersize`
- `maxchunksize`
- `memorysize`
- `repositorypath`
- `stackdepth`
- `thread_buffer_size`
- `preserveRepository`. 
A few of these options are legacy options are are not very important (although the current OpenJDK still supports them). `maxchunksize`, `repositorypath`,  and`stackdepth` are probably the most useful options and advanced JFR users may find them important.  `preserveRepository` is a new option added to JDK22 via https://github.com/openjdk/jdk/pull/13111. 
See issue: https://github.com/oracle/graal/issues/7546 
In HotSpot, the VM-level JFR options may not be changed after JFR is …
> [GR-51629] Add support for JFR -XX:FlightRecorderOptions

- sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/hosted/RuntimeClassInitialization.java
Document that using `""` as the package name results in all packages and
classes being registered for build time initialization.
> [GR-52129] Augment RuntimeClassInitialization#initializeAtBuildTime javadoc

- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/TestThrottler.java
This PR addresses GH issue: https://github.com/oracle/graal/issues/8401
The test case [`testDistributionHighRate`](https://github.com/oracle/graal/blob/3a131e2f5779742c793d1711cbc04837252ac9d3/substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/TestThrottler.java#L233) fails intermittently due to under-sampling below the allowed error tolerance (2%). This is because the `JfrAdaptiveSampler` [incorporates an element of randomness into the sampling algorithm](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/throttling/JfrAdaptiveSampler.java#L170). All the `testDistribution*` test cases suffer from the same problem because they rely on tolerance values to check the sampling distribution which has some randomness to it. …
> [GR-52295] JFR Throttler Sampling Distribution Test Update

- espresso/src/com.oracle.truffle.espresso.jdwp/src/com/oracle/truffle/espresso/jdwp/impl/JDWP.java
- espresso/src/com.oracle.truffle.espresso/src/com/oracle/truffle/espresso/classfile/ClassfileParser.java
During the parsing of local variable tables in class files, the start byte code index (BCI) and the end BCI between which a local variable is visible are set for each local variable. Local variables are represented with the class `Local` which implements `LocalRef`. The documentation of `LocalRef` implies that local variables are visible from the start BCI (inclusive) to the end BCI (inclusive).
When parsing the class file, the `ClassFileParser` sets the end BCI to the start BCI plus the length for which the variable is visible. According to the [JVM Specification](https://docs.oracle.com/javase/specs/jvms/se14/html/jvms-4.html#jvms-4.7.13), this index (start BCI + length) is exclusive, which contradicts the documentation of `LocalRef`.
This PR aligns the class file parser to the …
> Espresso: Fix parsing of LocalVariableTable and adapt JDWP implementation

- visualizer/IdealGraphVisualizer/VisualizerUI/src/org/graalvm/visualizer/ui/Bundle.properties
Looks like IGV has been [updated to use NetBeans-14](https://github.com/oracle/graal/blob/f105a80046c34cc69b35c1e45227e119cfa2ee80/visualizer/IdealGraphVisualizer/nbproject/platform.properties#L343), however the system is still configured to use _update centers_ from NetBeans 12.5 - that's unfortunate as the latest versions of plugins aren't available. This PR aligns the IGV's base NetBeans version with its update centers.
CCing @tkrodriguez, @sdedic, @dbalek, @Ondrej-Douda
> [GR-52025] Use update center for NetBeans 14 in IGV

- substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/JfrGCHeapSummaryEvent.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/TestGCHeapSummaryEvent.java
Previously, the `jdk.GCHeapSummary` event erroneously reported all the following fields as 0:
1. reservedEnd
2. committedEnd
3. start
4. reservedSize
```
jdk.GCHeapSummary {
startTime = 19:06:03.003 (2024-03-25)
gcId = 0
when = "Before GC"
heapSpace = {
start = 0x00000000
committedEnd = 0x00000000
committedSize = 28.8 MB
reservedEnd = 0x00000000
reservedSize = 0 bytes
}
heapUsed = 28.8 MB
}
```
**Fields 1-3** contain information about the boundaries of the Java heap. These fields make sense in Hotspot because the heap is one contiguous region from which sub-regions are utilized. Fields 1-3  are not applicable in SubstrateVM since heap space is allocated on a chunk-by-chunk basis when it's needed at runtime. These chunks are not a single contiguous region because each chunk corresponds to …
> [GR-52940] Fix reported values in GCHeapSummary JFR event.

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/Target_jdk_jfr_internal_JVM.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/TestContainerEvent.java
Use `PhysicalMemorySupport` to retrieve the total host value. The `PhysicalMemory` class would return the container values.
Closes: #8485
**Testing**
Inside a container with a memory limit of 500MB:
```
jdk.ContainerConfiguration {
startTime = 13:10:55.301
containerType = "cgroupv1"
cpuSlicePeriod = 100 ms
cpuQuota = 300 ms
cpuShares = -1
effectiveCpuCount = 3
memorySoftLimit = -1 byte
memoryLimit = 500.0 MB
swapMemoryLimit = 600.0 MB
hostTotalMemory = 62.6 GB
hostTotalSwapMemory = -1 byte
}
```
On the physical host:
```
jdk.ContainerConfiguration {
startTime = 14:06:32.742
containerType = "cgroupv1"
cpuSlicePeriod = 100 ms
cpuQuota = -0.00100 ms
cpuShares = -1
effectiveCpuCount = 12
memorySoftLimit = -1 byte
memoryLimit = -1 byte
swapMemoryLimit = -1 byte
hostTotalMemory = 62.6 GB …
```
> [GR-52453] Implement jdk.ContainerConfiguration.hostTotalMemory()

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/heap/PhysicalMemory.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/events/EveryChunkNativePeriodicEvents.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/TestEveryChunkNativePeriodicEvents.java
- Add partial support for physical memory usage (if container usage is enabled and linux). 
- Fix bug when reporting physical memory usage in `jdk.PhysicalMemory` JFR event. It will now be set to a valid value or -1 (instead of 0).
- Add tests for `jdk.PhysicalMemory` and other periodic native JFR events.
Note: Eventually, it may be worth adding support in for the case `Containers.isContainerized()` is false. This will require different implementations for different OS. In hotspot, the implmentation for Linux attempts to read `/proc/meminfo `, and if that fails, it tries to read the struct returned from the sysinfo() call.
Related issue: https://github.com/oracle/graal/issues/8486
```
$ mx native-image --install-exit-handlers --enable-monitoring=jfr -m jdk.httpserver
$ ./jdk.httpserver …
```
> [GR-52484] Partial support for physical memory usage (fixes JFR bug) and JFR tests for periodic native events

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/JfrEvent.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/JfrFeature.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/JfrNmtCategorySerializer.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/JfrType.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/events/EveryChunkNativePeriodicEvents.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/events/NativeMemoryUsagePeakEvent.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/events/NativeMemoryUsageTotalPeakEvent.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/nmt/NativeMemoryTracking.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/nmt/NmtMallocMemoryInfo.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/TestNmtEvents.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/utils/JfrFileParser.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/utils/poolparsers/NmtCategoryConstantPoolParser.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/nmt/NativeMemoryTrackingTests.java
This pull request adds JFR events for recently added native memory tracking. 
It also adds tracking of peak malloc usage. Unfortunately, the stock NMT JFR events from the openJDK do not contain peak usage data. So the only way to view the peak usage data is by specifying `-XX:+PrintNMTStatistics` at runtime.  Another possibility is to add Native Image specific `NativeMemoryUsagePeak` events.
See issue: https://github.com/oracle/graal/issues/8452
> [GR-52942] Add JFR events and track peak usage for native memory tracking.

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/SubstrateExitHandlerFeature.java
Currently, Native Image shutdown hooks don't run upon SIGINT unless the hosted option`--install-exit-handlers` is set to true at build time. This is a problem for JFR and NMT that do important work such as dumping stats/recordings on exit.
See issue: https://github.com/oracle/graal/issues/8482
> [GR-52454] Include signal exit handlers in the image build if JFR or NMT is also included

- substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/reports/CallTreePrinter.java
Related issue: #8496
This pull request reworks and simplifies the CSV output format of call graph report, generated by running Native Image with the `-H:+PrintAnalysisCallTree` and `-H:PrintAnalysisCallTreeType=CSV` options.
The new format consists of 3 files:
**call_tree_methods.csv**
```
Id | Name | Type | Parameters | Return | Display | Flags | IsEntryPoint
```
**call_tree_invokes.csv**
```
Id | MethodId | BytecodeIndexes | TargetId | IsDirect
```
**call_tree_targets.csv**
```
InvokeId | TargetId
```
The first two files represent a list of methods and invokes, respectively, while the targets file creates a many-to-many mapping between invokes and target methods. This replaces the original system of direct and virtual nodes and edges. Direct and virtual calls are simply distinguished by …
> Change CSV format of call tree report

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/throttling/JfrAdaptiveSampler.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/throttling/JfrEventThrottler.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/throttling/JfrSamplerWindow.java
- substratevm/src/com.oracle.svm.processor/src/com/oracle/svm/processor/BasedOnJDKFileProcessor.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/TestFlightRecorderEvents.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/TestJdkContainerEvents.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/TestSocketChannelEvents.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/TestSocketEvents.java
1. **Add tests for Java-level JFR events.**  
These events we typically get "for free", but problems related to substitutions can result in them being emitted incorrectly, or not at all. 
4. **Add @BasedOnJdkFile to throttler classes.** 
I'm not sure if its better to annotate each individual method, or simply the whole class. Will this annotation somehow alert us if the relevant code in the JDK changes, or is it just a form of documentation?
> Add Java-level JFR event tests and annotate JfrAdaptiveSampler methods with BasedOnJDKFile

- truffle/mx.truffle/mx_truffle.py
- truffle/mx.truffle/suite.py
- truffle/src/libffi/patches/windows-amd64/0001-Preconfigure-sources-for-x64-Windows-build.patch
Note that this currently prints:
```
Error downloading from https://lafo.ssw.uni-linz.ac.at/pub/graal-external-deps/libffi-3.4.6.tar.gz to /home/zakkak/.mx/cache/LIBFFI_SOURCES_033d2600e879b83c6bce0eb80f69c5f32aa775bf2e962c9d39fbd21226fa19d1e79173d8eaa0d0157014d54509ea73315ad86842356fc3a303c0831c94c6ab39/libffi-sources.tar.gz: HTTP Error 404: Not Found
```
during the build, due to libffi-3.4.6 not being mirrored in https://lafo.ssw.uni-linz.ac.at/pub/graal-external-deps/ but it successfully fetches it from the upstream github repository.
Also note that this **has not been tested on windows**, so the windows patch file might need further adjustments.
Fixes https://github.com/oracle/graal/issues/9123
> Update LIBFFI to 3.4.6

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/JfrFeature.java
Resolves Bug: https://github.com/oracle/graal/issues/8993
If epsilon or G1 GC is used, JFR does not emit any GC collection events. However, we were previously still serializing GC-related constant pools (which are empty in those cases). JFR consumer code, which parses chunks for jfr-streaming, expects these pools to be non-empty. 
This PR is just a small change to exclude those serializers when appropriate.
> [GR-55269] Don't include GC related JFR serializers unless Serial GC is used.

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/JfrTicks.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/thread/PlatformThreads.java
Related issues: https://github.com/oracle/graal/issues/9201 and  https://github.com/oracle/graal/issues/9199
This pull request:
1. Updates JfrTicks to use the new `PlatformTimeUtils.nanosNow()` method. This ensures that [borrowed java-level JDK code](https://github.com/openjdk/jdk/pull/19799/files#diff-c5bdd08f039200bb96baffb6b5ad5716d506c0a53e1f768bf18cb1d6570a4027R340) that uses `JVM.nanosNow()` is using the same clock that we timestamp chunk files with. See [the comment here](https://github.com/openjdk/jdk/pull/19799/files#diff-b7f754817501bf15b4cb8004fc066e46fbd97b30b15ef406aa09fd00ca2e5f14R174). Currently we use `System.currentTimeMillis()` to timestamp chunks, which is a different clock and only has ms precision. This might cause inconsistencies if JDK code uses `JVM.nanosNow()` and …
> [GR-54994] Remove duplicate ThreadSleep JFR events and use nanosNow() to timestamp JFR chunks.

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/events/NativeMemoryUsagePeakEvent.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/events/NativeMemoryUsageTotalPeakEvent.java
This is a small change to add the `@DataAmount` annotation to `jdk.NativeMemoryUsagePeak` and `NativeMemoryUsageTotalPeakEvent` events.  This will allow them to report units with the memory size fields similar to `jdk.NativeMemoryUsage` and `jdk.NativeMemoryUsageTotal`.
------
Before change:
```
$jfr print --events jdk.NativeMemoryUsagePeak recording.jfr 
jdk.NativeMemoryUsagePeak {
startTime = 15:47:35.221 (2024-04-25)
type = "Threading"
peakReserved = 424
peakCommitted = 424
countAtPeak = 4
eventThread = "JFR Shutdown Hook" (javaThreadId = 64)
}
jdk.NativeMemoryUsagePeak {
startTime = 15:47:35.221 (2024-04-25)
type = "Unsafe"
peakReserved = 14336
peakCommitted = 14336
countAtPeak = 2
eventThread = "JFR Shutdown Hook" (javaThreadId = 64)
}
...
```
After change:
``` …
```
> [GR-55268] Report units in custom JFR NMT events.

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/Target_jdk_internal_util_StaticProperty.java
The JDK's StaticProperty class uses a default of the empty string for the java.locale.useOldISOCodes static property. Ensure to also use the empty string as the default in substratevm avoiding the NullPointerException.
Closes: #9526
Testing:
- Passes the provided reproducer in #9526. Throws NPE before.
- Quarkus tests from https://github.com/graalvm/mandrel/issues/778 which triggered this investigation.
> [GR-57624] Fix Locale NPE in JDK 24+10 and better

- substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/HeapChunkProvider.java
- substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/HeapImpl.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/heap/Heap.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/events/EveryChunkNativePeriodicEvents.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/nmt/NativeMemoryTracking.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/nmt/NmtCategory.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/nmt/NmtFeature.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/nmt/NmtVirtualMemoryInfo.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/nmt/NativeMemoryTrackingTests.java
This is a simplified version of https://github.com/oracle/graal/pull/8630 
This PR adds virtual memory tracking, but makes the assumption that virtual memory is used neatly (no overlapping committed regions etc).  Please see the javadoc in `NativeMemoryTracking` for more info.
**Notes:**
There's 3 approaches we could take with this simplified version. 
1. The approach in this PR. This is a middle ground between 2 and 3. Instrument at the caller level (ie in `HeapChunkProvider`). This makes the caller responsible for correct instrumentation.
2. Get rid of "track" methods and `NmtVirtualMemoryInfo`. Instead, directly query `HeapAccounting` whenever we need to report virtual memory. This is probably less extensible than 1 or 3. 
3. Lower level instrumentation of `VirtualMemoryProvider` …
> [GR-57310] NMT simplified virtual memory tracking.

- truffle/src/com.oracle.truffle.runtime/src/com/oracle/truffle/runtime/OptimizedTruffleRuntime.java
- truffle/src/com.oracle.truffle.runtime/src/com/oracle/truffle/runtime/debug/TraceSplittingListener.java
This format is consistent with the format for splits present in the
"[engine] opt" lines when tracing compilation.
Using `--engine.TraceCompilation --engine.TraceSplitting --engine.TraceTransferToInterpreter`
the output changes from
```
[engine] split 297-493b01ef-1     Truffle::RegexpOperations.match_in_region                   |AST   99|Tier 1|Calls/Thres       5/    1|CallsAndLoop/Thres      17/  400|SourceSection /Users/rwstauner/src/truffle-ws/truffleruby/src/main/ruby/truffleruby/core/truffle/regexp_operations.rb~29:881-943
[engine] opt done   id=1722  Truffle::RegexpOperations.match_in_region <split-1722> |Tier 2|Time    90(  42+48  )ms|AST   99|Inlined   2Y   0N|IR    326/   956|CodeSize    3804|Addr 0x11743dcc0|Timestamp 6753643229750|Src regexp_operations.rb:76
[engine] …
```
> Use callTarget.id instead of hashCode in OptimizedTruffleRuntime and TraceSplittingListener

- compiler/src/jdk.graal.compiler/src/jdk/graal/compiler/hotspot/aarch64/AArch64HotSpotNodeLIRBuilder.java
- compiler/src/jdk.graal.compiler/src/jdk/graal/compiler/hotspot/amd64/AMD64HotSpotNodeLIRBuilder.java
- compiler/src/jdk.graal.compiler/src/jdk/graal/compiler/lir/gen/LIRGenerator.java
This is not necessarily a performance issue. Or at least, I didn't check whether this actually leads to the instructions being emitted twice. Though, it violates basic assumptions at the LIR level, for instance, that individual instructions are separate objects.
The indirectly called `emitSaveRegisters(.)` methods already store the instructions.
But just to make sure, I added an assert that they are indeed already added.
This is code that hasn't been touched in years. Though, @tkrodriguez and @rschatz touched related bits (5 and 11 years ago).
For me, it causes issues when trying to revive @zapster's Trace Register Allocator (https://github.com/smarr/truffle/tree/trace-ra) for our work on optimizing the code produced for bytecode loops (without PE).
/cc @davleopo
> Avoid adding same (AArch64|AMD64)SaveRegistersOp object twice to basic block

- .github/workflows/quarkus.yml
Since https://github.com/quarkusio/quarkus/pull/43862 the quarkus nightly builds have started failing (stopped by the watchdog) in the analysis phase of the micrometer-prometheus integration test. The reason appears to be an increase in the memory usage of the Native Image
builder due to the aforementioned change.
Since [Quarkus CI is already using 6g as the max heap size](https://github.com/quarkusio/quarkus/blob/49870be7a5a6188bb33dfa0fd3c2256dbb771454/.github/workflows/ci-actions-incremental.yml#L53). It makes sense to align this workflow with that limit.
FYI @radcortez @geoand
> Increase max heap size of Native Image builder to match Quarkus' CI

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/oldobject/JfrOldObject.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/oldobject/JfrOldObjectSampler.java
Back when the original PR was integrated, we noted that there was probably a problem with how each sample's span was allotted, but we decided to match exactly what Hotspot was doing anyway.  We were previously setting sample span to be the object allocation size. This is wrong because "span" is meant to represent all the allocations that span a period of time (even the ones that got removed from the queue due to GC). This is meant to have the effect of creating an even sampling representation of allocations over time, ex. if a sample's neighbors are removed from the list it should absorb their span and increase in importance so that its less likely to be removed itself. 
Now that the fix is integrated in Hotspot (https://github.com/openjdk/jdk/pull/19334), we should also add the fix in …
> [GR-60079] JFR leak profiler span fixes 

- docs/reference-manual/native-image/DebuggingAndDiagnostics.md
- docs/reference-manual/native-image/JCmd.md
This PR adds some documentation for the new `jcmd` support. This PR should not be merged until after https://github.com/oracle/graal/pull/9963 is integrated.
> Add documentation for `jcmd` support

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/oldobject/JfrOldObjectSampler.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/oldobject/TestOldObjectProfiler.java
A couple small fixes.  To address the errors found here: https://github.com/oracle/graal/pull/10154#issuecomment-2506190888
1. Fix an incorrect assertion. Previously when a younger sample neighbor could not be found, we assumed that the queue was empty. This is not true. It might just be the case that the sample being removed already is the youngest in the queue, so has no younger neighbor. 
2. Initialize JFR before running the JFR leak profiler tests. Please see code comment for explanation.
> [GR-60176] JFR Old Object Sampler fixes

- substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/NativeImage.java
Closes https://github.com/oracle/graal/issues/10008
> [GR-60382] Handle Enable-Native-Access manifest attribute if present

- .github/workflows/quarkus.yml
Reduce the frequency we run the Quarkus tests as they are quite resource hungry and lengthy.
> Run the Quarkus workflow weekly instead of nightly

- compiler/src/jdk.graal.compiler/src/jdk/graal/compiler/truffle/TruffleCompilerImpl.java
- truffle/src/com.oracle.truffle.compiler/src/com/oracle/truffle/compiler/TruffleCompilerListener.java
- truffle/src/com.oracle.truffle.runtime/src/com/oracle/truffle/runtime/debug/TraceCompilationListener.java
- truffle/src/com.oracle.truffle.runtime/src/com/oracle/truffle/runtime/hotspot/libgraal/LibGraalCompilationResultInfo.java
Please consider this patch to make engine trace messages print the compilation ID as part of `opt done` messages. This is useful when correlating the engine trace with HotSpot compilation/deoptimization/etc. messages.
> Include Compilation ID in engine logs.

- compiler/src/jdk.graal.compiler.test/src/jdk/graal/compiler/replacements/test/ArraysFillTest.java
- compiler/src/jdk.graal.compiler.test/src/jdk/graal/compiler/replacements/test/ArraysFillTestConfig.java
- compiler/src/jdk.graal.compiler.test/src/jdk/graal/compiler/replacements/test/ArraysSubstitutionsTestBase.java
- compiler/src/jdk.graal.compiler/src/jdk/graal/compiler/asm/aarch64/AArch64Assembler.java
- compiler/src/jdk.graal.compiler/src/jdk/graal/compiler/core/aarch64/AArch64LIRGenerator.java
- compiler/src/jdk.graal.compiler/src/jdk/graal/compiler/hightiercodegen/NodeLowerer.java
- compiler/src/jdk.graal.compiler/src/jdk/graal/compiler/hotspot/meta/HotSpotHostForeignCallsProvider.java
- compiler/src/jdk.graal.compiler/src/jdk/graal/compiler/hotspot/stubs/IntrinsicStubs.java
- compiler/src/jdk.graal.compiler/src/jdk/graal/compiler/lir/aarch64/AArch64ArrayFillOp.java
- compiler/src/jdk.graal.compiler/src/jdk/graal/compiler/lir/gen/LIRGeneratorTool.java
- compiler/src/jdk.graal.compiler/src/jdk/graal/compiler/replacements/StandardGraphBuilderPlugins.java
- compiler/src/jdk.graal.compiler/src/jdk/graal/compiler/replacements/nodes/ArrayFillNode.java
- compiler/src/org.graalvm.micro.benchmarks/src/micro/benchmarks/ArrayFillBenchmark.java
- substratevm/src/com.oracle.svm.graal/src/com/oracle/svm/graal/stubs/AArch64StubForeignCallsFeature.java
- substratevm/src/com.oracle.svm.graal/src/com/oracle/svm/graal/stubs/SVMIntrinsicStubs.java
Please, consider this patch to intrinsify `Arrays.fill(array, constant)` for `byte`, `short` and `int` on AArch64 backend. The assembly code is a port of the HotSpot assembly for the same intrinsic. Thank you @gergo- for reviewing the draft version of this PR!
The below is a summary of some quick JMH tests that I ran on my dev machine.
```
Instr     Benchmark                       (size)   Mode  Cnt          Score          Error  Units
No        ArrayFillBenchmark.fill_bytes       16  thrpt    5  130,858,263.770 ±  7175243.892  ops/s
Yes       ArrayFillBenchmark.fill_bytes       16  thrpt    5  268,367,821.486 ±  2717945.345  ops/s
No        ArrayFillBenchmark.fill_bytes     1024  thrpt    5    7,284,374.553 ±   131421.427  ops/s
Yes       ArrayFillBenchmark.fill_bytes     1024  thrpt …
```
> Intrinsic for AArch64 Arrays.fill(array, constant)

- substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/NativeImage.java
Closes #10708 
Tested with (which failed earlier):
```
$ mx --primary-suite-path substratevm --no-jlinking build
$ GRAALVM_HOME=$(mx --primary-suite-path substratevm --no-jlinking graalvm-home)
$ $GRAALVM_HOME/bin/native-image --macro:native-image-agent-library
[...]
Top 10 origins of code area:                                Top 10 object types in image heap:
6.81MB java.base                                            2.53MB byte[] for code metadata
1.51MB svm.jar (Native Image)                               1.78MB byte[] for java.lang.String
309.98kB org.graalvm.nativeimage.configure                    1.23MB java.lang.String
235.73kB org.graalvm.nativeimage.agent.tracing              937.73kB com.oracle.svm.core.hub.DynamicHubCompanion
224.31kB jdk.zipfs …
```
> Add nativeimage-libgraal to module path for non-jlinked JDKs

- docs/reference-manual/native-image/guides/build-and-run-native-executable-with-remote-jmx.md
Some parts of the remote JMX docs have gone out-of-date and are now incorrect. We should no longer suggest using `-H:DynamicProxyConfigurationFiles`. In addition, `proxy-config.json` is the wrong file name. Instead, suggest adding reachability-metadata.json to META-INF/native-image. 
Also fix some typographical errors.
> Update remote JMX docs 

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/JfrTypeRepository.java
This is a fix for the bug reported by: https://github.com/oracle/graal/issues/10742
The problem was that, for each class used during the epoch, we only visited its module's classloader (if the class' package and it's module were both non null).  However, later on when serializing classes, we attempt to write the class' classloader.  This classloader is never explicitly visited so may not have been processed.
> [GR-63550] Fix bug in JFR type repository

- visualizer/IdealGraphVisualizer/Data/src/main/java/jdk/graal/compiler/graphio/parsing/BinaryReader.java
- visualizer/IdealGraphVisualizer/Data/src/main/java/jdk/graal/compiler/graphio/parsing/LocationStackFrame.java
- visualizer/IdealGraphVisualizer/Data/src/test/java/org/graalvm/visualizer/data/serialization/lazy/BinaryReaderMockTest.java
- visualizer/IdealGraphVisualizer/JavaSources/src/main/java/org/graalvm/visualizer/source/java/impl/JavaStackProcessor2.java
- visualizer/IdealGraphVisualizer/SourceRepository/src/main/java/org/graalvm/visualizer/source/Location.java
- visualizer/IdealGraphVisualizer/SourceRepository/src/main/java/org/graalvm/visualizer/source/SourceLocationUtils.java
- visualizer/IdealGraphVisualizer/SourceRepository/src/main/java/org/graalvm/visualizer/source/impl/ui/LocationOpener.java
- visualizer/IdealGraphVisualizer/SourceRepository/src/main/java/org/graalvm/visualizer/source/lang/FileStackProcessor.java
- visualizer/IdealGraphVisualizer/SourceRepository/src/main/resources/org/graalvm/visualizer/source/resources/NodePositionOffset.xml
- visualizer/IdealGraphVisualizer/SourceRepository/src/main/resources/org/graalvm/visualizer/source/resources/layer.xml
- visualizer/IdealGraphVisualizer/SourceRepository/src/test/java/org/graalvm/visualizer/source/impl/ui/LocationOpenerTest.java
Enso is trying to [generate IGV graph](https://github.com/enso-org/enso/pull/12061#issuecomment-2598666306) for our internal `IR`:
- https://github.com/enso-org/enso/pull/12061 
We had issues to provide proper `nodeSourceLocation` information. I had to debug visualizer code to find out what's wrong. While doing that I made few fixes. 
-  we were providing `-1` as line location - IGV was then doing nothing - with 75d41ee8179929bdda1c5fed3220e6ef357092ca it at least opens the file
- I was getting `NullPointerException`s so I am adding checks and `assert` to catch that earlier
- Last, but not least: we do provide _start and end_ offsets for Enso nodes. Let's use them!
With these changes IGV picks up `start` and `end` offset from `location` property and is capable to select appropriate source …
> Use offsets from `.bgv` file to select appropriate text

- docs/reference-manual/native-image/BuildOptions.md
- substratevm/src/com.oracle.svm.driver/resources/HelpExtra.txt
`--exclude-config` seems to take a space-separated pair instead of a
comma-separated one.
Thanks to @gsmet for noticing it.
cc @fniephaus @olyagpl
> Docs: Fix `--exclude-config` documentation

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jni/JNILibraryInitializer.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JNIRegistrationAttach.java
related issue: https://github.com/oracle/graal/issues/11103
I resolved an issue where using the attach method in an application built with native-image resulted in the error:
`java.lang.UnsatisfiedLinkError: Can't load library: attach`
---
Additionally, during implementation, I discovered that in applications built with native-image, `VirtualMachine.list()` returns an empty list.
(This was not addressed in this PR.)
> [GR-65559] Add JNI registration Attach API

- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JmxServerFeature.java
This updates the resource bundle registration for the JMX server feature. This is needed to use remote JMX with password authentication. 
This OpenJDK upstream PR resulted in the original resource registration going out-of-date: https://github.com/openjdk/jdk/pull/22774
See this [commit](https://github.com/openjdk/jdk/commit/9a49418138b93bc8ed8879be5c9b9b9c85ef47e1#diff-fa5d9688ee9f2de0d3a71fb84220e8d39a10a196663ce91e8e2cc68430bc1de8R40).
Without this fix the following error can be expected when attempting password authentication: 
```
Exception in thread "main" java.lang.SecurityException: Authentication failed! java.util.MissingResourceException: Can't find bundle for base name sun.security.util.resources.security, locale en_US
at …
```
> Fix bug in JmxServerFeature resource registration

- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/c/util/FileUtils.java
- substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JmxServerFeature.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jmx/JmxTest.java
This is a follow up to this pull request here: https://github.com/oracle/graal/pull/6250
It adds a reflection configuration that was missing, but needed for a JMX client to connect using SSL. The tests have been updated to connect with SSL and password authentication.
I've included dummy password, access, and SSL files required to configure the JMX properties needed for authentication and SSL.
> Remote JMX SSL bug fix and updated tests

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/util/EnvVariableUtils.java
This is a simple fix for #11818 (Required environment variable names use case-sensitive compare on Windows).
The call to mapKey() is inlined into the call to isKeyRequiredCondition().  
Currently this particular call to mapKey() has no effect.
> [GR-68862] Github: [Native Image] [Windows] Required environment variable names use case-sensitive compare on Windows

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/events/ThreadParkEvent.java
- substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/TestOmitInternalParkEvents.java
When synchronization such as monitor enter or wait is used, `Unsafe.park` is used under-the-hood to block threads. This results in not only `jdk.JavaMonitorWait` and `jdk.JavaMonitorEnter` events being emitted, but secondary `jdk.ThreadPark` events being emitted as well. The `jdk.ThreadPark` events are only emitted due to the implementation details of the [`com.oracle.svm.core.monitor.JavaMonitor`](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/monitor/JavaMonitorQueuedSynchronizer.java#L397) and [`com.oracle.svm.core.monitor.JavaMonitorQueuedSynchronizer`](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/monitor/JavaMonitorQueuedSynchronizer.java#L139C17-L139C33) classes. 
In …
> [GR-69121] Skip emission of internal JFR ThreadPark events

- substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/darwin/DarwinSubstitutions.java
In [enso](https://github.com/enso-org/enso), we are building NI from a small JDK created by `jlink`. On latest [GraalVM CE 25.0.0](https://github.com/graalvm/graalvm-ce-builds/releases/tag/jdk-25.0.0), it is no longer possible to build NI from small JDK without `java.prefs` module on MacOS.
Makefile:
```make
NI_BUILDER_MODULES = "org.graalvm.nativeimage.builder,org.graalvm.nativeimage.driver,org.graalvm.nativeimage.librarysupport,org.graalvm.nativeimage.objectfile,org.graalvm.nativeimage.pointsto"
NI_BASE_MODULES = "org.graalvm.nativeimage,org.graalvm.nativeimage.base,com.oracle.graal.graal_enterprise,com.oracle.svm.svm_enterprise"
JDK_MODULES = "java.naming,java.net.http,java.rmi,jdk.attach,jdk.charsets,jdk.crypto.ec,jdk.httpserver,jdk.localedata,jdk.jdwp.agent,jdk.security.auth" …
```
> Substitution fails during NI build when `java.prefs` module is not present
