truffle/com.oracle.truffle.tck/src/com/oracle/truffle/tck/ComplexNumbersB.java

Fix ForeignAccess of ComplexNumbersB

---

truffle/com.oracle.truffle.api.interop/snapshot.sigtest
truffle/com.oracle.truffle.api.profiles/snapshot.sigtest
truffle/com.oracle.truffle.api.vm/snapshot.sigtest
truffle/com.oracle.truffle.api/snapshot.sigtest
truffle/com.oracle.truffle.tck/snapshot.sigtest

sigtest files updated before tagging. Need to push them. Then I need to propagate the truffle-0.11 tag...

Snapshot of Truffle APIs as of truffle-0.11 release

---

mx.truffle/suite.py

This helps mx create valid pom files.

Add explicit SCM metadata

---

truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/debug/Breakpoint.java

Impacts only Javadoc, but still.

Importing truffle instrument rather than midi one

---

truffle/com.oracle.truffle.api.instrumentation.test/src/com/oracle/truffle/api/instrumentation/examples/DebuggerController.java
truffle/com.oracle.truffle.api.instrumentation.test/src/com/oracle/truffle/api/instrumentation/examples/DebuggerExample.java
truffle/com.oracle.truffle.api.instrumentation.test/src/com/oracle/truffle/api/instrumentation/examples/DebuggerExampleTest.java
truffle/com.oracle.truffle.api.instrumentation/src/com/oracle/truffle/api/instrumentation/InstrumentationHandler.java
truffle/com.oracle.truffle.api.instrumentation/src/com/oracle/truffle/api/instrumentation/TruffleInstrument.java
truffle/com.oracle.truffle.api.vm/src/com/oracle/truffle/api/vm/PolyglotEngine.java
truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/TruffleLanguage.java
truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/impl/Accessor.java

Giving TruffleInstrument a chance to provide multiple services when its onCreate method is called.

TruffleInstrument can provide services

---

truffle/com.oracle.truffle.api.dsl/src/com/oracle/truffle/api/dsl/TypeSystem.java

Add a default value of an empty array to TypeSystem.

---

truffle/com.oracle.truffle.api.debug/src/com/oracle/truffle/api/debug/Debugger.java
truffle/com.oracle.truffle.sl.test/src/com/oracle/truffle/sl/test/SLDebugTest.java
truffle/com.oracle.truffle.sl/src/com/oracle/truffle/sl/nodes/SLStatementNode.java
truffle/com.oracle.truffle.sl/src/com/oracle/truffle/sl/parser/SLNodeFactory.java

Squashed version of https://github.com/graalvm/truffle/pull/74

Fix SLDebugTest; Extend SLDebugTest.

---

truffle/com.oracle.truffle.api.interop.java/src/com/oracle/truffle/api/interop/java/JavaInteropLanguage.java

Please review, @grimmerm, thanks.

JavaInteropLanguage shouldn't be public

---

CONTRIBUTING.md
README.md

Introducing trivial/complex/no API change and related reviews: fast-track/standard one.

Describing fast/standard review

---

truffle/com.oracle.truffle.tools.debug.shell/src/com/oracle/truffle/tools/debug/shell/server/InstrumentationUtils.java
truffle/com.oracle.truffle.tools.debug.shell/src/com/oracle/truffle/tools/debug/shell/server/REPLHandler.java
truffle/com.oracle.truffle.tools.debug.shell/src/com/oracle/truffle/tools/debug/shell/server/REPLServer.java

Clean up AST printing, use temporary "known tags" strategy to replace former functionality

Debug: update node visualizing support

---

truffle/com.oracle.truffle.api.debug/src/com/oracle/truffle/api/debug/SuspendedEvent.java
truffle/com.oracle.truffle.tools.debug.shell/src/com/oracle/truffle/tools/debug/shell/client/REPLClientContext.java
truffle/com.oracle.truffle.tools.debug.shell/src/com/oracle/truffle/tools/debug/shell/client/REPLRemoteCommand.java
truffle/com.oracle.truffle.tools.debug.shell/src/com/oracle/truffle/tools/debug/shell/client/SimpleREPLClient.java
truffle/com.oracle.truffle.tools.debug.shell/src/com/oracle/truffle/tools/debug/shell/server/REPLHandler.java
truffle/com.oracle.truffle.tools.debug.shell/src/com/oracle/truffle/tools/debug/shell/server/REPLServer.java

Remove the need for debugger clients to explicitly use KillException.
@chumer please also review

Add method SuspendedEvent.kill()

---

.travis.yml
truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/instrument/impl/DefaultVisualizer.java
truffle/com.oracle.truffle.dsl.processor/src/com/oracle/truffle/dsl/processor/AnnotationProcessor.java
truffle/com.oracle.truffle.dsl.processor/src/com/oracle/truffle/dsl/processor/InstrumentableProcessor.java
truffle/com.oracle.truffle.dsl.processor/src/com/oracle/truffle/dsl/processor/verify/VerifyTruffleProcessor.java

Truffle shall be compilable on JDK7

---

truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/impl/TVMCI.java

Addressing Andreas @woess comment from https://github.com/graalvm/truffle/pull/139/files/1d5d746c019e29b1e3359e6183c07f2bd0533b0f#r57309881

Removing outdated comment

---

truffle/com.oracle.truffle.api.debug/snapshot.sigtest
truffle/com.oracle.truffle.api.dsl/snapshot.sigtest
truffle/com.oracle.truffle.api.instrumentation/snapshot.sigtest
truffle/com.oracle.truffle.api.interop.java/snapshot.sigtest
truffle/com.oracle.truffle.api.interop/snapshot.sigtest
truffle/com.oracle.truffle.api.object.dsl/snapshot.sigtest
truffle/com.oracle.truffle.api.object/snapshot.sigtest
truffle/com.oracle.truffle.api.profiles/snapshot.sigtest
truffle/com.oracle.truffle.api.test/snapshot.sigtest
truffle/com.oracle.truffle.api.vm/snapshot.sigtest
truffle/com.oracle.truffle.api/snapshot.sigtest
truffle/com.oracle.truffle.tck/snapshot.sigtest
truffle/com.oracle.truffle.tools.debug.shell/snapshot.sigtest

Created as
```bash
$ git checkout truffle-0.13
$ mx build
$ mx sigtest --generate
```
and then I integrated all `.sigtest` files into master.

Snapshot of Truffle API at truffle-0.12 released version

---

truffle/com.oracle.truffle.api.debug/src/com/oracle/truffle/api/debug/BreakpointFactory.java

This change fixes a race between the construction of a `BreakpointImpl` object and its access from another listener thread. This can happen easily if another thread related to a debugger UI creates a breakpoint while a program is executing.
Details:
- make BreakpointListener static class, because letting `this` escape to another thread during construction is just evil: I can't see that race when looking at the code
- use factory method for BreakpointImpl construction to register listener after object creation
- this relies on JVM semantics that ensures that all object fields are visible after object construction, in case at least one of the fields in final. Otherwise, we'd need to make the racy fields volatile.
- make assumption fields `@CompilationFinal` otherwise they are not properly …

Fix race condition between Breakpoint construction and access from listeners

---

truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/nodes/Node.java

This is something that came up as a question on the gitter channel. Seems worthwhile documenting.
/cc @jtulach

Document that @Child and @Children imply @CompilationFinal

---

truffle/com.oracle.truffle.api.instrumentation/src/com/oracle/truffle/api/instrumentation/StandardTags.java

Elaborate the intuition required for tagging nodes and give an example for the debugger.

Clarify StatementTag semantics

---

compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/meta/HotSpotSnippetReflectionProvider.java
compiler/src/org.graalvm.compiler.lir/src/org/graalvm/compiler/lir/LIRIntrospection.java
compiler/src/org.graalvm.compiler.lir/src/org/graalvm/compiler/lir/constopt/ConstantTree.java
compiler/src/org.graalvm.compiler.nodeinfo.processor/src/org/graalvm/compiler/nodeinfo/processor/GraphNodeProcessor.java
compiler/src/org.graalvm.compiler.phases.common/src/org/graalvm/compiler/phases/common/ProfileCompiledMethodsPhase.java
truffle/src/com.oracle.truffle.api.dsl/src/com/oracle/truffle/api/dsl/Introspection.java
truffle/src/com.oracle.truffle.api/src/com/oracle/truffle/api/TruffleLanguage.java
truffle/src/com.oracle.truffle.dsl.processor/src/com/oracle/truffle/dsl/processor/verify/VerifyTruffleProcessor.java

Hello!
There are fixes to some problems found by static analysis which looks as clear bugs/misprints.
OCA signed ( http://www.oracle.com/technetwork/community/oca-486395.html#v -- Tagir Valeev )

Fixing bugs found by static analysis

---

compiler/src/org.graalvm.compiler.replacements/src/org/graalvm/compiler/replacements/StandardGraphBuilderPlugins.java

Minimal intrinsic support for Math./dec/inc/rementExact.
(Primarily testing account setup and work-flow.)

JDK-8193241: Part 1. Added intrinsic support for (Math) dec/incrementExact

---

compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64Assembler.java

This just adds the LDADD instruction to the AArch64 implementation.

Add the LDADD instruction to the AArch64 implementation

---

compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64Address.java
compiler/src/org.graalvm.compiler.asm.sparc/src/org/graalvm/compiler/asm/sparc/SPARCAssembler.java
compiler/src/org.graalvm.compiler.core.sparc/src/org/graalvm/compiler/core/sparc/SPARCLIRGenerator.java
compiler/src/org.graalvm.compiler.debug/src/org/graalvm/compiler/debug/TimerKeyImpl.java
compiler/src/org.graalvm.compiler.lir/src/org/graalvm/compiler/lir/SwitchStrategy.java
compiler/src/org.graalvm.compiler.lir/src/org/graalvm/compiler/lir/alloc/trace/GlobalLivenessAnalysisPhase.java
compiler/src/org.graalvm.compiler.lir/src/org/graalvm/compiler/lir/profiling/MethodProfilingPhase.java
compiler/src/org.graalvm.compiler.lir/src/org/graalvm/compiler/lir/profiling/MoveProfilingPhase.java
compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/AbstractBeginNode.java
compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/InliningLog.java
compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/debug/WeakCounterNode.java
compiler/src/org.graalvm.compiler.options/src/org/graalvm/compiler/options/EnumOptionKey.java
compiler/src/org.graalvm.compiler.phases.common/src/org/graalvm/compiler/phases/common/FloatingReadPhase.java
compiler/src/org.graalvm.compiler.phases/src/org/graalvm/compiler/phases/BasePhase.java

experimenting w/ using [error-prone](http://errorprone.info) for `jdk/jdk` repo, I got a number of reports for `jdk.compiler` module. this PR fixes some (most straightforward and less invasive) of them.

fix some warnings found by error prone

---

substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/JavaNetNetUtil.java
substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/PosixJavaNetSubstitutions.java

Relates to https://github.com/oracle/graal/issues/596

Hopefully actually pretty good attempt at getting Datagram sockets to work.

---

substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/JavaNetNetUtil.java
substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/PosixJavaNetSubstitutions.java

Let's keep on trucking.
I tried `mx checkstyle` which produced output as it ran, but indicated no errors. But I feel like I'm not looking in the right location.
In general, attempted to learn from prior mistakes, so hopefully this PR will be smoother than the last.

PlainDatagramSocketImpl.socketSetOption0(...)

---

.travis.yml

see https://github.com/oracle/graal/issues/634

Run `mx native-unittest` in graal travis CI

---

compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64MacroAssembler.java
compiler/src/org.graalvm.compiler.core.aarch64.test/src/org/graalvm/compiler/core/aarch64/test/AArch64AddSubShiftTest.java
compiler/src/org.graalvm.compiler.core.aarch64.test/src/org/graalvm/compiler/core/aarch64/test/AArch64MNegTest.java
compiler/src/org.graalvm.compiler.core.aarch64.test/src/org/graalvm/compiler/core/aarch64/test/AArch64MatchRuleTest.java
compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64ArithmeticLIRGenerator.java
compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64NodeMatchRules.java
compiler/src/org.graalvm.compiler.core.amd64.test/src/org/graalvm/compiler/core/amd64/test/AMD64MatchRuleTest.java
compiler/src/org.graalvm.compiler.core.test/src/org/graalvm/compiler/core/test/MatchRuleTest.java
compiler/src/org.graalvm.compiler.core/src/org/graalvm/compiler/core/gen/NodeLIRBuilder.java
compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64ArithmeticOp.java

The patch replies on another one under review https://github.com/oracle/graal/pull/781

Add MNeg rule for AArch64

---

compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64MacroAssembler.java
compiler/src/org.graalvm.compiler.core.aarch64.test/src/org/graalvm/compiler/core/aarch64/test/AArch64AddSubShiftTest.java
compiler/src/org.graalvm.compiler.core.aarch64.test/src/org/graalvm/compiler/core/aarch64/test/AArch64LogicShiftTest.java
compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64ArithmeticLIRGenerator.java
compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64LIRGenerator.java
compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64NodeMatchRules.java
compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64ArithmeticOp.java

This patch depends on PR https://github.com/oracle/graal/pull/781.

Add "logicShift" match rule for AArch64.

---

compiler/src/org.graalvm.compiler.replacements.test/src/org/graalvm/compiler/replacements/test/StringCompressInflateTest.java

Fix to test-case causing a Tier4 assertion failure.

[JDK-8214947] Assertion error in test: StringCompressInflateTest

---

sulong/projects/com.oracle.truffle.llvm.nodes/src/com/oracle/truffle/llvm/nodes/intrinsics/c/LLVMCMathsIntrinsics.java
sulong/projects/com.oracle.truffle.llvm.parser.factories/src/com/oracle/truffle/llvm/parser/factories/BasicIntrinsicsProvider.java
sulong/projects/com.oracle.truffle.llvm.parser.factories/src/com/oracle/truffle/llvm/parser/factories/BasicNodeFactory.java
sulong/tests/com.oracle.truffle.llvm.tests.sulong/c/builtin_gcc/__builtin_fmax.c
sulong/tests/com.oracle.truffle.llvm.tests.sulong/c/builtin_gcc/__builtin_fmaxf.c
sulong/tests/com.oracle.truffle.llvm.tests.sulong/c/builtin_gcc/__builtin_fmin.c
sulong/tests/com.oracle.truffle.llvm.tests.sulong/c/builtin_gcc/__builtin_fminf.c

Add support for llvm.minnum and llvm.maxnum intrinsics

---

substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/hub/DynamicHub.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/Target_java_lang_Module.java

Class.getModule() now works, but --report-unsupported-elements-at-runtime needs to be added when building image

temp fix for #975 create a single module

---

substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageGeneratorRunner.java

Swap order of compilationExecutor and analysisExecutor

---

substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/annotation/AnnotationSupport.java

This fixes #968 and #996. Explanation is in #996

Add missing annotation constructor substitution

---

sulong/projects/com.oracle.truffle.llvm.nodes/src/com/oracle/truffle/llvm/nodes/intrinsics/rust/LLVMStart.java

Fix support for Rust 1.33.0

---

docs/Publications.md

Publications related to Truffle and Graal from the University of Manchester and Edinburgh added to the  general list of publications

Related publications to Graal and Truffle added

---

substratevm/src/com.oracle.svm.native.libchelper/src/cSunMiscSignal.c

Fixes #841.  This should take care of AWS signal handling problems by using `sem_init` only on platforms conforming to POSIX.2001 and later.

Allow signal handler to work on AWS

---

compiler/mx.compiler/suite.py
compiler/src/org.graalvm.compiler.core.llvm/src/org/graalvm/compiler/core/llvm/LLVMGenerator.java
compiler/src/org.graalvm.compiler.core.llvm/src/org/graalvm/compiler/core/llvm/LLVMIRBuilder.java
compiler/src/org.graalvm.compiler.replacements.aarch64/src/org/graalvm/compiler/replacements/aarch64/AArch64GraphBuilderPlugins.java
sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/Platform.java
substratevm/mx.substratevm/suite.py
substratevm/src/com.oracle.svm.core.graal.llvm/src/com/oracle/svm/core/graal/llvm/LLVMFeature.java
substratevm/src/com.oracle.svm.core.graal.llvm/src/com/oracle/svm/core/graal/llvm/LLVMNativeImageCodeCache.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageGenerator.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/code/SubstrateLIRBackendFeature.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageCodeCache.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageCodeCacheFactory.java

add emitCountLeading/TrailingZeros
pass targetPlatform to compiler/optimizer
don't use plugins for String operations
don't use statepoints
create maven artifacts for llvm jars

build using LLVM backend for DARWIN_AArch64

---

compiler/src/org.graalvm.compiler.virtual/src/org/graalvm/compiler/virtual/phases/ea/GraphEffectList.java

This fixes issue #1275 (https://github.com/oracle/graal/issues/1275)
In Graal, nodes with potential runtime exception (like SignedRemNode)
should have Java source position bound. And this position information
should be well propagated when lowering or canonicalizing a node. But
in the PartialEscapePhase, when replacing nodes to new ones, position
information is lost.
This patch surrounds node replacement code in GraphEffectList.java with
the graph.withNodeSourcePosition() call to make sure we won't lose the
source position info from the old node.
Change-Id: Ife36ebe1ea847382c26ec6d66e93a3f49ef97d15

Fix missing source position issue.

---

substratevm/src/com.oracle.svm.reflect/src/com/oracle/svm/reflect/target/Target_jdk_internal_misc_Unsafe_Reflection.java

Add objectFieldOffset method for Class, name pair

---

substratevm/src/com.oracle.svm.core.posix.jdk11/src/com/oracle/svm/core/posix/Target_java_io_UnixFileSystem.java

Java 11: Add java.io.UnixFileSystem.getNameMax0 implementation

---

substratevm/src/com.oracle.svm.core.posix.jdk11/src/com/oracle/svm/core/posix/jdk11/PosixJavaNIOSubstitutions.java
substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/headers/Fcntl.java

Fixes #1486: FileDispatcherImpl.setDirect0(...)

---

substratevm/src/com.oracle.svm.core.posix.jdk11/src/com/oracle/svm/core/posix/jdk11/darwin/Target_jdk_net_MacOSXSocketOptions.java
substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/headers/NetinetTcp.java

- TCP_KEEPALIVE (~TCP_KEEPIDLE)
- TCP_KEEPINTVL
- TCP_KEEPCNT

Fixes #1491 - MacOSXSocketOptions implementations

---

substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/PosixJavaNIOSubstitutions.java
substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/linux/LinuxNIOSubstitutions.java

Add EPoll support under Java 11

---

substratevm/src/com.oracle.svm.core.posix.jdk11/src/com/oracle/svm/core/posix/Target_java_net_AbstractDatagramSocketImpl_JDK11OrLater.java

Implement AbstractPlainDatagramSocketImpl.isReusePortAvailable0()

---

substratevm/src/com.oracle.svm.core.posix.jdk11/src/com/oracle/svm/core/posix/jdk11/darwin/Target_jdk_net_MacOSXSocketOptions.java
substratevm/src/com.oracle.svm.core.posix.jdk11/src/com/oracle/svm/core/posix/jdk11/linux/Target_jdk_net_LinuxSocketOptions.java
substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/headers/NetinetTcp.java

JDK11: LinuxSocketOptions implementations

---

compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/replacements/NewObjectSnippets.java
compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/java/AbstractNewObjectNode.java
compiler/src/org.graalvm.compiler.replacements/src/org/graalvm/compiler/replacements/DefaultJavaLoweringProvider.java

https://github.com/oracle/graal/issues/1504

Emit a single STORE_STORE barrier for allocations

---

substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JDKLibZipSubstitutions.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JNIRegistrationJavaNet.java

JDK 11 has different fields than JDK 8

---

substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/PosixJavaNetSubstitutions.java
substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/headers/NetIf.java
substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/NetworkInterfaceTest.java

Fixes #1522 
Additional constants and a test included.

Fixes #1522 -- Add NetworkInterface.isUp0()

---

truffle/src/com.oracle.truffle.api.dsl/src/com/oracle/truffle/api/dsl/ReportPolymorphism.java

This should make it easier to find `ReportingPolymorphism.md` when looking at `@ReportPolymorphism`.

Add link to ReportingPolymorphism.md [ci skip]

---

truffle/src/com.oracle.truffle.sl/src/com/oracle/truffle/sl/nodes/local/SLReadLocalVariableNode.java

Simplify SLReadLocalVariableNode

---

compiler/src/org.graalvm.compiler.truffle.runtime/src/org/graalvm/compiler/truffle/runtime/TruffleSplittingStrategy.java

Sort TruffleTraceSplittingSummary by value

---

substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageOptions.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/c/NativeLibraries.java

Ignore missing static libs if -H:+ExitAfterRelocatableFileWrite is set.

---

sdk/src/org.graalvm.home/src/META-INF/native-image/org.graalvm.home/native-image.properties

Fixes https://github.com/oracle/graal/issues/1889
The commit here moves the `HomeFinderFeature` from `sdk` project to the `substratevm` project and marks that class as a `AutomaticFeature`. The move from `sdk` to `substratevm` was necessary so that it could reference the `@AutomaticFeature` annotation.
Just like I noted in https://github.com/oracle/graal/issues/1855, I'm actually a bit surprised that the existing test cases did not catch this issue. In fact, there's a `org.graalvm.home.test.VersionTest` in `sdk` project which fails with the exact same exception as reported in https://github.com/oracle/graal/issues/1889 when run as `mx native-unittest org.graalvm.home.test.VersionTest` (I didn't even know there's a `native-unittest` goal/target in the mx build but just happened to find it …

Enable HomeFinderFeature as part of Graal SDK

---

truffle/src/com.oracle.truffle.api/src/com/oracle/truffle/api/TruffleFile.java

Fix documented return value

---

sdk/mx.sdk/mx_sdk_vm.py

With [JDK-8232080](https://bugs.openjdk.java.net/browse/JDK-8232080) in progress of being backported to OpenJDK 11u the graal CE build with native image support is bound to fail. Failure looks like:
```
[Creating JDK image in /disk/graal/upstream-sources/graal/sdk/mxbuild/linux-amd64/graalvm-jimage]
/disk/openjdk/upstream-sources/openjdk-11-dev/build/linux-x86_64-normal-server-release/images/graal-builder-jdk/bin/jlink --add-modules=com.oracle.graal.graal_enterprise,java.base,java.compiler,java.datatransfer,java.desktop,java.instrument,java.logging,java.management,java.management.rmi,java.naming,java.net.http,java.prefs,java.rmi,java.scripting,java.se,java.security.jgss,java.security.sasl,java.smartcardio,java.sql,java.sql.rowset,java.transaction.xa,java.xml,java.xml.crypto,jdk.accessibili …
```

Allow building with OpenJDK 11u and vendor jlink plugins

---

substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/FileSystemProviderSupport.java

Fix relative paths on Windows on JDK 11

---

substratevm/src/com.oracle.svm.agent/src/com/oracle/svm/agent/BreakpointInterceptor.java

Initializing class in Agent when a java.lang.Class.forName is intercepted may lead to missing cathes of reflection, jni, proxy and resources invoked inside target class' static initializer.
This PR can fix the issue https://github.com/oracle/graal/issues/2335.

Not initialize class in Agent

---

substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/Target_java_lang_ClassLoader.java

Fix for https://github.com/oracle/graal/issues/2367

Support ClassLoader.createOrGetClassLoaderValueMap()

---

substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/ReferenceObjectProcessing.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/heap/Target_java_lang_ref_Reference.java

Fix pending reference list corruption during discovery.

---

substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/classinitialization/ClassInitializationFeature.java

Some NCDE errors can appear when trying to use a graalvm built with OpenJDK 11 to build native images.   
This is due to OpenJDK 11 using JVMCI code that relies on Class.getDeclaredMethods as opposed to using JDK 13+ JVMCI code present in Labs JDK.
The code below catches those NCDE and reports them in a way that we can see which type is the one that contains the import that's causing the issues. 
For more details see https://github.com/quarkusio/quarkus/issues/8081

Capture NoClassDefFoundError and report with source type

---

substratevm/mx.substratevm/suite.py
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageGeneratorRunner.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/agent/ClassInitializationTrackingVisitor.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/agent/NativeImageBytecodeInstrumentationAgent.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/agent/jdk8/lambda/LambdaMetaFactoryRewriteVisitor.java

This PR addresses https://github.com/oracle/graal/issues/2528#issuecomment-638300151

[GR-23944] Eliminate com.oracle.svm.hosted dependency to mx:ASM_7.1.

---

substratevm/src/com.oracle.svm.agent/src/com/oracle/svm/agent/restrict/ProxyAccessVerifier.java
substratevm/src/com.oracle.svm.configure/src/com/oracle/svm/configure/filters/FilterConfigurationParser.java
substratevm/src/com.oracle.svm.configure/src/com/oracle/svm/configure/trace/ReflectionProcessor.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/configure/ConfigurationParser.java

Apply access filter to proxy interfaces.

---

substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/GreyToBlackObjectVisitor.java
substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/HeapImpl.java
substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/HeapVerifier.java
substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/ImageHeapInfo.java
substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/ImageHeapWalker.java
substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/LinearImageHeapAllocator.java
substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/LinearImageHeapLayouter.java
substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/LinearImageHeapPartition.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/image/AbstractImageHeapLayouter.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/image/ImageHeapLayoutInfo.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/image/ImageHeapPartition.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/os/AbstractCommittedMemoryProvider.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/os/OSCommittedMemoryProvider.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageGenerator.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/code/amd64/AMD64HostedPatcher.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeBootImage.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageHeap.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageHeapWriter.java

Unified continuous image heap layout.

---

substratevm/src/com.oracle.svm.core.graal.aarch64/src/com/oracle/svm/core/graal/aarch64/SubstrateAArch64Backend.java

When updating the VMThread status a barrier should be present to ensure
all prior stores are visible to other threads. Failure to do so can
result in the garbage collector observing stale values.

AArch64: use stlr for VMThread status update

---

substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/SubstrateOptions.java

Make -g an alias for -H:GenerateDebugInfo=2

---

substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/substitute/UnsafeAutomaticSubstitutionProcessor.java

- If a class is substituted, avoid doing any of the work.
- If an unsafe usage is purely local, it's not a warning.

Better analysis for Unsafe automatic substitutions.

---

substratevm/ci_includes/gate.hocon
substratevm/mx.substratevm/mx_substratevm.py
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/SubstrateOptions.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeBootImage.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeBootImageViaCC.java

Fixes https://github.com/oracle/graal/issues/2639

Remove text relocations if UseOnlyWritableBootImageHeap flag is set

---

substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/SecurityServicesFeature.java

Consider the following very trivial Java program:
```
import java.net.URL;
import java.io.InputStream;
import java.net.*;
import java.io.*;
public class HelloWorld {
public static void main(String[] args) throws Exception { 
System.out.println("Hello World"); 
System.getProperties().list(System.out);
final URL targetURL = new URL("https://google.com/");
HttpURLConnection responseConnection = (HttpURLConnection) targetURL.openConnection();
System.out.println("Connected to target");
try (final InputStream is = responseConnection.getInputStream()) {
is.read();
}
System.out.println("Done");
} 
}
```
which just connects using `HTTPS` to some website and reads the stream.
Let's assume that we generate a native image out of this application
The …

Make sure SSL logging (configured using javax.net.debug) works in native application

---

substratevm/mx.substratevm/rebuild-images.cmd
substratevm/mx.substratevm/rebuild-images.sh

See https://github.com/oracle/graal/issues/2717#issuecomment-664998934

Ensure custom_args are passed after all other args

---

substratevm/mx.substratevm/testhello.py
substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/ClassEntry.java
substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/DebugInfoBase.java
substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/FileEntry.java
substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/Range.java
substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfInfoSectionImpl.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageDebugInfoProvider.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/sources/SourceCache.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/sources/SourceCacheType.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/sources/SourceManager.java

 Remove jdk, graal, and src subdirectories from sources cache 

---

substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/SystemPropertiesSupport.java
substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/NativeImage.java

There is a typo in conditions, founded by https://github.com/oracle/graal/commit/5d2997a9ac8cafdfc6b5c316532165839ad7d1af#commitcomment-43752175

Fixed typo in conditions

---

sulong/projects/com.oracle.truffle.llvm.libraries.native/src/posix.c

Fix some warnings in Sulong that I see on macOS.

Fix some warnings in Sulong

---

substratevm/NativeImageMavenPlugin.md
substratevm/src/native-image-maven-plugin/pom_template.xml
substratevm/src/native-image-maven-plugin/src/main/java/com/oracle/substratevm/NativeImageMojo.java

Make `buildArgs` a list to allow reusability from parent POMs

---

.github/workflows/main.yml
.travis.yml

Migrate to GH actions

---

substratevm/DynamicProxy.md
substratevm/JNI.md
substratevm/Limitations.md
substratevm/Reflection.md
substratevm/Resources.md
substratevm/src/com.oracle.svm.agent/src/com/oracle/svm/agent/NativeImageAgent.java
substratevm/src/com.oracle.svm.reflect/src/com/oracle/svm/reflect/target/Target_jdk_internal_misc_Unsafe_Reflection.java

Please note that this PR is a superset of #3002, which reports the broken link in one file only.

Fix broken links to document on build configuration

---

docs/Publications.md

[docs] Add recent publications

---

substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/snippets/SubstrateGraphBuilderPlugins.java

make awt invocation plugin conditional on linux os

---

compiler/docs/Debugging.md
truffle/docs/Optimizing.md

https://github.com/Shopify/truffleruby/issues/1

Update documentation for using the C1 Visualizer for Truffle

---

substratevm/mx.substratevm/mx_substratevm.py
substratevm/mx.substratevm/testhello.py

A simple tweak to the python driver and gdb test scripts to run mx  debuginfotest twice, with and without isolates.

Run debuginfotest with and without SpawnIsolates

---

substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JDK11_0_10OrEarlier.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JDK11_0_11OrLater.java
substratevm/src/com.oracle.svm.methodhandles/src/com/oracle/svm/methodhandles/Target_java_lang_invoke_MethodHandles_Lookup.java

Fix native-image-agent-library macro build with JDK 11.0.11 EA

---

compiler/src/org.graalvm.compiler.core.test/src/org/graalvm/compiler/core/test/AbsCanonicalizationTest.java
compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/calc/AbsNode.java

- Adds an extra canonicalization to AbsNode with NegateNode inputs.
- Fixed an incorrect return value in create factory method.

Improve AbsNode canonicalization

---

substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfAbbrevSectionImpl.java

added terminating abbrev record to list of abbreviations

---

substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/NativeImage.java

Fix for https://github.com/oracle/graal/issues/3437

[GR-31708] Append customJavaArgs after JavaArgs consolidation.

---

substratevm/src/com.oracle.svm.jfr/src/com/oracle/svm/jfr/JfrEventSubstitution.java

Fall back to getMetaspacePointer() in JfrEventSubstitution

---

substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/SecurityServicesFeature.java

This PR adds support to statically link `sunmscapi`, required for the `sun_security_mscapi` package.
First of all, this still has a **critical issue** that needs to be taken care of before it would be ready to merge.
Additionally, some extra JNI configuration can be added, and the reachability handler can be refined.
The critical issue with this addition, happens when both `sunmscapi` and `sunec` are added:
`sunec.lib(ECC_JNI.obj) : error LNK2005: ThrowException already defined in sunmscapi.lib(security.obj)`
The offending definitions:
https://github.com/graalvm/labs-openjdk-11/blob/0cbcc0176b3404262b95c180ea716e9b0cdeccf6/src/jdk.crypto.mscapi/windows/native/libsunmscapi/security.cpp#L132
https://github.com/graalvm/labs-openjdk-11/blob/0cbcc0176b3404262b95c180ea716e9b0cdeccf6/src/jdk.cryp …

statically link sunmscapi

---

substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfAbbrevSectionImpl.java
substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfDebugInfo.java
substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfFrameSectionImpl.java
substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfInfoSectionImpl.java
substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfLineSectionImpl.java
substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfSectionImpl.java
substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfStrSectionImpl.java

This is a proposed fix for issue #3586

Write DWARF string text as UTF8 rather than ASCII

---

sulong/projects/com.oracle.truffle.llvm.parser/src/com/oracle/truffle/llvm/parser/LLVMParser.java
sulong/projects/com.oracle.truffle.llvm.parser/src/com/oracle/truffle/llvm/parser/LLVMParserRuntime.java
sulong/projects/com.oracle.truffle.llvm.parser/src/com/oracle/truffle/llvm/parser/model/symbols/globals/GlobalAlias.java
sulong/projects/com.oracle.truffle.llvm.parser/src/com/oracle/truffle/llvm/parser/nodes/LLVMSymbolReadResolver.java
sulong/projects/com.oracle.truffle.llvm.runtime/src/com/oracle/truffle/llvm/runtime/CommonNodeFactory.java
sulong/projects/com.oracle.truffle.llvm.runtime/src/com/oracle/truffle/llvm/runtime/LLVMAlias.java
sulong/projects/com.oracle.truffle.llvm.runtime/src/com/oracle/truffle/llvm/runtime/LLVMElemPtrSymbol.java
sulong/projects/com.oracle.truffle.llvm.runtime/src/com/oracle/truffle/llvm/runtime/LLVMFunction.java
sulong/projects/com.oracle.truffle.llvm.runtime/src/com/oracle/truffle/llvm/runtime/LLVMScope.java
sulong/projects/com.oracle.truffle.llvm.runtime/src/com/oracle/truffle/llvm/runtime/LLVMSymbol.java
sulong/projects/com.oracle.truffle.llvm.runtime/src/com/oracle/truffle/llvm/runtime/global/LLVMGlobal.java
sulong/projects/com.oracle.truffle.llvm.runtime/src/com/oracle/truffle/llvm/runtime/nodes/others/LLVMAccessElemPtrSymbolNode.java

Parse, store and use an LLVM symbol which refers to a GetElementPointer instruction

(LLVM) GetElementPointer symbol

---

substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/resources/NativeImageResourceFileSystemProvider.java

Before this PR, the implementation `NativeImageResourceFileSystemProvider#newFileSystem` was too greedy. 
If the NativeImageResourceFileSystemProvider is first in the list of `FileSystemProvider.installedProviders()` and the user uses `java.nio.file.FileSystems#newFileSystem(java.nio.file.Path, java.lang.ClassLoader)` it will be picked even when the requested filesystem is for a zip-file.
Other FileSystemProvider makes sure that they only return a FileSystem for Paths and URIs that they are responsible for. If they see a Path or URI that does not represent the file system they can provide they throw an UnsupportedOperationException to ensure the next FileSystemProvider in the list has a chance to construct a FileSystem for the given Path/URI.
Both variants of …

[GR-33063] NativeImageResourceFileSystemProvider is used only in cases when Path/URI is from the resource system.

---

substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JNIRegistrationAWTSupport.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JNIRegistrationAwt.java

It only was a separate library for a while in OpenJDK [11.0.10, 11.0.12]
and OpenJDK 16. The patch got reverted later on. Only add the extra
library when it's actually needed.

Conditionalize loading of JNI library 'harfbuzz'

---

truffle/src/com.oracle.truffle.object/src/com/oracle/truffle/object/Debug.java

See the commits for details of each improvement.

Some improvements to options for dumping shapes

---

substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/api/HostVM.java
substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/api/SharedHostVM.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/SVMHost.java

Create a new HotSpotVM for analysis only, and extract the common part from SVMHost to SharedHostVM.
This PR is related with featue request:#3418

Establish HostVM hierarchy

---

substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/JfrNativeEventWriter.java

Native JFR event can be large or small, depends on its size whether fits a byte or an encoded long, and it has to be specified manually when writing an event via `JfrNativeEventWriter.beginEventWrite` and  `JfrNativeEventWriter.endEventWrite`.
Current none of native events is emitted as a large event, that results some of events are silently discarded. #[3636](https://github.com/oracle/graal/issues/3636) is an example.
The patch fixes emitting large event.

JFR: Fix JFR large events

---

substratevm/mx.substratevm/testhello.py

Fix Github Actions failure introduced in 7d262f0b199dc0e8b5c581009801469aaabb6db0.

[GR-38275] Fix debuginfo gate.

---

substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfARangesSectionImpl.java
substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfAbbrevSectionImpl.java
substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfFrameSectionImpl.java
substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfInfoSectionImpl.java
substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfLineSectionImpl.java
substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfLocSectionImpl.java
substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfSectionImpl.java
substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfStrSectionImpl.java

Simplify DWARF section buffer writeXXX methods

---

substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/pthread/PthreadVMLockSupport.java

Align `pthread_mutex_t` and `pthread_cond_t` on word boundary, not object alignment.

Align pthread_mutex_t and pthread_cond_t on word boundary

---

substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/aarch64/AArch64LibCHelper.java
substratevm/src/com.oracle.svm.native.libchelper/include/aarch64cpufeatures.h
substratevm/src/com.oracle.svm.native.libchelper/src/cpuid.c

Hi @zapster, does this look good to you?

Sync with AArch64.CPUFeature in JDK 19.

---

substratevm/mx.substratevm/suite.py
substratevm/src/com.oracle.graal.pointsto.standalone/src/com/oracle/graal/pointsto/standalone/PointsToAnalyzer.java
substratevm/src/com.oracle.graal.pointsto.standalone/src/com/oracle/graal/pointsto/standalone/StandaloneHost.java
substratevm/src/com.oracle.graal.pointsto.standalone/src/com/oracle/graal/pointsto/standalone/StandalonePointsToAnalysis.java
substratevm/src/com.oracle.graal.pointsto.standalone/src/com/oracle/graal/pointsto/standalone/heap/StandaloneImageHeapScanner.java
substratevm/src/com.oracle.graal.pointsto.standalone/src/com/oracle/graal/pointsto/standalone/meta/StandaloneConstantFieldProvider.java
substratevm/src/com.oracle.graal.pointsto.standalone/src/com/oracle/graal/pointsto/standalone/meta/StandaloneConstantReflectionProvider.java
substratevm/src/com.oracle.graal.pointsto.standalone/src/com/oracle/graal/pointsto/standalone/plugins/StandaloneGraphBuilderPhase.java
substratevm/src/com.oracle.graal.pointsto.standalone/src/com/oracle/graal/pointsto/standalone/util/Timer.java
substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/meta/UninitializedStaticFieldValueReader.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/ameta/AnalysisConstantReflectionProvider.java

Add standalone pointsto analysis driver class and all other necessary setting classes.
This PR is part of the standalone pointsto analysis, see https://github.com/oracle/graal/pull/4375 for details.

Add standalone pointsto driver

---

substratevm/src/com.oracle.svm.core.graal.llvm/src/com/oracle/svm/core/graal/llvm/runtime/LLVMExceptionUnwind.java

Removed unused constants in `LLVMExceptionUnwind`.

Removed unused constants.

---

substratevm/src/com.oracle.svm.core.graal.llvm/src/com/oracle/svm/core/graal/llvm/LLVMGenerator.java

Fix bit shifting behavior in LLVM back-end, as per [Java specifications](https://docs.oracle.com/javase/specs/jls/se7/html/jls-15.html#jls-15.19).

Fix bit shifting behavior in LLVM back-end, as per Java specifications

---

substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JNIRegistrationManagementExt.java

Backports #5122 (backport applied cleanly)
Closes #5273

[Backport][22.3] Only require libmanagement_ext if it's actually needed.

---

substratevm/src/com.oracle.graal.pointsto.standalone/src/com/oracle/graal/pointsto/standalone/PointsToAnalyzer.java
substratevm/src/com.oracle.graal.pointsto.standalone/src/com/oracle/graal/pointsto/standalone/StandaloneAnalysisMetaAccess.java
substratevm/src/com.oracle.graal.pointsto.standalone/src/com/oracle/graal/pointsto/standalone/StandaloneAnnotationExtractor.java
substratevm/src/com.oracle.graal.pointsto.standalone/src/com/oracle/graal/pointsto/standalone/StandalonePointsToAnalysis.java
substratevm/src/com.oracle.graal.pointsto.standalone/src/com/oracle/graal/pointsto/standalone/features/StandaloneAnalysisFeatureImpl.java

Added `com.oracle.graal.pointsto.standalone.StandaloneAnnotationExtractor` class for the changes of commit e99a961e200017a30209966c75fe3984554c0833.
Added `com.oracle.graal.pointsto.standalone.StandaloneAnalysisMetaAccess` class for the changes of commit a45aa19c1c4300ef2091cde23dfe432e957b67dc.
Modified `com.oracle.graal.pointsto.standalone.StandalonePointsToAnalysis#onTypeReachable` for the change of commit 39c2716bc591163ba9f1200cbe5ec1fb839772ad.
This PR is part of https://github.com/oracle/graal/pull/4375.

Adapt to upstream updates

---

substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JavaLangReflectSubstitutions.java

More `null` checks in `java.lang.reflect.Array.get*()`.

More checks in `java.lang.reflect.Array.get*()`.

---

.github/workflows/main.yml

Fixes recent (since the merge of https://github.com/oracle/graal/pull/6738)  CI failures, e.g.:
* https://github.com/oracle/graal/actions/runs/5176166290/jobs/9324638530
* https://github.com/oracle/graal/actions/runs/5177381458/jobs/9327406668

Remove CI jobs using non existing tags

---

substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/classinitialization/ClassInitializationFeature.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/classinitialization/ClassInitializationSupport.java

Fail fast when class initialization fails at build time

---

substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageDebugInfoProvider.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageDebugInfoProviderBase.java

This PR fixes the problem mentioned in issue #6990

Refactor debuginfo provider

---

substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/GCImpl.java
substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/ThreadLocalAllocation.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/JfrEvent.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/events/AllocationRequiringGC.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/events/EveryChunkNativePeriodicEvents.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/events/SystemGCEvent.java
substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/TestAllocationRequiringGCEvent.java
substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/TestSystemGCEvent.java

Adds a couple new JFR events related to GC.

Add support for jdk.AllocationRequiringGC and jdk.SystemGC JFR events

---

docs/reference-manual/native-image/JFR.md

Just a small update to the JFR documentation to include the new Native Memory Tracking events and JCMD support. 
Thanks!

Update JFR docs with NMT events and JCMD
